/* ============================================================
   990 — LE SCALPEL
   Palier de grammaire « haute précision ».
   Principes de conception (≠ des leçons de base) :
     1. Le DÉCLENCHEUR est éloigné du blanc (groupe intercalé, subordonnée)
        → impossible de répondre au coup d'œil, il faut analyser la phrase.
     2. Les 4 options sont TOUTES de l'anglais correct ailleurs
        → seul le contexte en élimine trois.
     3. On teste des CONTRASTES (deux formes possibles, deux sens différents),
        pas des règles à réciter.
     4. Chaque item porte une 5e case : l'AUTOPSIE des distracteurs
        (« pourquoi les autres sont fausses »), affichée après la réponse.

   Format : [énoncé, [options], indexBonne, explication, autopsie]
   Chargé APRÈS data.js / advanced.js. Flag hard:true → carte dédiée.
   ============================================================ */

window.LESSONS.push(

/* ---------------------------------------------------------- 1 */
{
  id: "sc-agree", hard: true, always: true,
  title: "L'accord au scalpel",
  tag: "🔪 Scalpel · le vrai sujet",
  note: "Le verbe s'accorde avec le <b>noyau</b> du groupe sujet, jamais avec le mot le plus proche du blanc. Les pièges de haut niveau : <b>a number of</b> (pluriel) vs <b>the number of</b> (singulier) ; <b>neither… nor…</b> s'accorde avec le terme LE PLUS PROCHE ; <b>along with / as well as / together with</b> n'ajoutent rien au sujet ; <b>each / every one / not one / a series of</b> restent singuliers ; <b>criteria, data, media, phenomena</b> sont des pluriels ; le nom d'une discipline (<i>statistics, economics</i>) est singulier, mais <i>the statistics</i> = les chiffres, pluriel.",
  q: [
    ["A number of the proposals submitted before the June deadline ______ still awaiting approval.",
     ["is", "are", "was", "has been"], 1,
     "« A number of + pluriel » = « plusieurs » → verbe PLURIEL : are.",
     "🔑 Déclencheur : <b>A number of</b> (≠ <i>the</i> number of). Le noyau réel est <i>proposals</i>.<br>✗ <b>is / was</b> : accordés sur le mot voisin <i>deadline</i>, pas sur le sujet. ✗ <b>has been</b> : même faute, et le present perfect ne colle pas à <i>still awaiting</i>."],
    ["The number of complaints filed against that supplier ______ risen sharply since January.",
     ["have", "has", "are", "were"], 1,
     "« The number of » = le chiffre lui-même → SINGULIER : has risen.",
     "🔑 Déclencheur : <b>The</b> number of. Le noyau est <i>number</i>, singulier ; <i>of complaints</i> n'est qu'un complément.<br>✗ <b>have</b> : c'est l'accord sur <i>complaints</i>, le piège exact de cet item. ✗ <b>are / were</b> : il faut un auxiliaire de perfect devant <i>risen</i>."],
    ["Neither the regional managers nor the finance director ______ been informed of the restructuring.",
     ["have", "has", "having", "were"], 1,
     "Avec « neither… nor… », le verbe s'accorde avec le terme LE PLUS PROCHE : <i>the finance director</i>, singulier → has.",
     "🔑 Déclencheur : la règle de proximité. Inverse l'ordre (<i>Neither the director nor the managers <b>have</b>…</i>) et la réponse change.<br>✗ <b>have</b> : accord sur <i>managers</i>, qui est le terme ÉLOIGNÉ. ✗ <b>were</b> : <i>been</i> exige have/has. ✗ <b>having</b> : forme non conjuguée, la phrase n'aurait plus de verbe principal."],
    ["The chief executive, along with her two deputies, ______ expected to attend the parliamentary hearing.",
     ["are", "is", "were", "have"], 1,
     "« along with » n'ajoute pas au sujet : il reste <i>The chief executive</i>, singulier → is.",
     "🔑 Déclencheur : les virgules. <i>along with / as well as / together with / in addition to</i> introduisent une incise, pas un second sujet.<br>✗ <b>are / were</b> : accord illicite sur <i>deputies</i>. ✗ <b>have</b> : incompatible avec <i>expected</i> au passif présent."],
    ["Not one of the safety inspections carried out that year ______ the slightest irregularity.",
     ["have revealed", "has revealed", "were revealing", "reveal"], 1,
     "« Not one of » est SINGULIER → has revealed.",
     "🔑 Déclencheur : <b>Not one of</b> (= pas un seul). Même logique que <i>each of / every one of / neither of</i>.<br>✗ <b>have revealed / reveal</b> : accord sur <i>inspections</i>. ✗ <b>were revealing</b> : un progressif ne convient pas à un constat de bilan."],
    ["Two-thirds of the documentation supplied by the contractor ______ still missing.",
     ["are", "is", "have", "were"], 1,
     "Une fraction s'accorde avec le nom qui suit « of » : <i>documentation</i> est INDÉNOMBRABLE → is.",
     "🔑 Déclencheur : <i>documentation</i>, pas <i>two-thirds</i>. Compare : <i>Two-thirds of the <b>documents are</b> missing.</i><br>✗ <b>are / were</b> : c'est le réflexe français (« les deux tiers sont »). ✗ <b>have</b> : il n'y a pas de participe passé derrière."],
    ["He is one of those managers who ______ never satisfied with a first draft.",
     ["is", "are", "has been", "was"], 1,
     "Le relatif « who » reprend <i>those managers</i> (pluriel), pas <i>one</i> → are.",
     "🔑 Déclencheur : <b>those managers</b> juste avant <i>who</i>. Test : <i>Of those managers who are never satisfied, he is one.</i><br>✗ <b>is / was / has been</b> : accord sur <i>one</i>. Il n'est correct que dans <i>He is <b>the only one</b> of those managers who <b>is</b>…</i>"],
    ["Statistics ______ a compulsory course for every first-year student on the programme.",
     ["are", "is", "have been", "were"], 1,
     "Nom de discipline en -ics → SINGULIER : is.",
     "🔑 Déclencheur : pas d'article devant <i>Statistics</i> et un attribut au singulier (<i>a course</i>).<br>✗ <b>are / were</b> : ce serait <i>The statistics <b>are</b> alarming</i> (= les chiffres). Même piège avec <i>economics, politics, ethics, physics</i>."],
    ["Every one of the contracts drafted by the outgoing legal team ______ to be reviewed before signature.",
     ["need", "needs", "are needing", "have"], 1,
     "« Every one of » est singulier → needs.",
     "🔑 Déclencheur : <b>Every one of</b>. Ne pas confondre avec <i>every<b>one</b></i> (tout le monde), lui aussi singulier d'ailleurs.<br>✗ <b>need / have</b> : accord sur <i>contracts</i>, à dix mots du verbe. ✗ <b>are needing</b> : <i>need</i> est un verbe d'état, pas de progressif."],
    ["The criteria on which the shortlist was drawn up ______ never been made public.",
     ["has", "have", "is", "was"], 1,
     "<i>Criteria</i> est le PLURIEL de <i>criterion</i> → have.",
     "🔑 Déclencheur : la forme <i>criteri<b>a</b></i>. Même famille : <i>data, media, phenomena, bacteria</i> (sing. <i>datum, medium, phenomenon, bacterium</i>).<br>✗ <b>has / was</b> : accord sur <i>shortlist</i>, qui appartient à la relative. ✗ <b>is</b> : incompatible avec <i>been</i>."]
  ]
},

/* ---------------------------------------------------------- 2 */
{
  id: "sc-participle", hard: true, always: true,
  title: "Le sujet caché · participiales & absolues",
  tag: "🔪 Scalpel · structure",
  note: "Une proposition participiale (<i>Having reviewed…, Alarmed by…, Not knowing…</i>) n'a pas de sujet exprimé : l'anglais lui attribue automatiquement <b>le sujet de la principale</b>. Si ce n'est pas le bon, la phrase est fautive (<i>dangling participle</i>) — faute lourde à l'écrit. Deux structures de haut niveau : la <b>construction absolue</b> (<i>The contract having been signed, …</i> — un sujet propre + participe) et <b>with + complément + participe</b> (<i>with the deadline approaching, with the paperwork completed</i>).",
  q: [
    ["Having reviewed the quarterly figures in detail, ______.",
     ["the decision was postponed", "the board postponed the decision", "it was decided to postpone the vote", "postponing the decision seemed wise"], 1,
     "Celui qui a examiné les chiffres doit être le SUJET de la principale : the board.",
     "🔑 Déclencheur : <i>Having reviewed</i> attend un être humain en position sujet.<br>✗ <b>the decision was postponed</b> : ce serait la décision qui a lu les chiffres. ✗ <b>it was decided</b> : <i>it</i> impersonnel ne peut pas lire. ✗ <b>postponing… seemed wise</b> : le sujet est un gérondif, même faute."],
    ["______ by the discrepancies in the ledger, the auditors demanded a second set of accounts.",
     ["Alarmed", "Alarming", "To alarm", "Having alarmed"], 0,
     "Les auditeurs SUBISSENT l'alarme → participe passé (sens passif) : Alarmed by.",
     "🔑 Déclencheur : <b>by</b>, marque du complément d'agent. Passif → participe en -ed.<br>✗ <b>Alarming</b> : sens actif (« qui alarme ») — ce sont les écarts qui alarment, pas les auditeurs. ✗ <b>To alarm</b> : exprimerait un but. ✗ <b>Having alarmed</b> : actif et antérieur, contresens."],
    ["The contract ______ signed by both parties, the negotiators moved on to delivery dates.",
     ["was", "having been", "had been", "being"], 1,
     "Construction absolue avec antériorité : <i>The contract having been signed, …</i>",
     "🔑 Déclencheur : la virgule + une principale qui a déjà son sujet (<i>the negotiators</i>). Il faut donc une forme NON conjuguée.<br>✗ <b>was / had been</b> : deux propositions conjuguées collées sans coordination (<i>comma splice</i>). ✗ <b>being signed</b> : simultané et inachevé — ils passeraient à la suite pendant la signature."],
    ["With the deadline ______ and two engineers off sick, the team agreed to work the weekend.",
     ["approached", "approaching", "to approach", "approach"], 1,
     "« with + complément + participe présent » = circonstance en cours : approaching.",
     "🔑 Déclencheur : <b>with</b> + un nom qui AGIT (l'échéance approche d'elle-même) → -ing.<br>✗ <b>approached</b> : participe passé = sens passif (« l'échéance étant approchée »), impossible ici. ✗ <b>to approach / approach</b> : aucune de ces formes ne suit <i>with + nom</i>."],
    ["With all the paperwork finally ______, we can close the file this afternoon.",
     ["completing", "completed", "to complete", "complete"], 1,
     "Ici le complément SUBIT l'action → participe passé : with the paperwork completed.",
     "🔑 Déclencheur : les dossiers ne remplissent rien, on les remplit → passif.<br>✗ <b>completing</b> : sens actif, exactement l'erreur inverse de l'item précédent — c'est ce contraste qui est testé. ✗ <b>to complete</b> : valeur de but. ✗ <b>complete</b> : adjectif possible en langue relâchée, mais la structure attend le participe."],
    ["The proposal ______ by the consultants last month has since been quietly withdrawn.",
     ["submitted", "submitting", "was submitted", "has submitted"], 0,
     "Relative réduite au passif : <i>the proposal (which was) submitted by…</i>",
     "🔑 Déclencheur : <b>has been withdrawn</b> plus loin est DÉJÀ le verbe principal — le blanc ne peut donc pas être conjugué.<br>✗ <b>was submitted / has submitted</b> : donneraient deux verbes principaux. ✗ <b>submitting</b> : sens actif, la proposition se serait soumise elle-même."],
    ["Not ______ how the committee would react, she prepared answers to every objection.",
     ["knowing", "known", "to know", "she knew"], 0,
     "Participiale négative active : Not knowing how…",
     "🔑 Déclencheur : le sujet <i>she</i> est bien celui qui ne sait pas → participe présent.<br>✗ <b>known</b> : passif (« n'étant pas connue »). ✗ <b>to know</b> : <i>Not to know</i> existe mais en emploi nominal, pas circonstanciel. ✗ <b>she knew</b> : deux propositions conjuguées sans lien."],
    ["______ from the top of the northern ridge, the whole valley looks deceptively flat.",
     ["Seeing", "Seen", "To see", "Having seen"], 1,
     "C'est la vallée qui est VUE → participe passé : Seen from…",
     "🔑 Déclencheur : le sujet de la principale est <i>the valley</i>, objet du regard.<br>✗ <b>Seeing</b> : le classique dangling — la vallée regarderait depuis la crête. ✗ <b>Having seen</b> : même faute, avec antériorité en plus. ✗ <b>To see</b> : but."],
    ["All things ______, the second offer is the more attractive of the two.",
     ["considering", "considered", "to consider", "consider"], 1,
     "Absolue figée : <i>All things considered</i> = tout bien considéré.",
     "🔑 Déclencheur : les choses sont considérées PAR quelqu'un → passif.<br>✗ <b>considering</b> : <i>Considering all things</i> serait correct, mais pas <i>All things considering</i> — l'ordre décide. ✗ <b>to consider / consider</b> : pas de forme conjuguée ni d'infinitif dans une absolue."],
    ["______ no further questions from the floor, the chair declared the session closed.",
     ["There being", "There is", "Being there", "It being"], 0,
     "Absolue existentielle : <i>There being no further questions, …</i> (registre très soutenu).",
     "🔑 Déclencheur : la principale a déjà son sujet (<i>the chair</i>) et son verbe → la première proposition doit être non conjuguée.<br>✗ <b>There is</b> : conjugué, il faudrait <i>As there were…</i> ✗ <b>Being there</b> : inversion impossible avec le <i>there</i> existentiel. ✗ <b>It being</b> : <i>it</i> ne peut pas introduire <i>no further questions</i>."]
  ]
},

/* ---------------------------------------------------------- 3 */
{
  id: "sc-tense", hard: true, always: true,
  title: "Le fil des temps",
  tag: "🔪 Scalpel · verbe",
  note: "En anglais soutenu, les temps se répondent d'une proposition à l'autre. Points de contrôle : <b>past perfect</b> obligatoire pour l'antériorité dans un récit passé (<i>by the time…, it was the first time…</i>) ; <b>pas de « will » dans une subordonnée de temps</b> (<i>until / as soon as / when</i> + présent) ; <b>backshift</b> au discours indirect ; <b>would</b> = habitude passée (mais jamais pour un état) ; <b>present perfect interdit</b> dès qu'un repère passé daté est présent.",
  q: [
    ["By the time the auditors finally arrived, the finance team ______ every invoice for the quarter.",
     ["checked", "had checked", "has checked", "was checking"], 1,
     "« By the time » + prétérit → l'action antérieure passe au past perfect : had checked.",
     "🔑 Déclencheur : <b>By the time … arrived</b> pose un repère passé ; ce qui le précède recule d'un cran.<br>✗ <b>checked</b> : rendrait les deux actions simultanées. ✗ <b>has checked</b> : le present perfect est incompatible avec un repère passé. ✗ <b>was checking</b> : action en cours, alors que <i>every invoice</i> impose un résultat achevé."],
    ["It was the first time in her career that she ______ asked to chair a board meeting.",
     ["was", "has been", "had been", "would be"], 2,
     "« It was the first time (that) » entraîne le past perfect : had been asked.",
     "🔑 Déclencheur : <b>It was</b> (et non <i>It is</i>) ; le bilan se fait à partir d'un point du passé.<br>✗ <b>was</b> : simple prétérit, l'antériorité disparaît. ✗ <b>has been</b> : ce serait la version présente (<i>It <b>is</b> the first time she <b>has been</b> asked</i>). ✗ <b>would be</b> : projection future, hors sujet."],
    ["The supplier assured us that the replacement parts ______ dispatched the previous week.",
     ["have been", "had been", "were being", "would have been"], 1,
     "Discours indirect au passé + antériorité (<i>the previous week</i>) → had been dispatched.",
     "🔑 Déclencheur : <b>assured</b> (passé) + <b>the previous week</b> (antérieur au moment rapporté).<br>✗ <b>have been</b> : absence de backshift, faute classique. ✗ <b>were being</b> : action en cours, contredit <i>the previous week</i>. ✗ <b>would have been</b> : sens hypothétique non réalisé."],
    ["We will not sign anything until the lawyers ______ the final version of the clause.",
     ["will approve", "approve", "would approve", "will have approved"], 1,
     "Pas de « will » dans une subordonnée de temps : until + PRÉSENT (valeur future).",
     "🔑 Déclencheur : <b>until</b>, subordonnant temporel. Idem <i>when, as soon as, before, once, by the time</i>.<br>✗ <b>will approve / will have approved</b> : le futur est déjà porté par la principale. ✗ <b>would approve</b> : concordance de passé, or la principale est au futur."],
    ["She ______ for the same firm ever since her first internship there, and shows no sign of leaving.",
     ["works", "worked", "has been working", "had worked"], 2,
     "Action commencée dans le passé et TOUJOURS en cours → present perfect continu.",
     "🔑 Déclencheur : <b>ever since</b> + <i>shows no sign of leaving</i> (le lien avec le présent est explicite).<br>✗ <b>works</b> : le présent simple ne relie pas au passé — c'est le calque du français « elle travaille depuis ». ✗ <b>worked</b> : coupe le lien avec le présent. ✗ <b>had worked</b> : exigerait un repère passé."],
    ["By the end of next year, the Rouen plant ______ in operation for two full decades.",
     ["is", "will be", "will have been", "has been"], 2,
     "Bilan à une échéance future → future perfect : will have been.",
     "🔑 Déclencheur : <b>By the end of next year</b> + <b>for two decades</b> = durée arrêtée à une date à venir.<br>✗ <b>will be</b> : état futur ponctuel, sans la durée accumulée. ✗ <b>is / has been</b> : ancrés dans le présent, incompatibles avec <i>next year</i>."],
    ["When he ran the Lyon office, he ______ arrive before seven every single morning.",
     ["would", "used", "was used to", "will"], 0,
     "Habitude répétée dans le passé → would + base verbale.",
     "🔑 Déclencheur : <b>every single morning</b> = action répétée (et non un état).<br>✗ <b>used</b> : il manque <i>to</i> (<i>used to arrive</i>). ✗ <b>was used to</b> : signifie « était habitué à » et appelle un -ing (<i>to arriving</i>). ✗ <b>will</b> : rupture de temps."],
    ["I ______ to the airport when the client rang to cancel the whole visit.",
     ["drove", "had driven", "was driving", "have driven"], 2,
     "Cadre en cours interrompu par un événement ponctuel → prétérit continu.",
     "🔑 Déclencheur : <b>when + prétérit ponctuel</b> (<i>rang</i>) coupe une action en déroulement.<br>✗ <b>drove</b> : deux actions successives, on perd l'interruption. ✗ <b>had driven</b> : antériorité achevée. ✗ <b>have driven</b> : present perfect avec repère passé, impossible."],
    ["Hardly ______ the announcement been made when the share price began to slide.",
     ["has", "had", "did", "was"], 1,
     "Structure figée : <i>Hardly had + sujet + participe … when …</i>",
     "🔑 Déclencheur : le couple <b>Hardly … when</b> impose le past perfect ET l'inversion.<br>✗ <b>has</b> : present perfect, incompatible avec <i>began</i>. ✗ <b>did</b> : <i>did … been</i> est agrammatical. ✗ <b>was</b> : <i>was the announcement been made</i> n'existe pas."],
    ["This time next Thursday, we ______ these very results with the investors in Frankfurt.",
     ["discuss", "will discuss", "will be discussing", "will have discussed"], 2,
     "Action EN COURS à un moment futur précis → future continuous.",
     "🔑 Déclencheur : <b>This time next Thursday</b> désigne un instant futur pendant lequel l'action se déroule.<br>✗ <b>will discuss</b> : fait futur global, sans le déroulement. ✗ <b>will have discussed</b> : action terminée AVANT cette date. ✗ <b>discuss</b> : présent simple réservé aux horaires fixes."]
  ]
},

/* ---------------------------------------------------------- 4 */
{
  id: "sc-cond", hard: true, always: true,
  title: "Conditionnels mixtes & inversés",
  tag: "🔪 Scalpel · irréel",
  note: "Au-delà des trois types scolaires : les <b>conditionnels mixtes</b> croisent les époques (<i>If she had noticed…, the firm would still be solvent</i> = cause passée / effet présent ; <i>If he were more cautious, he would never have signed</i> = état présent / effet passé). Et surtout l'<b>inversion sans « if »</b>, marque d'anglais très soutenu : <i>Had it not been for…, Should you require…, Were the board to reject…</i>. Ajoute <i>but for, otherwise, I'd rather, as if</i>.",
  q: [
    ["If she ______ the warning signs in the 2019 audit, the company would still be solvent today.",
     ["noticed", "had noticed", "has noticed", "would notice"], 1,
     "Mixte : cause dans le passé (<i>had noticed</i>) → conséquence dans le présent (<i>would still be</i>).",
     "🔑 Déclencheur : <b>today</b> dans la principale + une date passée dans la subordonnée. Les deux époques diffèrent.<br>✗ <b>noticed</b> : donnerait un type 2 tout entier au présent irréel. ✗ <b>has noticed</b> : jamais après <i>if</i> hypothétique. ✗ <b>would notice</b> : <i>would</i> ne se met pas dans la subordonnée en if."],
    ["If he ______ a more cautious investor by nature, he would never have signed that contract.",
     ["was", "were", "had been", "would be"], 1,
     "Mixte inverse : état permanent au présent (<i>were</i>) → conséquence passée (<i>would never have signed</i>).",
     "🔑 Déclencheur : <b>by nature</b> = trait durable, donc actuel ; la principale, elle, est au passé.<br>✗ <b>had been</b> : ferait un type 3 pur et perdrait la nuance « il EST ainsi ». ✗ <b>was</b> : toléré à l'oral, mais le subjonctif <i>were</i> est attendu au registre soutenu. ✗ <b>would be</b> : proscrit dans la subordonnée."],
    ["______ it not been for the emergency loan from the parent company, the firm would have folded.",
     ["Were", "Had", "Should", "If"], 1,
     "Conditionnel type 3 inversé : <i>Had it not been for…</i> = <i>If it had not been for…</i>",
     "🔑 Déclencheur : <b>been</b> juste après → il faut l'auxiliaire du past perfect.<br>✗ <b>Were</b> : donnerait <i>Were it not for</i> (présent irréel), incompatible avec <i>would have folded</i>. ✗ <b>Should</b> : éventualité future. ✗ <b>If</b> : correct seulement suivi de <i>it had not been</i> — l'ordre des mots l'exclut ici."],
    ["______ you require any further clarification, please contact our legal department directly.",
     ["Should", "Would", "Were", "Had"], 0,
     "Éventualité polie et future, inversée : <i>Should you require…</i> = <i>If you should require…</i>",
     "🔑 Déclencheur : la formule de courtoisie + <b>require</b> à la base verbale.<br>✗ <b>Were</b> : demanderait <i>Were you to require</i>. ✗ <b>Had</b> : appellerait un participe passé. ✗ <b>Would</b> : ne s'invertit jamais en tête de condition."],
    ["______ the board to reject the recommendation, the entire funding round would collapse.",
     ["Were", "Was", "Had", "Should"], 0,
     "Hypothèse peu probable, registre formel : <i>Were + sujet + to + base</i>.",
     "🔑 Déclencheur : le <b>to reject</b> qui suit — seul <i>were</i> se construit ainsi.<br>✗ <b>Was</b> : l'inversion conditionnelle n'accepte que <i>were</i>, à toutes les personnes. ✗ <b>Had</b> : exigerait <i>had the board rejected</i>. ✗ <b>Should</b> : <i>Should the board reject</i> (sans <i>to</i>) serait correct — c'est le <i>to</i> qui tranche."],
    ["But for your intervention at the last minute, the deal ______ through.",
     ["wouldn't go", "wouldn't have gone", "didn't go", "hadn't gone"], 1,
     "« But for » = sans / n'eût été. Ici le fait est PASSÉ → wouldn't have gone.",
     "🔑 Déclencheur : <b>at the last minute</b> renvoie à un épisode révolu.<br>✗ <b>wouldn't go</b> : irréel du présent. ✗ <b>didn't go</b> : fait réel, or l'affaire s'est bien conclue. ✗ <b>hadn't gone</b> : il manque <i>would</i>, la principale n'est plus conditionnelle."],
    ["I'd rather you ______ anything to the press until the official announcement on Monday.",
     ["don't say", "didn't say", "won't say", "hadn't said"], 1,
     "« would rather + sujet + prétérit » pour une préférence sur le présent/futur.",
     "🔑 Déclencheur : <b>I'd rather + you</b> (sujet différent) → prétérit à valeur non passée.<br>✗ <b>don't say</b> : le présent suit <i>I'd rather</i> seulement dans l'anglais très relâché. ✗ <b>won't say</b> : jamais de <i>will</i> ici. ✗ <b>hadn't said</b> : regret sur du passé, contredit <i>until Monday</i>."],
    ["He talks about the takeover as if it ______ already a done deal.",
     ["is", "was", "were", "had been"], 2,
     "« as if » + irréel → subjonctif were (ce n'est pas le cas).",
     "🔑 Déclencheur : <b>as if</b> + un fait présenté comme faux. Registre soutenu → <i>were</i>.<br>✗ <b>is</b> : signifierait que c'est probablement vrai. ✗ <b>was</b> : courant à l'oral, mais c'est justement la précision testée. ✗ <b>had been</b> : décalerait au passé, or <i>already</i> renvoie au présent."],
    ["The train was held up outside Lille; otherwise we ______ there well before noon.",
     ["would be", "would have been", "will be", "had been"], 1,
     "« otherwise » porte une condition implicite passée : sinon nous y SERIONS ARRIVÉS.",
     "🔑 Déclencheur : <b>was held up</b> — le fait est accompli, donc l'irréel porte sur le passé.<br>✗ <b>would be</b> : irréel du présent. ✗ <b>will be</b> : futur réel, contredit le retard. ✗ <b>had been</b> : plus de valeur conditionnelle."],
    ["Suppose the merger ______ at the last stage — what would happen to the Bordeaux plant?",
     ["fails", "failed", "would fail", "has failed"], 1,
     "Le <i>would</i> de la question impose un scénario hypothétique → prétérit : failed.",
     "🔑 Déclencheur : <b>what <i>would</i> happen</b>. Avec <i>what <b>will</b> happen</i>, <i>fails</i> deviendrait correct.<br>✗ <b>fails</b> : éventualité réelle, désaccordée avec <i>would</i>. ✗ <b>would fail</b> : pas de <i>would</i> dans la condition. ✗ <b>has failed</b> : fait accompli, incompatible avec une supposition."]
  ]
},

/* ---------------------------------------------------------- 5 */
{
  id: "sc-rel", hard: true, always: true,
  title: "Relatives chirurgicales",
  tag: "🔪 Scalpel · structure",
  note: "Le niveau supérieur des relatives : <b>préposition + which/whom</b> (<i>the terms under which…, the extent to which…</i>) — et alors <b>that est interdit</b> ; <b>quantifieur + of whom / of which</b> (<i>none of whom, most of whom, several of which</i>) ; <b>whose</b> s'emploie aussi pour les choses ; <b>which</b> peut reprendre TOUTE une proposition ; après une virgule, <b>that est impossible</b>.",
  q: [
    ["The terms ______ the loan was originally granted have never been disclosed to shareholders.",
     ["under which", "which", "that", "under that"], 0,
     "On dit <i>grant a loan <b>under</b> certain terms</i> → la préposition remonte avec le relatif.",
     "🔑 Déclencheur : le verbe <i>granted</i> reste sans complément à la fin — il manque donc la préposition.<br>✗ <b>which / that</b> : la phrase resterait bancale (<i>…the loan was granted ___</i>). ✗ <b>under that</b> : <i>that</i> ne suit jamais une préposition en anglais standard."],
    ["She interviewed forty candidates, ______ had any experience in the sector.",
     ["none of them", "none of whom", "none of which", "whom none of"], 1,
     "Quantifieur + <b>of whom</b> pour des personnes, dans une relative non déterminative.",
     "🔑 Déclencheur : la virgule impose un RELATIF, pas un pronom personnel.<br>✗ <b>none of them</b> : deux propositions indépendantes collées (comma splice). ✗ <b>none of which</b> : <i>which</i> ne reprend pas des personnes. ✗ <b>whom none of</b> : ordre des mots impossible."],
    ["The extent ______ the figures had been manipulated only emerged during the trial.",
     ["to which", "which", "that", "of which"], 0,
     "Locution figée : <i>the extent <b>to</b> which</i> = la mesure dans laquelle.",
     "🔑 Déclencheur : <i>extent</i> appelle toujours <b>to</b> (<i>to a large extent</i>).<br>✗ <b>which / that</b> : la préposition manque. ✗ <b>of which</b> : donnerait « l'étendue de laquelle », calque du français."],
    ["The building, ______ roof was torn off in the storm, has been closed to the public.",
     ["which", "whose", "that", "of which its"], 1,
     "<i>whose</i> s'emploie aussi pour les objets : <i>the building whose roof…</i>",
     "🔑 Déclencheur : un lien de possession entre <i>building</i> et <i>roof</i>.<br>✗ <b>which</b> : <i>the roof of which</i> serait correct, mais pas <i>which roof</i>. ✗ <b>that</b> : exclu après une virgule. ✗ <b>of which its</b> : double marque de possession."],
    ["He missed the filing deadline by two days, ______ came as a surprise to absolutely no one.",
     ["that", "what", "which", "who"], 2,
     "<i>which</i> reprend ici TOUTE la proposition précédente (le fait d'avoir raté l'échéance).",
     "🔑 Déclencheur : la virgule + un commentaire sur l'ensemble de l'énoncé.<br>✗ <b>that</b> : impossible après virgule et incapable de reprendre une proposition. ✗ <b>what</b> : ne peut pas avoir d'antécédent. ✗ <b>who</b> : réservé aux personnes."],
    ["This is precisely the kind of dispute ______ there is no obvious solution.",
     ["to which", "which", "that", "for that"], 0,
     "<i>a solution <b>to</b> a problem</i> → la préposition remonte : <i>the dispute to which there is no solution</i>.",
     "🔑 Déclencheur : en anglais, une solution est <b>to</b> quelque chose (jamais <i>of</i>).<br>✗ <b>which / that</b> : préposition manquante. ✗ <b>for that</b> : mauvaise préposition ET <i>that</i> après préposition."],
    ["There were several technical points on ______ the two delegations could not agree.",
     ["that", "which", "what", "them"], 1,
     "Après une préposition, seul <b>which</b> (choses) ou <b>whom</b> (personnes) est possible.",
     "🔑 Déclencheur : le <b>on</b> déjà écrit devant le blanc.<br>✗ <b>that</b> : la règle la plus stricte de l'anglais — jamais après préposition. ✗ <b>what</b> : pas d'antécédent possible. ✗ <b>them</b> : ce n'est pas un relatif, la phrase perdrait sa subordination."],
    ["The firm now employs just over three hundred people, ______ work entirely remotely.",
     ["most of them", "most of whom", "most of which", "the most of whom"], 1,
     "Quantifieur + of whom, relative non déterminative sur des personnes.",
     "🔑 Déclencheur : virgule + verbe conjugué derrière (<i>work</i>) : il faut un relatif SUJET.<br>✗ <b>most of them</b> : juxtaposition fautive de deux propositions. ✗ <b>most of which</b> : <i>people</i> = personnes. ✗ <b>the most of whom</b> : <i>most</i> quantifieur ne prend pas d'article."],
    ["He delivered a speech the length of ______ tested even his most loyal supporters.",
     ["which", "that", "whose", "it"], 0,
     "Structure formelle <i>the … of which</i> : <i>the length of which</i> = dont la longueur.",
     "🔑 Déclencheur : <b>of</b> devant le blanc → obligatoirement <i>which</i>.<br>✗ <b>that</b> : après préposition, interdit. ✗ <b>whose</b> : il faudrait <i>whose length tested…</i> — pas de <i>of</i>. ✗ <b>it</b> : supprime la subordination."],
    ["It was her tone, rather than her argument, ______ finally offended the committee.",
     ["which", "that", "what", "who"], 1,
     "Phrase clivée <i>It is/was X <b>that</b>…</i> : la forme standard du clivage anglais.",
     "🔑 Déclencheur : le montage <b>It was … ______ …</b> = mise en relief.<br>✗ <b>which</b> : dans une clivée, la norme reste <i>that</i>, surtout quand l'élément mis en relief est mixte ou abstrait. ✗ <b>what</b> : donnerait <i>What offended the committee was her tone</i> — autre construction. ✗ <b>who</b> : <i>tone</i> n'est pas une personne."]
  ]
},

/* ---------------------------------------------------------- 6 */
{
  id: "sc-patterns", hard: true, always: true,
  title: "Complémentation verbale",
  tag: "🔪 Scalpel · verbe",
  note: "Chaque verbe impose SA construction, et c'est là que le français calque le plus : <i>prevent sb <b>from</b> doing</i>, <i>accuse sb <b>of</b> doing</i>, <i>object <b>to</b> doing</i>, <i>insist <b>on</b> doing</i>, <i>provide <b>for</b></i>, <i>deprive <b>of</b></i>. Trois pièges structurels : <b>suggest / recommend</b> n'acceptent JAMAIS « quelqu'un + to » ; <b>have / get something done</b> (faire faire) ; au passif, <b>make</b> récupère un <i>to</i> (<i>were made to work</i>). Et à l'écrit soutenu, le gérondif prend un possessif (<i>the chairman's having overruled…</i>).",
  q: [
    ["The new confidentiality clause prevents employees ______ discussing their salaries publicly.",
     ["to", "of", "from", "for"], 2,
     "<i>prevent somebody <b>from</b> doing</i> — la préposition est obligatoire.",
     "🔑 Déclencheur : <i>prevent</i>, comme <i>stop, keep, discourage, prohibit</i>, se construit avec <b>from + -ing</b>.<br>✗ <b>to</b> : calque de « empêcher de ». ✗ <b>of</b> : construction de <i>accuse / convince</i>. ✗ <b>for</b> : celle de <i>blame / criticise</i>."],
    ["She suggested ______ the vote until the independent figures had been verified.",
     ["us to postpone", "postponing", "to postpone", "that we postponing"], 1,
     "<i>suggest</i> + gérondif, ou <i>suggest that we postpone</i> — jamais « suggest somebody to ».",
     "🔑 Déclencheur : <b>suggest</b> (idem <i>recommend, propose, advise that</i>).<br>✗ <b>us to postpone</b> : la faute la plus fréquente des francophones. ✗ <b>to postpone</b> : <i>suggest</i> n'admet pas l'infinitif seul. ✗ <b>that we postponing</b> : après <i>that</i>, il faut une forme conjuguée ou la base."],
    ["Before the inspection, the manager had the entire paper archive ______ by an outside firm.",
     ["digitise", "digitised", "to digitise", "digitising"], 1,
     "<i>have + objet + participe passé</i> = faire faire quelque chose (par un tiers).",
     "🔑 Déclencheur : <b>by an outside firm</b> — l'archive subit l'action.<br>✗ <b>digitise</b> : <i>have somebody digitise</i> serait correct, mais l'objet ici est <i>the archive</i>, pas une personne. ✗ <b>to digitise</b> : jamais après <i>have</i> causatif. ✗ <b>digitising</b> : sens actif et en cours."],
    ["The night staff were made ______ three consecutive weekends without extra pay.",
     ["work", "to work", "working", "worked"], 1,
     "<i>make somebody do</i> ACTIF, mais <i>be made <b>to</b> do</i> au PASSIF.",
     "🔑 Déclencheur : <b>were made</b> = passif. C'est le seul cas où <i>make</i> récupère le <i>to</i>.<br>✗ <b>work</b> : correct uniquement à l'actif (<i>They made the staff work</i>). ✗ <b>working / worked</b> : ni l'un ni l'autre ne suit <i>be made</i>."],
    ["The regulator accused the supplier ______ systematically inflating its invoices.",
     ["for", "of", "with", "to"], 1,
     "<i>accuse somebody <b>of</b> doing</i>.",
     "🔑 Déclencheur : <i>accuse</i> gouverne <b>of</b> ; <i>blame</i> gouverne <b>for</b> — c'est le couple à ne pas confondre.<br>✗ <b>for</b> : <i>blame sb for / criticise sb for</i>. ✗ <b>with</b> : <i>charge sb with</i> (inculper). ✗ <b>to</b> : jamais avec <i>accuse</i>."],
    ["Nobody on the committee objected ______ the deadline forward by a fortnight.",
     ["to bring", "to bringing", "bring", "for bringing"], 1,
     "<i>object <b>to</b></i> : le <i>to</i> est une PRÉPOSITION → suivi du gérondif.",
     "🔑 Déclencheur : le piège du faux infinitif. Même famille : <i>look forward to, be used to, be opposed to, admit to</i>.<br>✗ <b>to bring</b> : lecture erronée du <i>to</i> comme infinitif. ✗ <b>bring</b> : préposition manquante. ✗ <b>for bringing</b> : mauvaise préposition."],
    ["The auditors insisted ______ the original receipts before signing off the accounts.",
     ["to see", "on seeing", "of seeing", "in seeing"], 1,
     "<i>insist <b>on</b> doing</i> (ou <i>insist that + base</i>).",
     "🔑 Déclencheur : <i>insist</i> refuse l'infinitif. Comparer : <i>The auditors insisted that the receipts <b>be</b> produced.</i><br>✗ <b>to see</b> : calque de « insister pour voir ». ✗ <b>of / in seeing</b> : mauvaises prépositions."],
    ["The final report made no mention of ______ having overruled the technical committee.",
     ["the chairman", "the chairman's", "the chairman he", "that the chairman"], 1,
     "Devant un gérondif, le registre soutenu exige le POSSESSIF : <i>the chairman's having overruled</i>.",
     "🔑 Déclencheur : <b>of</b> + gérondif <b>having overruled</b> : ce qui est mentionné, c'est le FAIT, pas la personne.<br>✗ <b>the chairman</b> : toléré à l'oral, mais fautif à l'écrit formel — c'est exactement la précision visée. ✗ <b>the chairman he</b> : agrammatical. ✗ <b>that the chairman</b> : <i>of that</i> est impossible."],
    ["The revised contract provides ______ an annual review of the management fees.",
     ["to", "with", "for", "of"], 2,
     "<i>provide <b>for</b> something</i> = prévoir, stipuler (sens juridique).",
     "🔑 Déclencheur : le sujet est un contrat → sens « prévoit que ».<br>✗ <b>with</b> : <i>provide somebody <b>with</b> something</i> = fournir — il faudrait un bénéficiaire. ✗ <b>to</b> : jamais après <i>provide</i>. ✗ <b>of</b> : aucune construction."],
    ["By freezing salaries for four years, the group deprived itself ______ its best engineers.",
     ["from", "of", "with", "off"], 1,
     "<i>deprive somebody <b>of</b> something</i>.",
     "🔑 Déclencheur : <i>deprive</i>, comme <i>rob, strip, relieve</i>, gouverne <b>of</b>.<br>✗ <b>from</b> : calque de « priver de » via <i>prevent from</i>. ✗ <b>with</b> : sens inverse. ✗ <b>off</b> : orthographe/particule sans emploi ici."]
  ]
},

/* ---------------------------------------------------------- 7 */
{
  id: "sc-det", hard: true, always: true,
  title: "Déterminants & quantifieurs",
  tag: "🔪 Scalpel · précision",
  note: "Là où le français met un article, l'anglais met souvent <b>rien du tout</b> (<i>Life is hard</i>, <i>in hospital</i>) — et là où il compte, l'anglais distingue le comptable de l'indénombrable : <b>fewer/less</b>, <b>number/amount</b>, <b>many/much</b>. Deux contrastes fins à ne jamais rater : <b>little</b> (presque rien, négatif) vs <b>a little</b> (un peu, positif) ; <b>neither</b> (aucun des deux) vs <b>either</b> (l'un ou l'autre) vs <b>none</b> (aucun d'un ensemble &gt; 2). Enfin <b>so + adjectif</b> mais <b>such + (a) + nom</b>.",
  q: [
    ["There were far ______ objections to the merger than the board had feared.",
     ["less", "fewer", "lesser", "little"], 1,
     "<i>objections</i> est comptable pluriel → fewer.",
     "🔑 Déclencheur : un nom comptable au pluriel juste après le blanc.<br>✗ <b>less</b> : réservé aux indénombrables (<i>less noise, less time</i>) — répandu à l'oral, sanctionné à l'écrit. ✗ <b>lesser</b> : adjectif de valeur (<i>the lesser evil</i>). ✗ <b>little</b> : indénombrable, et sans comparatif."],
    ["The sheer ______ of paperwork involved makes the whole procedure unattractive.",
     ["number", "amount", "few", "several"], 1,
     "<i>paperwork</i> est INDÉNOMBRABLE → amount of.",
     "🔑 Déclencheur : <i>paperwork</i> (comme <i>work, advice, information, luggage, equipment</i>) ne se compte pas.<br>✗ <b>number</b> : exigerait un pluriel (<i>the number of <b>forms</b></i>). ✗ <b>few / several</b> : quantifieurs comptables, et ils ne suivent pas <i>the sheer</i>."],
    ["______ of the two proposals on the table is entirely satisfactory, unfortunately.",
     ["None", "Neither", "Either", "Any"], 1,
     "Deux éléments seulement, et sens négatif → Neither of the two.",
     "🔑 Déclencheur : <b>the two</b>. Au-delà de deux, ce serait <i>None of the proposals</i>.<br>✗ <b>None</b> : correct pour trois éléments ou plus. ✗ <b>Either</b> : « l'un ou l'autre », donc positif. ✗ <b>Any</b> : ne s'emploie pas en sujet affirmatif ici."],
    ["He has ______ patience for this kind of administrative delay — expect a scene.",
     ["few", "a few", "little", "a little"], 2,
     "<i>little</i> (sans article) = presque aucune : sens NÉGATIF, confirmé par la suite de la phrase.",
     "🔑 Déclencheur : <b>expect a scene</b> → le sens doit être négatif.<br>✗ <b>a little</b> : « un peu », positif — le contraire du sens voulu. ✗ <b>few / a few</b> : comptables, or <i>patience</i> est indénombrable."],
    ["The minister was rushed to ______ hospital shortly after the platform collapsed.",
     ["the", "a", "— (pas d'article)", "some"], 2,
     "En anglais britannique, l'institution prise dans sa fonction se passe d'article : <i>to hospital, in prison, at school, at university</i>.",
     "🔑 Déclencheur : on parle de la FONCTION (se faire soigner), pas d'un bâtiment identifié.<br>✗ <b>the</b> : correct en anglais américain (<i>to the hospital</i>) ou si l'on désigne un hôpital précis. ✗ <b>a</b> : introduirait un hôpital quelconque, ce qui affaiblit le sens. ✗ <b>some</b> : registre vague, inapproprié."],
    ["He gave us ______ that changed the whole direction of the investigation.",
     ["an information", "informations", "a piece of information", "some informations"], 2,
     "<i>information</i> est indénombrable : on compte avec <i>a piece of</i>.",
     "🔑 Déclencheur : <i>information</i> — comme <i>advice, news, furniture, evidence, research</i>.<br>✗ <b>an information / informations</b> : formes inexistantes en anglais, calque direct du français. ✗ <b>some informations</b> : même faute au pluriel."],
    ["______ of the two directors may sign the cheque; it makes no difference which.",
     ["Either", "Neither", "Both", "Any"], 0,
     "« l'un ou l'autre, indifféremment » → Either.",
     "🔑 Déclencheur : <b>it makes no difference which</b> = choix libre entre deux.<br>✗ <b>Neither</b> : sens négatif. ✗ <b>Both</b> : impliquerait les DEUX signatures, et demanderait <i>Both directors</i> (sans <i>of the two</i> ici). ✗ <b>Any</b> : au-delà de deux."],
    ["I've read ______ of his articles — considerably more than most of his colleagues have.",
     ["quite a few", "quite few", "a quite few", "quite the few"], 0,
     "Locution figée <i>quite a few</i> = un bon nombre (sens POSITIF).",
     "🔑 Déclencheur : <b>considerably more</b> confirme la quantité élevée.<br>✗ <b>quite few</b> : sans article, <i>few</i> devient négatif — contresens complet. ✗ <b>a quite few / quite the few</b> : ordre des mots impossible."],
    ["______ life in the nineteenth century was considerably harsher than most of us imagine.",
     ["The", "A", "— (pas d'article)", "Some"], 2,
     "Nom abstrait pris dans un sens général → AUCUN article.",
     "🔑 Déclencheur : sens générique (« la vie » en général), même si un complément suit.<br>✗ <b>The</b> : le réflexe français ; <i>the</i> particulariserait (<i>the life of a miner</i>). ✗ <b>A</b> : ferait de <i>life</i> un exemplaire dénombrable. ✗ <b>Some</b> : quantité indéterminée, hors sens."],
    ["It was ______ a convincing demonstration that even the sceptics changed their vote.",
     ["so", "such", "very", "too"], 1,
     "<b>such + a + adjectif + nom</b> ; <b>so</b> se placerait devant l'adjectif seul.",
     "🔑 Déclencheur : il y a un NOM (<i>demonstration</i>) après l'adjectif.<br>✗ <b>so</b> : correct dans <i>so convincing <b>a</b> demonstration</i> (ordre inversé, très littéraire) ou <i>The demonstration was so convincing that…</i> ✗ <b>very</b> : n'introduit pas de <i>that</i> de conséquence. ✗ <b>too</b> : appellerait <i>to</i> + infinitif."]
  ]
},

/* ---------------------------------------------------------- 8 */
{
  id: "sc-parallel", hard: true, always: true,
  title: "Parallélisme, comparaison, ellipse",
  tag: "🔪 Scalpel · symétrie",
  note: "Les corrélatifs exigent une SYMÉTRIE exacte : <i>not only <b>for</b> X but also <b>for</b> Y</i>, <i>both <b>for</b> X and <b>for</b> Y</i>, <i>either… or…</i>, <i>neither… nor…</i>. Les comparatifs ont leur grammaire propre : <i>as … as</i> (jamais <i>as … than</i>), <i>twice as many as</i>, <i>than any <b>other</b></i>, <i>the more…, the more…</i>, <i>prefer X <b>to</b> Y</i>, <i>different <b>from</b></i>. Enfin l'ellipse soutenue : <i>…, nor has her team</i>, <i>so did we</i>.",
  q: [
    ["The post calls not only for solid technical expertise ______ for a good deal of diplomacy.",
     ["but also", "but also needs", "and also", "but"], 0,
     "<i>not only <b>for</b> X but also <b>for</b> Y</i> : les deux branches doivent être identiques.",
     "🔑 Déclencheur : le <b>for</b> déjà présent après le blanc — la symétrie est prête, il ne manque que le corrélatif.<br>✗ <b>but also needs</b> : ajoute un verbe et casse le parallélisme. ✗ <b>and also</b> : <i>not only</i> appelle obligatoirement <i>but</i>. ✗ <b>but</b> seul : possible mais perd le corrélatif attendu à l'écrit soutenu."],
    ["She is responsible both for the internal audit ______ for the year-end consolidated accounts.",
     ["and", "as well as", "but also", "or"], 0,
     "Le corrélatif de <i>both</i> est <b>and</b>, sans exception.",
     "🔑 Déclencheur : <b>both</b> en amont.<br>✗ <b>as well as</b> : correct sans <i>both</i> (<i>responsible for X as well as Y</i>). ✗ <b>but also</b> : appartient à <i>not only</i>. ✗ <b>or</b> : introduirait une alternative."],
    ["The upgraded model is almost twice ______ the version it replaces.",
     ["as expensive as", "more expensive as", "as expensive than", "expensive as"], 0,
     "Multiplicatif + <i>as + adjectif + as</i> : <i>twice as expensive as</i>.",
     "🔑 Déclencheur : <b>twice</b> impose le moule <i>as … as</i>, jamais le comparatif en <i>-er/more</i>.<br>✗ <b>more expensive as</b> et <b>as expensive than</b> : deux hybrides fautifs, les plus fréquents à l'écrit. ✗ <b>expensive as</b> : premier <i>as</i> manquant."],
    ["Their after-sales service is better than ______ in the region, and they know it.",
     ["any", "any other", "the others", "anyone"], 1,
     "Quand le sujet fait partie de l'ensemble comparé, il faut <b>any other</b>.",
     "🔑 Déclencheur : leur service appartient lui aussi à la région — sans <i>other</i>, il serait meilleur que lui-même.<br>✗ <b>any</b> : contradiction logique. ✗ <b>the others</b> : possible mais change le sens (un groupe précis) et ne colle pas au singulier. ✗ <b>anyone</b> : renvoie à des personnes, pas à un service."],
    ["The more data the model is fed, ______ its predictions become.",
     ["the accurate", "the more accurate", "more accurate", "the most accurate"], 1,
     "Structure corrélative <i>the + comparatif…, the + comparatif…</i>",
     "🔑 Déclencheur : <b>The more data…</b> ouvre la corrélation, la seconde branche doit la refermer à l'identique.<br>✗ <b>the accurate</b> : pas de comparatif. ✗ <b>more accurate</b> : <i>the</i> manquant. ✗ <b>the most accurate</b> : superlatif, hors structure."],
    ["He earns nearly as much in a single month ______ she does in an entire year.",
     ["than", "as", "that", "like"], 1,
     "<i>as much … <b>as</b></i> : le second terme de l'égalité est <i>as</i>.",
     "🔑 Déclencheur : le <b>as much</b> en amont.<br>✗ <b>than</b> : réservé au comparatif de supériorité/infériorité (<i>more/less … than</i>). ✗ <b>that</b> : jamais dans une comparaison. ✗ <b>like</b> : préposition, ne peut pas introduire <i>she does</i>."],
    ["She has never missed a single deadline, ______ her team, as far as I know.",
     ["nor has", "nor does", "neither is", "so has"], 0,
     "Ellipse négative : reprise de l'auxiliaire du present perfect avec inversion → <i>nor has her team</i>.",
     "🔑 Déclencheur : la principale est au <b>present perfect</b> (<i>has never missed</i>) et négative.<br>✗ <b>nor does</b> : mauvais auxiliaire. ✗ <b>neither is</b> : auxiliaire <i>be</i>, absent de la principale. ✗ <b>so has</b> : <i>so</i> reprend une AFFIRMATIVE."],
    ["The report was thorough, carefully argued and ______, which is rarer than it should be.",
     ["written clearly", "clearly written", "with clarity", "it was clear"], 1,
     "Le troisième terme doit copier la forme des deux premiers : adverbe + participe (<i>carefully argued</i> → <i>clearly written</i>).",
     "🔑 Déclencheur : la série <b>thorough, carefully argued and …</b> fixe le moule.<br>✗ <b>written clearly</b> : ordre inversé, rupture de symétrie. ✗ <b>with clarity</b> : groupe prépositionnel, autre catégorie. ✗ <b>it was clear</b> : proposition entière, rupture nette."],
    ["Their approach is fundamentally different ______ ours on one crucial point.",
     ["than", "from", "of", "that"], 1,
     "<i>different <b>from</b></i> — la forme neutre et sûre à l'écrit.",
     "🔑 Déclencheur : <i>different</i>. (<i>different to</i> existe en anglais britannique ; <i>different than</i> est américain et contesté — <b>from</b> passe partout.)<br>✗ <b>than</b> : accepté par certains Américains, rejeté par les correcteurs. ✗ <b>of</b> : calque de « différent de ». ✗ <b>that</b> : agrammatical."],
    ["The committee was noticeably less interested in the conclusions ______ in the method.",
     ["as", "than", "that", "then"], 1,
     "<i>less … <b>than</b></i>, et les deux branches sont symétriques (<i>in</i> … <i>in</i>).",
     "🔑 Déclencheur : <b>less</b> = comparatif → <i>than</i>.<br>✗ <b>as</b> : réservé à l'égalité (<i>as interested as</i>). ✗ <b>that</b> : jamais comparatif. ✗ <b>then</b> : adverbe de temps, confusion orthographique classique."]
  ]
},

/* ---------------------------------------------------------- 9 */
{
  id: "sc-connect", hard: true, always: true,
  title: "Connecteurs : la nuance exacte",
  tag: "🔪 Scalpel · liaison",
  note: "Le vrai critère n'est pas le sens mais la <b>catégorie grammaticale</b> : <i>despite / in spite of / because of / during</i> sont des PRÉPOSITIONS (+ nom ou -ing) ; <i>although / because / while</i> sont des CONJONCTIONS (+ proposition conjuguée) ; <i>however / nevertheless / therefore</i> sont des ADVERBES (ponctuation forte). Nuances de haut niveau : <b>in case</b> (précaution, ≠ <i>if</i>), <b>unless</b> (= sauf si), <b>whereas</b> (contraste symétrique), <b>whereby</b> (par lequel), <b>lest</b> (+ base verbale, de peur que).",
  q: [
    ["______ the repeated delays at the port, the project was still delivered under budget.",
     ["Although", "Despite", "However", "Even though"], 1,
     "<i>Despite</i> est une PRÉPOSITION : suivie d'un groupe nominal (<i>the repeated delays</i>).",
     "🔑 Déclencheur : après le blanc il n'y a PAS de verbe conjugué, seulement un groupe nominal.<br>✗ <b>Although / Even though</b> : conjonctions, il faudrait <i>Although the port was delayed…</i> ✗ <b>However</b> : adverbe, il faudrait un point ou un point-virgule."],
    ["______ the team had worked three weekends in a row, the deadline still slipped.",
     ["Despite", "In spite of", "Although", "Despite of"], 2,
     "Ici suit une proposition conjuguée (<i>the team had worked</i>) → conjonction : Although.",
     "🔑 Déclencheur : sujet + verbe conjugué juste après le blanc — l'exact inverse de l'item précédent.<br>✗ <b>Despite / In spite of</b> : prépositions, elles demanderaient <i>Despite three weekends of work…</i> ✗ <b>Despite of</b> : forme qui n'existe pas (croisement de <i>despite</i> et <i>in spite of</i>)."],
    ["The two groups signed a framework agreement ______ each undertakes to share its test data.",
     ["whereby", "where", "in which way", "thereby"], 0,
     "<i>whereby</i> = « aux termes duquel / par lequel », relatif de registre juridique.",
     "🔑 Déclencheur : un document + un mécanisme qu'il institue.<br>✗ <b>where</b> : renvoie à un lieu. ✗ <b>in which way</b> : ordre interrogatif, pas relatif. ✗ <b>thereby</b> : adverbe (« ce faisant »), il faudrait <i>thereby undertaking</i> sans sujet."],
    ["He resigned two days before the enquiry opened ______ he be publicly dismissed.",
     ["lest", "unless", "in case", "so that"], 0,
     "<i>lest</i> = de peur que ; il commande la BASE verbale (<i>he be</i>), pas un présent.",
     "🔑 Déclencheur : le <b>be</b> nu après le sujet — seul <i>lest</i> (ou un subjonctif) l'autorise.<br>✗ <b>unless</b> : demanderait <i>unless he <b>is</b></i>. ✗ <b>in case</b> : idem, forme conjuguée. ✗ <b>so that</b> : exprimerait un but recherché, contresens."],
    ["Take the earlier train ______ there are engineering works on the line.",
     ["if", "in case", "unless", "whether"], 1,
     "<i>in case</i> = par précaution, AVANT de savoir. Le conseil vaut qu'il y ait des travaux ou non.",
     "🔑 Déclencheur : c'est une précaution, pas une condition.<br>✗ <b>if</b> : signifierait « prends le train plus tôt UNIQUEMENT s'il y a des travaux » — or on ne le saura qu'après. ✗ <b>unless</b> : inverse la logique. ✗ <b>whether</b> : introduit une alternative indirecte."],
    ["We will not release the funds ______ the client confirms the order in writing.",
     ["unless", "if", "in case", "without"], 0,
     "<i>unless</i> = sauf si ; il porte déjà la négation de la condition.",
     "🔑 Déclencheur : la principale est déjà négative (<i>will not release</i>).<br>✗ <b>if</b> : donnerait un contresens (nous ne débloquerons pas si le client confirme). ✗ <b>in case</b> : précaution, hors sens. ✗ <b>without</b> : préposition, il faudrait <i>without written confirmation</i>."],
    ["______ his colleagues, all of whom took the redundancy package, he chose to stay on.",
     ["Unlike", "Contrary to", "Whereas", "Despite"], 0,
     "<i>Unlike + personne/chose</i> = à la différence de.",
     "🔑 Déclencheur : le terme comparé est une PERSONNE.<br>✗ <b>Contrary to</b> : ne s'emploie qu'avec des idées, attentes, règles (<i>contrary to expectations</i>) — jamais avec des gens. ✗ <b>Whereas</b> : conjonction, il faudrait une proposition. ✗ <b>Despite</b> : concession, pas contraste."],
    ["The northern plant is almost fully automated, ______ the southern one still relies on manual assembly.",
     ["whereas", "however", "despite", "in spite of"], 0,
     "<i>whereas</i> : conjonction de contraste symétrique entre deux propositions.",
     "🔑 Déclencheur : une virgule + une proposition complète derrière.<br>✗ <b>however</b> : adverbe — il faudrait <i>; however,</i> avec un point-virgule. ✗ <b>despite / in spite of</b> : prépositions, et le rapport ici est un contraste, pas une concession."],
    ["The offer stands ______ payment is received within thirty days of invoicing.",
     ["provided that", "in case of", "despite", "unless"], 0,
     "<i>provided (that)</i> = à condition que — conjonction, suivie d'une proposition.",
     "🔑 Déclencheur : une condition explicite et restrictive.<br>✗ <b>in case of</b> : préposition (+ nom). ✗ <b>despite</b> : concession. ✗ <b>unless</b> : inverserait la condition."],
    ["The merger finally collapsed ______ a fundamental disagreement over the valuation.",
     ["because", "because of", "due", "since"], 1,
     "Suivi d'un groupe nominal → <i>because of</i>.",
     "🔑 Déclencheur : <b>a fundamental disagreement</b> est un nom, pas une proposition.<br>✗ <b>because / since</b> : conjonctions (+ sujet + verbe). ✗ <b>due</b> : incomplet — <i>due <b>to</b></i>, et l'usage soigné le réserve à une position attributive (<i>The collapse was due to…</i>)."]
  ]
},

/* ---------------------------------------------------------- 10 */
{
  id: "sc-boss", hard: true, always: true,
  title: "Le millimètre · épreuve finale",
  tag: "🔪 Scalpel · boss",
  note: "Dix phrases longues où le déclencheur est enfoui et où tout ce que tu as vu peut tomber : inversion après adverbe négatif, accord sur un noyau lointain, conditionnel inversé, subjonctif de nécessité, structures figées <i>No sooner… than</i> / <i>Such was… that</i> / <i>Not until… did</i>. Aucune n'est décidable au coup d'œil : lis la phrase entière AVANT de regarder les options.",
  q: [
    ["Rarely, if ever, ______ a claim of this magnitude been settled out of court so quickly.",
     ["has", "have", "did", "was"], 0,
     "Inversion après <i>Rarely</i>, et le sujet est <b>a claim</b>, singulier → has been settled.",
     "🔑 Double déclencheur : l'adverbe négatif en tête (inversion) ET le noyau <i>a claim</i>, isolé du verbe par <i>of this magnitude</i>.<br>✗ <b>have</b> : accord sur <i>magnitude</i>… qui n'est même pas pluriel. ✗ <b>did</b> : <i>did … been</i> impossible. ✗ <b>was</b> : <i>was … been settled</i> agrammatical."],
    ["The seized documents, several of ______ had been altered after the audit, are now with the prosecutor.",
     ["them", "which", "whom", "that"], 1,
     "Quantifieur + <i>of which</i> pour des choses, dans une incise.",
     "🔑 Déclencheur : les virgules encadrantes exigent un relatif ; <i>documents</i> = choses.<br>✗ <b>them</b> : casserait la subordination. ✗ <b>whom</b> : personnes uniquement. ✗ <b>that</b> : interdit après préposition et après virgule."],
    ["Were the committee ______ its recommendation at this stage, the entire funding round would collapse.",
     ["to withdraw", "withdrawing", "withdrawn", "withdraw"], 0,
     "Conditionnel formel inversé : <i>Were + sujet + <b>to</b> + base</i>.",
     "🔑 Déclencheur : le <b>Were</b> initial suivi d'un sujet — cette structure n'admet que <i>to + base</i>.<br>✗ <b>withdrawing</b> : donnerait un progressif passé (<i>the committee was withdrawing</i>), sans valeur conditionnelle. ✗ <b>withdrawn</b> : passif. ✗ <b>withdraw</b> : c'est le moule de <i>Should the committee withdraw</i>."],
    ["Little ______ the negotiators realise that the draft had already been leaked to the press.",
     ["did", "had", "do", "were"], 0,
     "<i>Little</i> en tête = adverbe négatif → inversion avec <b>do/did</b> : Little did they realise.",
     "🔑 Déclencheur : <b>Little</b> antéposé + le récit au passé (<i>had already been leaked</i>).<br>✗ <b>had</b> : exigerait un participe (<i>had realised</i>), pas la base <i>realise</i>. ✗ <b>do</b> : présent, en rupture avec le passé. ✗ <b>were</b> : aucun montage possible avec <i>realise</i>."],
    ["So thoroughly ______ the evidence destroyed that no prosecution was ever brought.",
     ["was", "were", "had", "did"], 0,
     "<i>evidence</i> est INDÉNOMBRABLE (singulier) → was destroyed, avec inversion après <i>So + adverbe</i>.",
     "🔑 Double déclencheur : l'emphase <b>So thoroughly</b> impose l'inversion, et <i>evidence</i> impose le singulier.<br>✗ <b>were</b> : le piège exact — <i>evidence</i> ressemble à un pluriel français (« les preuves »). ✗ <b>had</b> : il manquerait <i>been</i>. ✗ <b>did</b> : incompatible avec le participe passé."],
    ["The board would sooner ______ the Nantes office than lay off a third of the workforce.",
     ["close", "closing", "to close", "closed"], 0,
     "<i>would sooner / would rather + BASE verbale</i>, et <i>than</i> + base également (<i>lay off</i>).",
     "🔑 Déclencheur : le <b>lay off</b> (base nue) après <i>than</i> révèle la symétrie attendue.<br>✗ <b>closing</b> : <i>would sooner</i> n'accepte pas le gérondif. ✗ <b>to close</b> : pas de <i>to</i> après <i>would rather/sooner</i>. ✗ <b>closed</b> : casse le parallélisme avec <i>lay off</i>."],
    ["It is imperative that every applicant ______ a certified copy of the original diploma.",
     ["submits", "submit", "will submit", "submitted"], 1,
     "Subjonctif de nécessité après <i>It is imperative that</i> → BASE invariable : submit.",
     "🔑 Déclencheur : <b>imperative that</b> (comme <i>essential, vital, crucial, mandatory</i> + <i>that</i>).<br>✗ <b>submits</b> : le -s de la 3e personne est justement ce que le subjonctif supprime. ✗ <b>will submit</b> : jamais dans cette subordonnée. ✗ <b>submitted</b> : passé, hors valeur d'injonction."],
    ["No sooner had the preliminary results been published ______ the share price began to slide.",
     ["when", "that", "than", "then"], 2,
     "Structure figée : <i>No sooner … <b>than</b> …</i> (à ne pas confondre avec <i>Hardly … when …</i>).",
     "🔑 Déclencheur : <b>No sooner</b> contient un comparatif (<i>sooner</i>) — d'où <i>than</i>.<br>✗ <b>when</b> : c'est le partenaire de <i>Hardly / Scarcely / Barely</i>. ✗ <b>that</b> : jamais dans ce moule. ✗ <b>then</b> : adverbe, pas conjonction."],
    ["Only when the third independent audit was complete ______ the full extent of the shortfall.",
     ["the board understood", "did the board understand", "the board did understand", "understood the board"], 1,
     "<i>Only when + proposition</i> en tête → inversion dans la PRINCIPALE : did the board understand.",
     "🔑 Déclencheur : <b>Only when…</b> antéposé. L'inversion frappe la principale, pas la subordonnée.<br>✗ <b>the board understood</b> : ordre normal, l'inversion manque. ✗ <b>the board did understand</b> : <i>do</i> emphatique sans inversion. ✗ <b>understood the board</b> : inversion du verbe lexical, impossible en anglais moderne."],
    ["Such ______ the pressure on the supply chain that deliveries were suspended for a fortnight.",
     ["was", "were", "has", "did"], 0,
     "<i>Such + be + sujet + that…</i> ; le sujet est <b>the pressure</b>, singulier.",
     "🔑 Double déclencheur : la structure emphatique <i>Such was X that…</i> et le noyau <i>pressure</i> (indénombrable).<br>✗ <b>were</b> : accord sur <i>deliveries</i> ou sur <i>supply chain</i>, tous deux hors sujet. ✗ <b>has</b> : il manquerait un participe. ✗ <b>did</b> : la structure exige <i>be</i>."]
  ]
}

);

/* ============================================================
   Vivier d'examen « haute précision » (difficulté 3-4)
   Alimente le mode Défi et les examens blancs de niveau 3.
   Format : [énoncé, [options], indexBonne, explication, difficulté]
   ============================================================ */
window.EXAM_GRAMMAR.push(
  ["The consignment of spare parts ordered back in March ______ yet to clear customs.",
   ["is", "are", "have", "were"], 0,
   "Le noyau du sujet est « The consignment » (singulier) ; « of spare parts » n'est qu'un complément → is yet to clear.", 3],
  ["Only after the third written reminder ______ the outstanding invoice.",
   ["they paid", "did they pay", "they did pay", "paid they"], 1,
   "« Only after… » en tête entraîne l'inversion dans la principale : did they pay.", 3],
  ["The minutes of the meeting, which ______ circulated on Friday, contain a serious error.",
   ["was", "were", "is", "has been"], 1,
   "« Minutes » (compte rendu) est un pluriel → were circulated.", 3],
  ["Had the supplier disclosed the defect at the time, we ______ the order immediately.",
   ["would cancel", "would have cancelled", "cancelled", "will cancel"], 1,
   "Conditionnel type 3 inversé (Had + participe) → would have cancelled.", 3],
  ["Applicants ______ supporting documents are incomplete will not be considered.",
   ["who", "whose", "which", "whom"], 1,
   "Rapport de possession entre les candidats et leurs pièces → whose.", 3],
  ["It was not until the accounts were independently audited ______ the discrepancy came to light.",
   ["when", "that", "than", "which"], 1,
   "Phrase clivée : « It was not until X THAT Y ». Jamais « when » dans ce moule.", 4],
  ["Under no circumstances ______ the safety barrier be removed without written authorisation.",
   ["may", "may it", "it may", "is"], 0,
   "Locution négative en tête → inversion sujet-auxiliaire : may the safety barrier be removed.", 3],
  ["The board has yet to decide ______ to relocate the head office to Lyon.",
   ["if", "whether", "that", "what"], 1,
   "Devant un infinitif en « to », seul « whether » est possible — jamais « if ».", 3],
  ["Very few of the recommendations made in last year's report ______ implemented.",
   ["has been", "have been", "was", "is"], 1,
   "Le noyau est « Very few (of the recommendations) », pluriel → have been.", 3],
  ["The technician explained that the fault ______ by a power surge the previous night.",
   ["is caused", "was caused", "had been caused", "has been caused"], 2,
   "Discours indirect au passé + antériorité (« the previous night ») → had been caused.", 3],
  ["Not only did the supplier miss the deadline, but it also ______ the wrong model.",
   ["delivered", "deliver", "delivering", "had deliver"], 0,
   "L'inversion ne porte que sur la 1re proposition ; la seconde reprend l'ordre normal → it also delivered.", 3],
  ["The new premises are ______ larger than the ones we occupied in Lille.",
   ["far more", "far", "much more", "very"], 1,
   "Devant un comparatif en -er, on renforce avec far / much / considerably — jamais avec « more » ni « very ».", 3],
  ["The regulation applies to all vehicles ______ gross weight exceeds 3.5 tonnes.",
   ["which", "whose", "that", "of which"], 1,
   "« Whose » s'emploie aussi pour les choses : the vehicles whose gross weight…", 3],
  ["Should any discrepancy ______ during the reconciliation, notify the finance department at once.",
   ["arise", "arises", "arose", "arising"], 0,
   "Conditionnel inversé « Should + sujet + BASE verbale » → arise.", 3],
  ["The tender was rejected on the grounds ______ it breached the procurement rules.",
   ["of", "that", "which", "for"], 1,
   "Locution figée « on the grounds that + proposition ». « On the grounds of » demanderait un nom.", 3],
  ["The auditors would rather ______ the original invoices than rely on a summary.",
   ["see", "seeing", "to see", "saw"], 0,
   "« would rather + base verbale », en symétrie avec « than rely ».", 3],
  ["By the time the new system ______ fully deployed, the current contract will have expired.",
   ["is", "will be", "was", "has been"], 0,
   "Pas de « will » dans une subordonnée de temps : by the time + présent à valeur future.", 3],
  ["The candidate we appointed is by far ______ of the four we interviewed.",
   ["the more experienced", "the most experienced", "more experienced", "most experienced"], 1,
   "Quatre éléments → superlatif avec article : the most experienced.", 3],
  ["Neither of the two suppliers we approached ______ willing to revise their terms.",
   ["were", "was", "are", "have been"], 1,
   "« Neither of » est singulier → was.", 3],
  ["The findings, ______ were published last week, contradict the earlier study.",
   ["that", "which", "what", "who"], 1,
   "Relative non déterminative (entre virgules) : « that » y est interdit → which.", 3],
  ["He categorically denied ______ the confidential file to a competitor.",
   ["to forward", "forwarding", "having forward", "forward"], 1,
   "« deny » se construit avec le gérondif : denied forwarding (ou denied having forwarded).", 3],
  ["Such was the demand for the seminar ______ a second session had to be arranged.",
   ["that", "so", "as", "which"], 0,
   "Structure emphatique « Such was X that… » (conséquence).", 4],
  ["The regulator demands that every transaction ______ recorded within twenty-four hours.",
   ["is", "be", "will be", "being"], 1,
   "Subjonctif de nécessité après « demand that » → base verbale : be recorded.", 3],
  ["We had barely begun the presentation ______ the fire alarm went off.",
   ["than", "when", "that", "then"], 1,
   "« barely / hardly / scarcely … WHEN » ; « than » appartient à « no sooner ».", 3],
  ["The number of applications received this year ______ last year's total by a wide margin.",
   ["exceed", "exceeds", "have exceeded", "are exceeding"], 1,
   "« The number of » est singulier → exceeds.", 3],
  ["The witness claimed to ______ the defendant near the warehouse that evening.",
   ["have seen", "seeing", "seen", "having seen"], 0,
   "Infinitif parfait après « claim » pour un fait antérieur : claimed to have seen.", 3],
  ["Nowhere in the entire report ______ any reference to the missing funds.",
   ["there is", "is there", "it is", "there are"], 1,
   "Adverbe négatif en tête → inversion, y compris avec « there » existentiel : is there.", 4],
  ["The equipment ______ to be faulty was returned to the manufacturer at once.",
   ["found", "finding", "was found", "has found"], 0,
   "Relative réduite au passif : the equipment (which was) found to be faulty.", 3],
  ["Approval will be granted only if the revised plans ______ with the local building code.",
   ["will comply", "comply", "would comply", "complying"], 1,
   "Pas de « will » après « if » conditionnel → comply.", 3],
  ["It is high time the committee ______ a decision on the matter.",
   ["takes", "took", "will take", "has taken"], 1,
   "« It's high time » + prétérit à valeur de présent : took.", 3],
  ["The delegates were asked to remain seated until every vote ______ counted.",
   ["is", "has been", "had been", "will be"], 2,
   "Contexte passé rapporté (« were asked ») + antériorité → had been counted.", 3],
  ["______ of the three shortlisted firms has submitted a complete tender.",
   ["Neither", "None", "Either", "Both"], 1,
   "Au-delà de deux éléments, on emploie « None of » ; « neither » est réservé à un couple.", 3],
  ["The consultant recommended that the department ______ its entire procurement process.",
   ["reviews", "review", "reviewed", "will review"], 1,
   "Subjonctif après « recommend that » → base verbale : review.", 3],
  ["Operating profit rose by twelve per cent, ______ was well above the analysts' forecast.",
   ["what", "which", "that", "it"], 1,
   "« Which » reprend ici toute la proposition précédente.", 3],
  ["Hardly anyone in the department ______ aware of the change in policy.",
   ["were", "was", "have been", "are"], 1,
   "« Hardly anyone » est singulier → was.", 3],
  ["The contract may be terminated by ______ party on three months' notice.",
   ["either", "both", "neither", "any"], 0,
   "« Either party » = l'une ou l'autre des deux parties (formule contractuelle standard).", 3],
  ["The report criticises the bank for ______ to act on the early warnings.",
   ["fail", "failing", "have failed", "failed"], 1,
   "« for » est une préposition → gérondif : for failing to act.", 3],
  ["So great was the demand that production ______ doubled within a month.",
   ["has to be", "had to be", "must be", "has been to be"], 1,
   "Le récit est au passé (« was ») → had to be doubled.", 3],
  ["The auditors requested access to every file ______ the transaction had been recorded.",
   ["in which", "which", "that", "where in"], 0,
   "« record something IN a file » → la préposition remonte : the file in which…", 4],
  ["Were it not for the guarantee given by the parent company, the bank ______ the loan outright.",
   ["would refuse", "would have refused", "refused", "will refuse"], 0,
   "« Were it not for » = irréel du PRÉSENT → would refuse (comparer : « Had it not been for » → would have refused).", 4],
  ["Each of the subsidiaries files ______ own accounts entirely separately.",
   ["their", "its", "it's", "theirs"], 1,
   "« Each of » est singulier → possessif singulier : its own accounts.", 3],
  ["No decision ______ until every member of the panel has been consulted.",
   ["is taken", "will be taken", "would be taken", "has been taken"], 1,
   "La principale se projette dans l'avenir → will be taken ; le futur reste interdit dans la subordonnée de temps.", 3],
  ["The firm has been operating in the region ______ 1998, longer than any of its rivals.",
   ["for", "since", "from", "during"], 1,
   "Point de départ daté → since (« for » demanderait une durée : for twenty-five years).", 3],
  ["The assembly instructions were so poorly drafted ______ nobody could follow them.",
   ["as", "that", "so", "than"], 1,
   "« so + adjectif + THAT » exprime la conséquence.", 3],
  ["It was ______ short notice that half the delegates were unable to attend.",
   ["so", "such", "such a", "very"], 1,
   "« notice » est indénombrable → such short notice, sans article.", 3],
  ["The defect, ______ solution has so far eluded the engineers, dates back to the original design.",
   ["which", "whose", "that", "of whom"], 1,
   "Possession appliquée à une chose → whose solution.", 4],
  ["Not until the following morning ______ that the server had been compromised.",
   ["we realised", "did we realise", "we did realise", "realised we"], 1,
   "« Not until… » en tête → inversion dans la principale : did we realise.", 4],
  ["The company insists on all visitors ______ a security badge at all times.",
   ["to wear", "wearing", "wear", "worn"], 1,
   "« insist ON » est une préposition → gérondif : on all visitors wearing.", 3]
);
