/* ============================================================
   990 — Module « Traduire » : version FR → EN
   Chaque phrase : traduction modèle idiomatique + variantes acceptées
   + point de grammaire/vocabulaire (subjonctif, inversion, etc.)
   t = { fr, en, alt:[...], cat, point, note, level }
   ============================================================ */
window.TRANSLATIONS = [

  /* ---- Subjonctif ---- */
  { fr:"Il est essentiel que chaque étudiant soit présent à l'examen.", en:"It is essential that every student be present at the exam.", alt:["It's essential that each student is present at the exam."], cat:"Subjonctif", point:"Subjonctif après « essential that »", note:"Après essential / vital / crucial / imperative that, l'anglais soutenu emploie la BASE verbale invariable : « that he BE », « that she ARRIVE ». La variante à l'indicatif (is) passe à l'oral, mais le subjonctif fait plus C2.", level:"C1" },
  { fr:"Je suggère qu'il parte avant la tombée de la nuit.", en:"I suggest (that) he leave before nightfall.", alt:["I suggest he should leave before nightfall."], cat:"Subjonctif", point:"suggest / recommend + subjonctif", note:"suggest, recommend, insist, demand, propose + that + BASE (« he leave », « they be »). « nightfall » = la tombée de la nuit, plus soutenu que « before it gets dark ».", level:"C1" },
  { fr:"Le règlement exige que tous les documents soient signés à la main.", en:"The regulations require that all documents be signed by hand.", alt:["The regulations require all documents to be signed by hand."], cat:"Subjonctif", point:"Subjonctif passif / require that", note:"Deux tournures : « require that ... BE signed » (subjonctif passif) OU « require + COD + to be signed ». « by hand » = à la main.", level:"C1" },
  { fr:"Il vaudrait mieux que tu lui dises la vérité maintenant.", en:"You had better tell him the truth now.", alt:["It would be better if you told him the truth now.","You'd better tell him the truth now."], cat:"Subjonctif", point:"« had better » + base (conseil pressant)", note:"« had better + base » = il vaudrait mieux que (conseil fort). Autre tournure : « It would be better if + prétérit » (told). Jamais « you would better ».", level:"B2" },
  { fr:"J'insiste pour qu'elle soit traitée avec respect.", en:"I insist that she be treated with respect.", alt:["I insist on her being treated with respect."], cat:"Subjonctif", point:"insist that + subj. / insist on + -ing", note:"Deux constructions : « insist that she BE treated » (subjonctif) ou « insist ON + -ing » (her being treated). Jamais « insist to ».", level:"C1" },
  { fr:"Il est grand temps que nous prenions cette décision.", en:"It's high time we made this decision.", alt:["It's about time we made this decision."], cat:"Subjonctif", point:"« It's high time » + prétérit", note:"Après « it's high time / it's about time », on emploie le PRÉTÉRIT à valeur de présent urgent : « we MADE », pas « we make ».", level:"C1" },

  /* ---- Souhait / Regret ---- */
  { fr:"J'aurais aimé le savoir plus tôt.", en:"I wish I had known earlier.", alt:["I wish I'd known sooner."], cat:"Souhait/Regret", point:"wish + past perfect (regret passé)", note:"Regret sur le passé : « wish + past perfect » (had known). « I wish I knew » = regret présent. Ne pas calquer « I would have liked ».", level:"B2" },
  { fr:"Si seulement il m'avait écouté !", en:"If only he had listened to me!", alt:["If only he'd listened to me."], cat:"Souhait/Regret", point:"« If only » + past perfect", note:"« If only + past perfect » = regret intense d'un passé irréversible. « listen TO somebody » (préposition obligatoire).", level:"B2" },
  { fr:"Je regrette de ne pas avoir accepté cette offre.", en:"I wish I had accepted that offer.", alt:["I regret not accepting that offer.","I regret not having accepted that offer."], cat:"Souhait/Regret", point:"regret + -ing / wish + past perfect", note:"« regret (not) + -ing » pour un regret passé, ou la tournure idiomatique « I wish I had accepted ».", level:"C1" },
  { fr:"Je préférerais que tu ne fumes pas ici.", en:"I'd rather you didn't smoke here.", alt:["I would prefer it if you didn't smoke here."], cat:"Souhait/Regret", point:"« would rather » + prétérit (autre sujet)", note:"Souhait portant sur QUELQU'UN D'AUTRE : « would rather + sujet + PRÉTÉRIT » (you didn't). Même sujet : « I'd rather not smoke » (base).", level:"C1" },
  { fr:"Pourvu qu'il ne soit pas trop tard.", en:"Let's hope it's not too late.", alt:["I just hope it's not too late.","Hopefully it's not too late."], cat:"Souhait/Regret", point:"« pourvu que » → tournures d'espoir", note:"« Pourvu que » ne se rend pas par un subjonctif ; l'anglais idiomatique préfère « Let's hope... » / « I just hope... » / « Hopefully... ».", level:"B2" },
  { fr:"Il est temps que tu prennes tes responsabilités.", en:"It's time you took responsibility.", alt:["It's time for you to take responsibility."], cat:"Souhait/Regret", point:"« It's time » + prétérit / for + to", note:"« It's time + sujet + PRÉTÉRIT » (you took) OU « It's time for you TO take ». « to take responsibility » = prendre ses responsabilités.", level:"B2" },

  /* ---- Conditionnels ---- */
  { fr:"Si j'avais su, je ne serais jamais venu.", en:"If I had known, I would never have come.", alt:["Had I known, I would never have come."], cat:"Conditionnels", point:"3e conditionnel (irréel du passé)", note:"If + past perfect, would have + participe. Version soutenue par inversion sans « if » : « Had I known, ... ».", level:"C1" },
  { fr:"Si tu avais économisé, tu serais riche aujourd'hui.", en:"If you had saved, you would be rich today.", alt:["Had you saved, you'd be rich today."], cat:"Conditionnels", point:"Conditionnel MIXTE (passé → présent)", note:"Condition passée (had saved) mais conséquence présente (would be, PAS would have been) à cause de « today ». C'est le conditionnel mixte, très C2.", level:"C2" },
  { fr:"À ta place, je démissionnerais sur-le-champ.", en:"If I were you, I would resign on the spot.", alt:["In your position, I'd resign at once.","Were I you, I would resign immediately."], cat:"Conditionnels", point:"2e conditionnel + « were »", note:"« If I were you » (jamais « was » en anglais soigné). « on the spot / at once » = sur-le-champ. Inversion formelle : « Were I you, ... ».", level:"B2" },
  { fr:"Au cas où il pleuvrait, prends un parapluie.", en:"In case it rains, take an umbrella.", alt:["Take an umbrella in case it rains."], cat:"Conditionnels", point:"« in case » + présent (≠ if)", note:"« in case » exprime la précaution et se construit au PRÉSENT (it rains), pas au conditionnel. Différent de « if it rains » (condition).", level:"B2" },
  { fr:"Sans ton aide, j'aurais tout abandonné.", en:"If it weren't for your help, I would have given up.", alt:["Were it not for your help, I would have given up.","But for your help, I would have given up."], cat:"Conditionnels", point:"« if it weren't for » / « but for »", note:"« If it weren't for X » = sans X. Registre soutenu : « Were it not for... » ou « But for your help... ». « to give up » = abandonner.", level:"C2" },
  { fr:"Même si on me le payait, je ne le ferais pas.", en:"I wouldn't do it even if I were paid to.", alt:["Even if you paid me, I wouldn't do it."], cat:"Conditionnels", point:"« even if » + 2e conditionnel", note:"« even if » + prétérit / would : hypothèse concessive. Le « to » final (« paid to ») reprend « to do it » par ellipse idiomatique.", level:"C1" },

  /* ---- Inversion ---- */
  { fr:"Ce n'est qu'après coup que j'ai compris mon erreur.", en:"Only afterwards did I realize my mistake.", alt:["It was only afterwards that I realized my mistake."], cat:"Inversion", point:"« Only... » en tête → inversion", note:"Un « Only + ... » restrictif en tête déclenche l'inversion sujet-auxiliaire : « did I realize ». « afterwards » = après coup.", level:"C1" },
  { fr:"Jamais je n'aurais imaginé une telle réussite.", en:"Never would I have imagined such a success.", alt:["Never had I imagined such a success."], cat:"Inversion", point:"« Never » en tête → inversion", note:"Adverbe négatif en tête → inversion : « Never would I have... ». « such a success » (such + a + nom). Effet très emphatique.", level:"C1" },
  { fr:"À peine étais-je arrivé qu'il se mit à pleuvoir.", en:"No sooner had I arrived than it started to rain.", alt:["Hardly had I arrived when it started to rain."], cat:"Inversion", point:"« No sooner... than » / « Hardly... when »", note:"Structures figées à inversion : « No sooner had ... THAN ... » et « Hardly/Scarcely had ... WHEN ... ». Attention à la conjonction.", level:"C2" },
  { fr:"Non seulement il a menti, mais il a aussi triché.", en:"Not only did he lie, but he also cheated.", alt:["Not only did he lie, he cheated as well."], cat:"Inversion", point:"« Not only » en tête → inversion", note:"« Not only + inversion (did he lie), but ... also ». Le second membre n'a pas besoin d'inversion. Sens d'accumulation.", level:"C1" },
  { fr:"En aucun cas vous ne devez partager ce mot de passe.", en:"Under no circumstances should you share this password.", alt:["On no account should you share this password."], cat:"Inversion", point:"Locution négative en tête → inversion", note:"« Under no circumstances / On no account » (= en aucun cas) impose l'inversion : « should you share ». Registre des consignes.", level:"C1" },
  { fr:"Rarement ai-je vu un travail aussi soigné.", en:"Rarely have I seen such careful work.", alt:["Seldom have I seen work so carefully done."], cat:"Inversion", point:"« Rarely / Seldom » en tête → inversion", note:"Adverbes restrictifs (rarely, seldom, little) en tête → inversion : « have I seen ». « such careful work » (such + nom indénombrable, sans a).", level:"C1" },

  /* ---- Discours indirect ---- */
  { fr:"Il m'a dit qu'il viendrait le lendemain.", en:"He told me (that) he would come the next day.", alt:["He told me he'd come the following day."], cat:"Discours indirect", point:"Concordance des temps + « told »", note:"Discours indirect : présent→prétérit, will→would. « tomorrow » → « the next/following day ». « tell SOMEBODY » (told me) vs « say » (sans COD).", level:"B2" },
  { fr:"Elle m'a demandé si j'avais terminé.", en:"She asked me whether I had finished.", alt:["She asked me if I had finished."], cat:"Discours indirect", point:"Question indirecte (if/whether)", note:"Question indirecte : PAS d'inversion, ordre sujet-verbe normal. « if/whether » pour une question fermée. « have finished » → « had finished ».", level:"B2" },
  { fr:"Ils ont affirmé qu'ils avaient déjà réglé la facture.", en:"They claimed (that) they had already settled the invoice.", alt:["They insisted they had already paid the bill."], cat:"Discours indirect", point:"« claim » + past perfect", note:"« claim » = affirmer (avec une nuance de doute). Antériorité → past perfect (had settled). « to settle an invoice » = régler une facture.", level:"C1" },
  { fr:"Le professeur nous a conseillé de réviser régulièrement.", en:"The teacher advised us to revise regularly.", alt:["The teacher advised us to review regularly."], cat:"Discours indirect", point:"« advise somebody to » + infinitif", note:"Ordre/conseil rapporté → « advise / tell / ask + COD + TO + base » (advised us to revise). Pas de « that » ici.", level:"B2" },
  { fr:"Elle m'a demandé de ne pas faire de bruit.", en:"She asked me not to make any noise.", alt:["She told me not to make noise."], cat:"Discours indirect", point:"Ordre négatif rapporté : « not to »", note:"Ordre négatif rapporté : « ask / tell + COD + NOT TO + base » (not to make). « to make noise » (pas « to do noise »).", level:"B2" },
  { fr:"Il a expliqué qu'il n'avait pas eu le choix.", en:"He explained that he had had no choice.", alt:["He explained he'd had no choice."], cat:"Discours indirect", point:"« had had » (past perfect de have)", note:"« had had » : le 1er « had » est l'auxiliaire du past perfect, le 2nd le verbe « have ». « to have no choice » = ne pas avoir le choix.", level:"C1" },

  /* ---- Modaux ---- */
  { fr:"Il a dû oublier notre rendez-vous.", en:"He must have forgotten our appointment.", alt:["He must have forgotten about our meeting."], cat:"Modaux", point:"« must have » + participe (déduction)", note:"Déduction quasi-certaine sur le passé : « must have + participe ». À ne pas confondre avec l'obligation passée « he had to ».", level:"B2" },
  { fr:"Elle n'a pas pu dire une chose pareille.", en:"She can't have said such a thing.", alt:["She couldn't have said such a thing."], cat:"Modaux", point:"« can't have » + participe (impossibilité)", note:"Négation d'une déduction passée : « can't / couldn't have + participe » (il est impossible qu'elle ait dit). « such a thing » = une chose pareille.", level:"C1" },
  { fr:"Tu aurais dû me prévenir plus tôt.", en:"You should have warned me earlier.", alt:["You ought to have told me earlier."], cat:"Modaux", point:"« should have » + participe (reproche)", note:"Reproche / conseil rétrospectif : « should have / ought to have + participe » (tu aurais dû). « to warn » = prévenir.", level:"B2" },
  { fr:"Ce n'était pas la peine de te presser.", en:"You needn't have hurried.", alt:["You didn't need to hurry."], cat:"Modaux", point:"« needn't have » vs « didn't need to »", note:"« needn't have + participe » = tu t'es pressé, mais c'était inutile (action FAITE). « didn't need to » = ce n'était pas nécessaire (pas forcément fait). Nuance C2 !", level:"C2" },
  { fr:"Il se pourrait bien qu'elle ait raison.", en:"She may well be right.", alt:["She might well be right."], cat:"Modaux", point:"« may well » (forte possibilité)", note:"« may / might well » = il se pourrait bien / c'est fort possible. Renforce la probabilité (pas la permission).", level:"C1" },
  { fr:"Tu n'étais pas obligé de payer, mais merci.", en:"You didn't have to pay, but thank you.", alt:["You didn't need to pay, but thanks."], cat:"Modaux", point:"« didn't have to » (absence d'obligation)", note:"« didn't have to » = ne pas être obligé de (absence d'obligation), à ne pas confondre avec « mustn't » (interdiction).", level:"B2" },

  /* ---- Gérondif / Infinitif ---- */
  { fr:"J'ai hâte de te revoir.", en:"I look forward to seeing you again.", alt:["I'm looking forward to seeing you again."], cat:"Gérondif/Infinitif", point:"« look forward TO » + -ing", note:"Ici « to » est une PRÉPOSITION, donc suivie de -ING (seeing), jamais de la base. Erreur classique : « look forward to see ».", level:"B2" },
  { fr:"Ça vaut la peine d'essayer, non ?", en:"It's worth trying, isn't it?", alt:["It's worth a try, isn't it?"], cat:"Gérondif/Infinitif", point:"« worth » + -ing", note:"« (be) worth + -ing » = valoir la peine de. « It's worth trying », pas « worth to try ». Tag « isn't it? » = non ?", level:"B2" },
  { fr:"J'ai fini par accepter leur proposition.", en:"I ended up accepting their offer.", alt:["I eventually accepted their proposal."], cat:"Gérondif/Infinitif", point:"« end up » + -ing", note:"« end up + -ing » = finir par (résultat non prévu). « eventually » = finalement (faux-ami : ≠ éventuellement).", level:"C1" },
  { fr:"Il n'arrête pas de se plaindre.", en:"He keeps (on) complaining.", alt:["He won't stop complaining."], cat:"Gérondif/Infinitif", point:"« keep (on) » + -ing", note:"« keep (on) + -ing » = n'arrête pas de / continuer à. « to complain » = se plaindre. « won't stop » exprime aussi l'insistance.", level:"B2" },
  { fr:"J'ai du mal à me concentrer aujourd'hui.", en:"I'm having trouble concentrating today.", alt:["I find it hard to concentrate today."], cat:"Gérondif/Infinitif", point:"« have trouble » + -ing", note:"« have trouble / difficulty + -ing » = avoir du mal à. Autre tournure : « find it hard TO + base » (to concentrate).", level:"B2" },
  { fr:"Elle a réussi à les convaincre en dix minutes.", en:"She managed to convince them in ten minutes.", alt:["She succeeded in convincing them in ten minutes."], cat:"Gérondif/Infinitif", point:"« manage TO » vs « succeed IN »", note:"« manage to + base » (managed to convince) OU « succeed in + -ing » (succeeded in convincing). Deux façons de dire « réussir à ».", level:"C1" },

  /* ---- Passif / Impersonnel ---- */
  { fr:"On dit qu'il est le meilleur dans son domaine.", en:"He is said to be the best in his field.", alt:["It is said that he is the best in his field."], cat:"Passif", point:"« be said to » (passif impersonnel)", note:"« On dit que... » → « X is said to + base » ou « It is said that... ». Tournure élégante pour le ouï-dire. « in his field » = dans son domaine.", level:"C1" },
  { fr:"On m'a proposé un poste à l'étranger.", en:"I was offered a job abroad.", alt:["They offered me a job abroad."], cat:"Passif", point:"Passif avec le COI comme sujet", note:"Avec offer / give / tell / send, le complément indirect peut devenir sujet du passif : « I was offered... ». « abroad » = à l'étranger (sans préposition).", level:"B2" },
  { fr:"Le rapport est en train d'être révisé.", en:"The report is being revised.", alt:["The report is currently being revised."], cat:"Passif", point:"Passif au présent continu", note:"Passif progressif : « is/are + being + participe » (is being revised) = est en train d'être. Ne pas oublier « being ».", level:"B2" },
  { fr:"On aurait dû nous prévenir à l'avance.", en:"We should have been warned in advance.", alt:["They should have warned us in advance."], cat:"Passif", point:"Passif + modal parfait", note:"Passif + « should have » : « should have been + participe » (been warned). « in advance » = à l'avance.", level:"C1" },
  { fr:"Il s'est fait voler son téléphone dans le métro.", en:"He had his phone stolen on the subway.", alt:["His phone got stolen on the subway."], cat:"Passif", point:"« have something done » (causatif subi)", note:"« have + COD + participe » exprime une chose subie : « had his phone stolen » = s'est fait voler. Variante familière : « got + participe ».", level:"C2" },
  { fr:"On construit un nouveau pont en ce moment.", en:"A new bridge is being built.", alt:["They are building a new bridge."], cat:"Passif", point:"Passif présent continu (agent vague)", note:"Quand l'agent est vague (« on »), le passif est plus naturel : « A new bridge is being built » (focalise sur l'objet).", level:"B2" },

  /* ---- Concession ---- */
  { fr:"Malgré tous ses efforts, il a échoué.", en:"Despite all his efforts, he failed.", alt:["In spite of all his efforts, he failed."], cat:"Concession", point:"« despite / in spite of » + NOM", note:"« despite / in spite of » sont suivis d'un NOM ou de -ing (jamais d'une proposition). « despite his efforts », pas « despite he tried ».", level:"B2" },
  { fr:"Bien qu'il soit très riche, il vit simplement.", en:"Although he is very rich, he lives simply.", alt:["Rich as he is, he lives simply.","Wealthy though he is, he lives simply."], cat:"Concession", point:"« although » / « as-though » inversé", note:"« although + proposition ». Tournure soutenue et élégante : « Rich as he is, ... » / « Rich though he is, ... » (adjectif en tête).", level:"C1" },
  { fr:"Quoi qu'il arrive, je te soutiendrai.", en:"Whatever happens, I'll support you.", alt:["No matter what happens, I'll stand by you."], cat:"Concession", point:"« whatever / no matter what »", note:"« Whatever + verbe » = quoi que. Synonyme : « No matter what ». « to stand by somebody » = soutenir qqn (idiomatique).", level:"B2" },
  { fr:"Si difficile que soit la tâche, nous y arriverons.", en:"However difficult the task may be, we'll manage.", alt:["Hard as the task may be, we'll succeed."], cat:"Concession", point:"« however + adjectif »", note:"« However + adj/adv (+ may be) » = si... que. « we'll manage » = on y arrivera. Alternative : « Hard as it may be ».", level:"C2" },
  { fr:"Tout riche qu'il est, il n'est pas heureux.", en:"Rich as he may be, he is not happy.", alt:["For all his wealth, he is not happy."], cat:"Concession", point:"« as ... may be » / « for all »", note:"Concession soutenue : « Adjectif + as + sujet + may be ». Autre tournure : « For all his wealth » (= malgré toute sa richesse).", level:"C2" },
  { fr:"Il est venu, alors même qu'il était malade.", en:"He came, even though he was ill.", alt:["He came, despite being ill."], cat:"Concession", point:"« even though » vs « despite »", note:"« even though + proposition » (he was ill) ≠ « despite + nom/-ing » (despite being ill). Choisir selon ce qui suit.", level:"B2" },

  /* ---- Cause / But ---- */
  { fr:"Il a tellement plu que le match a été annulé.", en:"It rained so much that the match was called off.", alt:["It rained so heavily that the game was cancelled."], cat:"Cause/But", point:"« so much... that » (conséquence)", note:"« so + (adverbe) + that » exprime la conséquence. « to call off » = annuler (phrasal), synonyme « cancel ».", level:"B2" },
  { fr:"Elle travaille dur afin de décrocher une bourse.", en:"She works hard in order to land a scholarship.", alt:["She works hard so as to get a scholarship."], cat:"Cause/But", point:"« in order to / so as to » (but)", note:"But : « in order to » / « so as to » + base. « to land » (fam.) = décrocher. « scholarship » = bourse d'études.", level:"C1" },
  { fr:"Faute de temps, nous n'avons pas pu tout finir.", en:"For lack of time, we couldn't finish everything.", alt:["Due to a lack of time, we didn't manage to finish."], cat:"Cause/But", point:"« for lack of » (cause)", note:"« For lack of + nom » = faute de. Alternative : « Due to a lack of... ». « to manage to » = parvenir à.", level:"C1" },
  { fr:"Il a parlé doucement pour ne pas la réveiller.", en:"He spoke softly so as not to wake her.", alt:["He spoke quietly in order not to wake her."], cat:"Cause/But", point:"But négatif : « so as not to »", note:"But négatif : « so as NOT to » / « in order NOT to » + base. « to wake somebody » = réveiller qqn.", level:"C1" },
  { fr:"Grâce à ton aide, tout s'est bien passé.", en:"Thanks to your help, everything went smoothly.", alt:["Thanks to your help, it all went well."], cat:"Cause/But", point:"« thanks to » (cause positive)", note:"« Thanks to + nom » = grâce à (résultat positif), à distinguer de « because of » (neutre). « to go smoothly » = bien se passer.", level:"B2" },
  { fr:"Vu qu'il pleuvait, nous sommes restés à l'intérieur.", en:"Since it was raining, we stayed indoors.", alt:["As it was raining, we stayed inside.","Given that it was raining, we stayed in."], cat:"Cause/But", point:"« since / as / given that » (cause)", note:"« Since / As / Given that + proposition » introduisent une cause connue. « indoors » = à l'intérieur (adverbe, sans préposition).", level:"B2" },

  /* ---- Mise en relief ---- */
  { fr:"C'est lui qui a tout organisé.", en:"He's the one who organized everything.", alt:["It was he who organized everything.","He's the one who set it all up."], cat:"Mise en relief", point:"Clivée « the one who »", note:"« C'est ... qui » → « He's the one who... » ou la structure clivée « It was he who... » (soutenu). Insiste sur le sujet.", level:"B2" },
  { fr:"Ce dont j'ai besoin, c'est d'un peu de repos.", en:"What I need is a little rest.", alt:["What I need is some rest."], cat:"Mise en relief", point:"Pseudo-clivée « What ... is »", note:"« Ce dont/ce que ... c'est » → « What I need is... ». Le verbe reste au singulier « is ». « rest » = le repos (indénombrable).", level:"B2" },
  { fr:"C'est la raison pour laquelle j'ai démissionné.", en:"That's the reason (why) I resigned.", alt:["That's why I resigned."], cat:"Mise en relief", point:"« the reason why » / « that's why »", note:"« la raison pour laquelle » = « the reason (why) » ou simplement « that's why ». « to resign » = démissionner.", level:"B2" },
  { fr:"Ce n'est qu'en travaillant qu'on progresse.", en:"It's only by working that you improve.", alt:["Only by working do you improve."], cat:"Mise en relief", point:"Clivée « It's only by -ing that »", note:"« Ce n'est qu'en + -ant » → « It's only by + -ing that... ». Version à inversion : « Only by working DO you improve ».", level:"C1" },
  { fr:"C'est justement ce que je voulais dire.", en:"That's exactly what I meant.", alt:["That's precisely what I meant."], cat:"Mise en relief", point:"« what » relatif + emphase", note:"« ce que je voulais dire » = « what I meant » (what = ce que, relatif sans antécédent). « exactly / precisely » = justement.", level:"B2" },
  { fr:"C'est en 2019 qu'ils se sont rencontrés.", en:"It was in 2019 that they met.", alt:["They met in 2019."], cat:"Mise en relief", point:"Clivée sur le complément de temps", note:"Structure clivée « It was + complément + that... » pour mettre en relief la date. Insiste sur « in 2019 ».", level:"B2" },

  /* ---- Idiomatique ---- */
  { fr:"Ça ne me dit rien qui vaille.", en:"I have a bad feeling about this.", alt:["This doesn't feel right to me."], cat:"Idiomatique", point:"Pressentiment (non littéral)", note:"Ne se traduit pas mot à mot. Idiomatique : « I have a bad feeling about this » = j'ai un mauvais pressentiment.", level:"C1" },
  { fr:"Je n'y suis pour rien.", en:"It's not my fault.", alt:["I had nothing to do with it."], cat:"Idiomatique", point:"Responsabilité (non littéral)", note:"« Je n'y suis pour rien » = « It's not my fault » ou, plus idiomatique, « I had nothing to do with it ».", level:"B2" },
  { fr:"On verra bien, advienne que pourra.", en:"We'll see; come what may.", alt:["We'll see what happens, come what may."], cat:"Idiomatique", point:"« come what may » (subjonctif figé)", note:"« Advienne que pourra » = « come what may » (quoi qu'il advienne) — subjonctif figé, très idiomatique et soutenu.", level:"C2" },
  { fr:"Revenons à nos moutons.", en:"Let's get back to the point.", alt:["Let's get back on track.","Anyway, where were we?"], cat:"Idiomatique", point:"Recentrer la discussion", note:"« Revenons à nos moutons » → « Let's get back to the point / on track ». Ne jamais traduire par « sheep » !", level:"C1" },
  { fr:"Ça tombe à pic !", en:"That's perfect timing!", alt:["That couldn't have come at a better time!"], cat:"Idiomatique", point:"Bonne coïncidence", note:"« Tomber à pic » = « perfect timing » / « couldn't have come at a better time ». Exprime la coïncidence heureuse.", level:"B2" },
  { fr:"Autant pour moi, je me suis trompé.", en:"My mistake, I got it wrong.", alt:["My bad, I was wrong."], cat:"Idiomatique", point:"Admettre une erreur", note:"« Autant pour moi » = « My mistake » / « My bad » (fam.). « to get it wrong » = se tromper.", level:"B2" }

];
