/* ============================================================
   990 — Vocabulaire bilingue, 2e vague (quotidien élargi + C1-C2)
   Format : [recto EN, verso FR, exemple EN, thème]
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  /* --- Animaux (mer, ferme, insectes) --- */
  ["whale", "la baleine", "A whale surfaced near the boat.", "Animaux"],
  ["dolphin", "le dauphin", "Dolphins followed the ferry.", "Animaux"],
  ["shark", "le requin", "A shark circled the reef.", "Animaux"],
  ["octopus", "la pieuvre / le poulpe", "The octopus changed colour.", "Animaux"],
  ["jellyfish", "la méduse", "A jellyfish stung his leg.", "Animaux"],
  ["crab", "le crabe", "A crab scuttled across the sand.", "Animaux"],
  ["lobster", "le homard", "We had lobster for dinner.", "Animaux"],
  ["seal", "le phoque", "Seals basked on the rocks.", "Animaux"],
  ["penguin", "le manchot / le pingouin", "Penguins huddled against the cold.", "Animaux"],
  ["eagle", "l'aigle", "An eagle soared above the peak.", "Animaux"],
  ["sparrow", "le moineau", "A sparrow hopped on the table.", "Animaux"],
  ["crow", "le corbeau", "A crow cawed from the fence.", "Animaux"],
  ["peacock", "le paon", "The peacock spread its tail.", "Animaux"],
  ["rooster", "le coq", "The rooster crowed at dawn.", "Animaux"],
  ["hen", "la poule", "The hen laid three eggs.", "Animaux"],
  ["goat", "la chèvre", "A goat climbed the steep rock.", "Animaux"],
  ["lamb", "l'agneau", "The lamb stayed close to its mother.", "Animaux"],
  ["donkey", "l'âne", "The donkey carried the load.", "Animaux"],
  ["mole", "la taupe", "A mole dug up the lawn.", "Animaux"],
  ["lizard", "le lézard", "A lizard basked on the wall.", "Animaux"],
  ["toad", "le crapaud", "A toad hid under a stone.", "Animaux"],
  ["caterpillar", "la chenille", "The caterpillar ate the leaf.", "Animaux"],
  ["dragonfly", "la libellule", "A dragonfly hovered over the pond.", "Animaux"],
  ["mosquito", "le moustique", "A mosquito bit my ankle.", "Animaux"],
  ["worm", "le ver", "The bird pulled a worm from the soil.", "Animaux"],

  /* --- Nature & géographie --- */
  ["hill", "la colline", "They walked up the grassy hill.", "Nature"],
  ["valley", "la vallée", "The town sits in a green valley.", "Nature"],
  ["cave", "la grotte", "Bats live deep in the cave.", "Nature"],
  ["waterfall", "la cascade / la chute d'eau", "We swam below the waterfall.", "Nature"],
  ["swamp", "le marais / le marécage", "Mosquitoes thrive in the swamp.", "Nature"],
  ["meadow", "la prairie / le pré", "Wildflowers filled the meadow.", "Nature"],
  ["field", "le champ", "The field was full of wheat.", "Nature"],
  ["orchard", "le verger", "The orchard smells of apples.", "Nature"],
  ["vineyard", "le vignoble", "The vineyard covers the hillside.", "Nature"],
  ["harvest", "la récolte / la moisson", "This year's harvest was poor.", "Nature"],
  ["seed", "la graine", "Plant the seeds in spring.", "Nature"],
  ["blossom", "la fleur (d'arbre)", "The cherry blossom is beautiful.", "Nature"],
  ["petal", "le pétale", "A petal fell from the rose.", "Nature"],
  ["thorn", "l'épine", "A thorn pricked her finger.", "Nature"],
  ["bark", "l'écorce", "The bark of the oak is rough.", "Nature"],
  ["moss", "la mousse (végétale)", "Moss grew on the north wall.", "Nature"],
  ["mushroom", "le champignon", "We picked mushrooms in the woods.", "Nature"],
  ["weed", "la mauvaise herbe", "Weeds took over the garden.", "Nature"],
  ["leaf", "la feuille", "A single leaf drifted down.", "Nature"],
  ["sand", "le sable", "The sand was warm under our feet.", "Nature"],
  ["dust", "la poussière", "A layer of dust covered the shelf.", "Nature"],
  ["ash", "la cendre", "Ash fell from the volcano.", "Nature"],
  ["clay", "l'argile", "The pot was made of clay.", "Nature"],
  ["tide", "la marée", "The tide is coming in.", "Nature"],
  ["wave", "la vague", "A big wave knocked him over.", "Nature"],

  /* --- Météo --- */
  ["drizzle", "la bruine", "A light drizzle fell all morning.", "Météo"],
  ["shower", "l'averse", "We got caught in a shower.", "Météo"],
  ["downpour", "la pluie battante", "The picnic was ruined by a downpour.", "Météo"],
  ["drought", "la sécheresse", "The drought killed the crops.", "Météo"],
  ["flood", "l'inondation", "The flood destroyed the bridge.", "Météo"],
  ["heatwave", "la canicule", "A heatwave hit the country.", "Météo"],
  ["blizzard", "le blizzard / la tempête de neige", "The blizzard closed the roads.", "Météo"],
  ["gust", "la rafale", "A gust of wind slammed the door.", "Météo"],
  ["rainbow", "l'arc-en-ciel", "A rainbow appeared after the storm.", "Météo"],
  ["dawn", "l'aube", "We left at dawn.", "Météo"],
  ["dusk", "le crépuscule", "The birds return at dusk.", "Météo"],
  ["sunset", "le coucher de soleil", "The sunset turned the sky orange.", "Météo"],

  /* --- Corps (plus) --- */
  ["skull", "le crâne", "The helmet protects the skull.", "Corps"],
  ["rib", "la côte", "He cracked a rib in the fall.", "Corps"],
  ["hip", "la hanche", "She injured her hip skiing.", "Corps"],
  ["palm", "la paume", "He held the coin in his palm.", "Corps"],
  ["tongue", "la langue (organe)", "She burned her tongue on the soup.", "Corps"],
  ["throat", "la gorge", "I have a sore throat.", "Corps"],
  ["nostril", "la narine", "The smell reached his nostrils.", "Corps"],
  ["kidney", "le rein", "The patient needs a new kidney.", "Corps"],
  ["nerve", "le nerf", "A trapped nerve caused the pain.", "Corps"],
  ["vein", "la veine", "The nurse found a vein easily.", "Corps"],
  ["wrinkle", "la ride", "Fine wrinkles appeared around her eyes.", "Corps"],
  ["scar", "la cicatrice", "He has a scar on his chin.", "Corps"],
  ["limb", "le membre (bras/jambe)", "She stretched her stiff limbs.", "Corps"],
  ["gum", "la gencive", "My gums were bleeding.", "Corps"],

  /* --- Émotions & personnalité --- */
  ["grief", "le chagrin / le deuil", "She was overcome with grief.", "Émotions"],
  ["anger", "la colère", "He struggled to control his anger.", "Émotions"],
  ["fear", "la peur", "Fear kept her awake at night.", "Émotions"],
  ["shame", "la honte", "He felt a deep sense of shame.", "Émotions"],
  ["guilt", "la culpabilité", "Guilt gnawed at him for weeks.", "Émotions"],
  ["pride", "la fierté / l'orgueil", "She took pride in her work.", "Émotions"],
  ["envy", "l'envie / la jalousie", "He watched them with envy.", "Émotions"],
  ["grudge", "la rancune", "She still holds a grudge.", "Émotions"],
  ["relief", "le soulagement", "It was a huge relief to finish.", "Émotions"],
  ["dread", "l'appréhension / l'effroi", "He felt a growing dread.", "Émotions"],
  ["awe", "l'émerveillement / la crainte", "They stared in awe at the canyon.", "Émotions"],
  ["boredom", "l'ennui", "Boredom set in after an hour.", "Émotions"],
  ["mood", "l'humeur", "She's in a good mood today.", "Émotions"],
  ["to soothe", "apaiser / calmer", "The music soothed the baby.", "Émotions"],
  ["to comfort", "réconforter", "He tried to comfort his friend.", "Émotions"],
  ["outgoing", "extraverti / sociable", "She's outgoing and makes friends easily.", "Émotions"],
  ["shy", "timide", "The boy was too shy to speak.", "Émotions"],
  ["moody", "lunatique / d'humeur changeante", "He's been moody all week.", "Émotions"],
  ["easygoing", "décontracté / facile à vivre", "Our new boss is easygoing.", "Émotions"],
  ["thoughtful", "attentionné / prévenant", "That was a thoughtful gift.", "Émotions"],
  ["selfish", "égoïste", "It was a selfish decision.", "Émotions"],
  ["ruthless", "impitoyable / sans pitié", "A ruthless competitor.", "Émotions"],
  ["humble", "humble / modeste", "He stayed humble despite his fame.", "Émotions"],
  ["witty", "spirituel / plein d'esprit", "Her witty reply made us laugh.", "Émotions"],
  ["cunning", "rusé / malin", "A cunning plan worked perfectly.", "Émotions"],
  ["greedy", "avide / cupide / gourmand", "He was greedy for power.", "Émotions"],

  /* --- Métiers --- */
  ["plumber", "le plombier", "The plumber fixed the leak.", "Métiers"],
  ["carpenter", "le menuisier / le charpentier", "A carpenter built the shelves.", "Métiers"],
  ["electrician", "l'électricien", "The electrician rewired the house.", "Métiers"],
  ["lawyer", "l'avocat", "She hired a lawyer.", "Métiers"],
  ["judge", "le juge", "The judge dismissed the case.", "Métiers"],
  ["accountant", "le comptable", "The accountant filed the taxes.", "Métiers"],
  ["surgeon", "le chirurgien", "The surgeon performed the operation.", "Métiers"],
  ["nurse", "l'infirmier / l'infirmière", "The nurse checked his pulse.", "Métiers"],
  ["firefighter", "le pompier", "Firefighters put out the blaze.", "Métiers"],
  ["butcher", "le boucher", "The butcher cut the meat.", "Métiers"],
  ["baker", "le boulanger", "The baker rose before dawn.", "Métiers"],
  ["hairdresser", "le coiffeur / la coiffeuse", "The hairdresser trimmed my hair.", "Métiers"],
  ["cashier", "le caissier / la caissière", "The cashier gave me change.", "Métiers"],
  ["clerk", "l'employé (de bureau/magasin)", "A clerk stamped the form.", "Métiers"],
  ["janitor", "le concierge / l'agent d'entretien", "The janitor locked the school.", "Métiers"],
  ["farmer", "l'agriculteur / le fermier", "The farmer milked the cows.", "Métiers"],
  ["sailor", "le marin", "The sailor tied the rope.", "Métiers"],
  ["waiter", "le serveur", "The waiter brought the menu.", "Métiers"],

  /* --- Nourriture & ingrédients --- */
  ["wheat", "le blé", "The field of wheat swayed.", "Cuisine"],
  ["flour", "la farine", "Add two cups of flour.", "Cuisine"],
  ["yeast", "la levure", "Yeast makes the bread rise.", "Cuisine"],
  ["beans", "les haricots", "We had rice and beans.", "Cuisine"],
  ["peas", "les petits pois", "The children hate peas.", "Cuisine"],
  ["cabbage", "le chou", "She shredded the cabbage.", "Cuisine"],
  ["spinach", "les épinards", "Spinach is rich in iron.", "Cuisine"],
  ["lettuce", "la laitue / la salade", "Wash the lettuce well.", "Cuisine"],
  ["cucumber", "le concombre", "Slice the cucumber thinly.", "Cuisine"],
  ["garlic", "l'ail", "Add a clove of garlic.", "Cuisine"],
  ["ginger", "le gingembre", "Fresh ginger adds heat.", "Cuisine"],
  ["leek", "le poireau", "Leek soup is warming.", "Cuisine"],
  ["pumpkin", "le potiron / la citrouille", "We carved a pumpkin.", "Cuisine"],
  ["plum", "la prune", "The plum was juicy and ripe.", "Cuisine"],
  ["cherry", "la cerise", "She spat out the cherry stone.", "Cuisine"],
  ["peach", "la pêche", "The peach was soft and sweet.", "Cuisine"],
  ["raspberry", "la framboise", "Raspberry jam on toast.", "Cuisine"],
  ["walnut", "la noix", "He cracked a walnut.", "Cuisine"],
  ["almond", "l'amande", "Almond milk in my coffee.", "Cuisine"],
  ["honey", "le miel", "A spoon of honey in tea.", "Cuisine"],
  ["jam", "la confiture", "Strawberry jam on a scone.", "Cuisine"],
  ["vinegar", "le vinaigre", "Add a splash of vinegar.", "Cuisine"],
  ["to chop", "hacher / couper (en morceaux)", "Chop the onions finely.", "Cuisine"],
  ["to stir", "remuer", "Stir the sauce constantly.", "Cuisine"],
  ["to pour", "verser", "Pour the milk into the jug.", "Cuisine"],
  ["to chew", "mâcher", "Chew your food slowly.", "Cuisine"],
  ["to swallow", "avaler", "The pill was hard to swallow.", "Cuisine"],
  ["oven", "le four", "Preheat the oven to 200 degrees.", "Cuisine"],
  ["stove", "la cuisinière / le fourneau", "Something is burning on the stove.", "Cuisine"],
  ["tray", "le plateau", "She carried the tray of glasses.", "Cuisine"],
  ["bowl", "le bol / le saladier", "Beat the eggs in a bowl.", "Cuisine"],
  ["cutlery", "les couverts", "Set the cutlery on the table.", "Cuisine"],
  ["apron", "le tablier", "The chef wore a white apron.", "Cuisine"],

  /* --- Maison (plus) --- */
  ["towel", "la serviette", "Dry your hands on the towel.", "Maison"],
  ["sheet", "le drap", "She changed the bed sheets.", "Maison"],
  ["mattress", "le matelas", "The mattress is too firm.", "Maison"],
  ["wardrobe", "l'armoire / la penderie", "Hang your coat in the wardrobe.", "Maison"],
  ["cupboard", "le placard", "The mugs are in the cupboard.", "Maison"],
  ["mirror", "le miroir / la glace", "She checked the mirror.", "Maison"],
  ["vase", "le vase", "He put the flowers in a vase.", "Maison"],
  ["mop", "la serpillière / le balai à franges", "Mop the kitchen floor.", "Maison"],
  ["sponge", "l'éponge", "Wipe it with a wet sponge.", "Maison"],
  ["bin", "la poubelle", "Throw it in the bin.", "Maison"],
  ["hanger", "le cintre", "There are no hangers left.", "Maison"],
  ["chimney", "la cheminée (conduit)", "Smoke rose from the chimney.", "Maison"],
  ["tile", "le carreau / la tuile", "One tile came loose.", "Maison"],
  ["brick", "la brique", "The wall is made of brick.", "Maison"],
  ["beam", "la poutre", "An oak beam crossed the ceiling.", "Maison"],
  ["railing", "la rampe / la balustrade", "Hold the railing on the stairs.", "Maison"],

  /* --- Ville & commerces --- */
  ["grocery store", "l'épicerie", "I stopped at the grocery store.", "Ville"],
  ["pharmacy", "la pharmacie", "The pharmacy closes at eight.", "Ville"],
  ["hardware store", "la quincaillerie", "Buy nails at the hardware store.", "Ville"],
  ["town hall", "la mairie / l'hôtel de ville", "The town hall is downtown.", "Ville"],
  ["fountain", "la fontaine", "Coins glittered in the fountain.", "Ville"],
  ["bench", "le banc", "They sat on a park bench.", "Ville"],
  ["crossroads", "le carrefour", "Turn left at the crossroads.", "Ville"],
  ["dead end", "l'impasse / le cul-de-sac", "The street is a dead end.", "Ville"],
  ["suburb", "la banlieue", "They live in a quiet suburb.", "Ville"],
  ["outskirts", "la périphérie / les abords", "The factory is on the outskirts.", "Ville"],
  ["neighborhood", "le quartier", "It's a friendly neighborhood.", "Ville"],
  ["laundromat", "la laverie automatique", "I do my washing at the laundromat.", "Ville"],

  /* --- Transport --- */
  ["wheel", "la roue", "The front wheel is buckled.", "Transport"],
  ["tyre", "le pneu", "I had a flat tyre.", "Transport"],
  ["brake", "le frein", "The brakes are worn.", "Transport"],
  ["steering wheel", "le volant", "Keep both hands on the steering wheel.", "Transport"],
  ["seatbelt", "la ceinture de sécurité", "Fasten your seatbelt.", "Transport"],
  ["trunk", "le coffre (voiture)", "Put the bags in the trunk.", "Transport"],
  ["hood", "le capot", "Steam rose from under the hood.", "Transport"],
  ["fuel", "le carburant", "We're running low on fuel.", "Transport"],
  ["ferry", "le ferry / le bac", "We took the ferry across.", "Transport"],
  ["sailboat", "le voilier", "A sailboat crossed the bay.", "Transport"],
  ["anchor", "l'ancre", "They dropped the anchor.", "Transport"],
  ["helmet", "le casque", "Always wear a helmet.", "Transport"],
  ["aisle", "l'allée / le couloir", "I prefer an aisle seat.", "Transport"],

  /* --- Santé & médical --- */
  ["ache", "la douleur (sourde)", "I have an ache in my back.", "Santé"],
  ["cough", "la toux", "He has a nasty cough.", "Santé"],
  ["fever", "la fièvre", "The child had a high fever.", "Santé"],
  ["rash", "l'éruption cutanée / les rougeurs", "A rash spread on her arm.", "Santé"],
  ["wound", "la blessure / la plaie", "The wound is healing well.", "Santé"],
  ["bandage", "le pansement / le bandage", "Wrap a bandage around it.", "Santé"],
  ["crutch", "la béquille", "He walks on crutches now.", "Santé"],
  ["prescription", "l'ordonnance", "The doctor wrote a prescription.", "Santé"],
  ["painkiller", "l'antidouleur / l'analgésique", "She took a painkiller.", "Santé"],
  ["side effect", "l'effet secondaire", "Drowsiness is a side effect.", "Santé"],
  ["to heal", "guérir / cicatriser", "The cut healed quickly.", "Santé"],
  ["to swell", "enfler / gonfler", "His ankle began to swell.", "Santé"],
  ["to faint", "s'évanouir", "She fainted in the heat.", "Santé"],
  ["to recover", "se rétablir / récupérer", "He recovered after a week.", "Santé"],
  ["dizzy", "pris de vertige / étourdi", "I feel dizzy when I stand up.", "Santé"],
  ["numb", "engourdi / insensible", "My fingers went numb.", "Santé"],

  /* --- École & études --- */
  ["homework", "les devoirs", "Finish your homework first.", "École"],
  ["essay", "la dissertation / la rédaction", "I have an essay due tomorrow.", "École"],
  ["grade", "la note", "She got a top grade.", "École"],
  ["degree", "le diplôme (universitaire)", "He earned a degree in law.", "École"],
  ["term", "le trimestre / le semestre", "Exams are at the end of term.", "École"],
  ["eraser", "la gomme", "Use an eraser to fix it.", "École"],
  ["highlighter", "le surligneur", "She highlighted the key points.", "École"],
  ["notebook", "le cahier / le carnet", "Write it in your notebook.", "École"],
  ["to memorize", "mémoriser / apprendre par cœur", "Memorize these ten words.", "École"],
  ["to cram", "bachoter / réviser à la dernière minute", "He crammed all night.", "École"],

  /* --- Argent & achats --- */
  ["change", "la monnaie", "Keep the change.", "Argent"],
  ["receipt", "le reçu / le ticket de caisse", "Keep the receipt for the refund.", "Argent"],
  ["coin", "la pièce (de monnaie)", "He flipped a coin.", "Argent"],
  ["wallet", "le portefeuille", "I left my wallet at home.", "Argent"],
  ["purse", "le porte-monnaie / (US) le sac à main", "She rummaged in her purse.", "Argent"],
  ["savings", "les économies / l'épargne", "They spent their savings.", "Argent"],
  ["loan", "le prêt / l'emprunt", "He took out a loan.", "Argent"],
  ["debt", "la dette", "She's finally free of debt.", "Argent"],
  ["tax", "l'impôt / la taxe", "Prices include tax.", "Argent"],
  ["bargain", "la bonne affaire", "At that price, it's a bargain.", "Argent"],
  ["to afford", "pouvoir se permettre", "We can't afford a new car.", "Argent"],
  ["to owe", "devoir (de l'argent)", "You still owe me ten euros.", "Argent"],
  ["to lend", "prêter", "Can you lend me a pen?", "Argent"],
  ["to borrow", "emprunter", "May I borrow your charger?", "Argent"],
  ["thrifty", "économe / regardant", "She's thrifty but not stingy.", "Argent"],

  /* --- Verbes du quotidien (plus) --- */
  ["to fetch", "aller chercher (et rapporter)", "The dog fetched the stick.", "Verbes"],
  ["to drag", "traîner / tirer", "He dragged the box across the floor.", "Verbes"],
  ["to poke", "donner un petit coup / tapoter", "She poked him to wake him.", "Verbes"],
  ["to scratch", "gratter / griffer / rayer", "The cat scratched the sofa.", "Verbes"],
  ["to rub", "frotter", "Rub the stain gently.", "Verbes"],
  ["to pinch", "pincer", "The shoes pinch my toes.", "Verbes"],
  ["to pat", "tapoter (doucement)", "She patted the dog.", "Verbes"],
  ["to hug", "serrer dans ses bras / étreindre", "They hugged goodbye.", "Verbes"],
  ["to kneel", "s'agenouiller", "He knelt to tie his lace.", "Verbes"],
  ["to shake", "secouer / trembler", "Shake the bottle well.", "Verbes"],
  ["to toss", "lancer / jeter (négligemment)", "He tossed the keys on the table.", "Verbes"],
  ["to drip", "goutter / dégouliner", "The tap keeps dripping.", "Verbes"],
  ["to splash", "éclabousser", "The kids splashed in the pool.", "Verbes"],
  ["to sink", "couler / s'enfoncer", "The boat began to sink.", "Verbes"],
  ["to float", "flotter", "Wood floats on water.", "Verbes"],
  ["to burst", "éclater / exploser", "The balloon burst loudly.", "Verbes"],
  ["to chase", "poursuivre / courir après", "The cat chased the mouse.", "Verbes"],
  ["to flee", "fuir / s'enfuir", "The villagers fled the fire.", "Verbes"],
  ["to reach", "atteindre / arriver à", "We reached the summit at noon.", "Verbes"],
  ["to spread", "étaler / répandre / se propager", "Spread the butter evenly.", "Verbes"],
  ["to gather", "rassembler / se réunir", "A crowd gathered outside.", "Verbes"],
  ["to scatter", "éparpiller / disperser", "The wind scattered the papers.", "Verbes"],
  ["to lift", "soulever / lever", "Lift with your legs, not your back.", "Verbes"],
  ["to hang", "suspendre / accrocher / pendre", "Hang your coat on the hook.", "Verbes"],

  /* --- Adjectifs concrets --- */
  ["tiny", "minuscule", "A tiny insect crawled by.", "Adjectifs"],
  ["huge", "énorme", "They live in a huge house.", "Adjectifs"],
  ["narrow", "étroit", "The alley was too narrow for cars.", "Adjectifs"],
  ["steep", "raide / escarpé / abrupt", "The path is very steep.", "Adjectifs"],
  ["rough", "rugueux / rude / agité", "The sea was rough.", "Adjectifs"],
  ["smooth", "lisse / doux", "The stone felt smooth.", "Adjectifs"],
  ["sticky", "collant / poisseux", "My hands are sticky.", "Adjectifs"],
  ["slippery", "glissant", "The floor is slippery when wet.", "Adjectifs"],
  ["damp", "humide / moite", "The cellar smelled damp.", "Adjectifs"],
  ["crisp", "croustillant / frais et net", "Crisp autumn air.", "Adjectifs"],
  ["spicy", "épicé / relevé", "The curry was very spicy.", "Adjectifs"],
  ["bland", "fade / insipide", "The soup was rather bland.", "Adjectifs"],
  ["tough", "dur / coriace / difficile", "The meat was tough.", "Adjectifs"],
  ["loose", "lâche / desserré / ample", "A screw came loose.", "Adjectifs"],
  ["tight", "serré / étroit", "These jeans are too tight.", "Adjectifs"],
  ["hollow", "creux", "The tree trunk was hollow.", "Adjectifs"],
  ["plain", "simple / ordinaire / uni", "A plain white shirt.", "Adjectifs"],
  ["filthy", "crasseux / dégoûtant", "His boots were filthy.", "Adjectifs"],
  ["neat", "soigné / ordonné / net", "Her desk is always neat.", "Adjectifs"],
  ["messy", "en désordre / bordélique", "The kids left the room messy.", "Adjectifs"],

  /* --- Registre soutenu (C1-C2) --- */
  ["to deem", "juger / estimer / considérer", "The plan was deemed too risky.", "Soutenu"],
  ["to entail", "impliquer / comporter", "The job entails a lot of travel.", "Soutenu"],
  ["to curb", "freiner / juguler / enrayer", "New rules aim to curb spending.", "Soutenu"],
  ["to spur", "stimuler / inciter", "Tax cuts spurred growth.", "Soutenu"],
  ["to hamper", "gêner / entraver", "Rain hampered the search.", "Soutenu"],
  ["to bolster", "renforcer / consolider", "The news bolstered confidence.", "Soutenu"],
  ["to jeopardize", "compromettre / mettre en péril", "The delay could jeopardize the deal.", "Soutenu"],
  ["to reconcile", "concilier / réconcilier", "It's hard to reconcile the two views.", "Soutenu"],
  ["to scrutinize", "examiner minutieusement", "Auditors scrutinized the accounts.", "Soutenu"],
  ["to advocate", "préconiser / plaider pour", "She advocates stricter laws.", "Soutenu"],
  ["to refrain", "s'abstenir (de)", "Please refrain from smoking.", "Soutenu"],
  ["to prevail", "prévaloir / l'emporter", "Common sense finally prevailed.", "Soutenu"],
  ["to stem from", "découler de / provenir de", "The issue stems from poor design.", "Soutenu"],
  ["to strive", "s'efforcer / lutter (pour)", "We strive for excellence.", "Soutenu"],
  ["plausible", "plausible / vraisemblable", "That's a plausible explanation.", "Soutenu"],
  ["feasible", "faisable / réalisable", "The project is technically feasible.", "Soutenu"],
  ["arbitrary", "arbitraire", "The choice seemed arbitrary.", "Soutenu"],
  ["inherent", "inhérent / intrinsèque", "There are risks inherent in trading.", "Soutenu"],
  ["blatant", "flagrant / manifeste", "A blatant lie.", "Soutenu"],
  ["subtle", "subtil / nuancé / discret", "There's a subtle difference.", "Soutenu"],
  ["compelling", "convaincant / captivant", "A compelling argument.", "Soutenu"],
  ["overarching", "global / prédominant", "The overarching goal is trust.", "Soutenu"],

  /* --- Phrasal verbs (plus) --- */
  ["to give up", "abandonner / renoncer", "Don't give up so easily.", "Phrasal verbs"],
  ["to work out", "faire du sport ; résoudre", "It all worked out in the end.", "Phrasal verbs"],
  ["to sort out", "régler / trier / arranger", "We need to sort out this mess.", "Phrasal verbs"],
  ["to come up with", "trouver / proposer (une idée)", "She came up with a clever plan.", "Phrasal verbs"],
  ["to put up with", "supporter / tolérer", "I can't put up with the noise.", "Phrasal verbs"],
  ["to look forward to", "attendre avec impatience", "I look forward to hearing from you.", "Phrasal verbs"],
  ["to get along", "bien s'entendre", "They get along well.", "Phrasal verbs"],
  ["to run into", "tomber sur (qqn) / heurter", "I ran into an old friend.", "Phrasal verbs"],
  ["to bring up", "aborder (un sujet) / élever", "Don't bring up politics.", "Phrasal verbs"],
  ["to break down", "tomber en panne / s'effondrer", "The car broke down again.", "Phrasal verbs"],
  ["to show up", "se pointer / arriver", "He showed up an hour late.", "Phrasal verbs"],
  ["to hold on", "attendre / tenir bon", "Hold on a second.", "Phrasal verbs"],
  ["to make up", "inventer ; se réconcilier", "He made up an excuse.", "Phrasal verbs"],
  ["to back up", "soutenir ; sauvegarder", "Back up your files regularly.", "Phrasal verbs"],
  ["to catch up", "rattraper (son retard)", "I need to catch up on emails.", "Phrasal verbs"],
  ["to drop off", "déposer (qqn/qqch)", "I'll drop you off on the way.", "Phrasal verbs"],
  ["to hang out", "traîner / passer du temps", "We hung out at the café.", "Phrasal verbs"],
  ["to end up", "finir par / se retrouver", "We ended up walking home.", "Phrasal verbs"],

  /* --- Idiomes (plus) --- */
  ["to be on the same page", "être sur la même longueur d'onde", "Let's make sure we're on the same page.", "Idiomes"],
  ["to get cold feet", "se dégonfler (au dernier moment)", "He got cold feet before the wedding.", "Idiomes"],
  ["to be in hot water", "avoir des ennuis / être dans le pétrin", "He's in hot water with the boss.", "Idiomes"],
  ["to go the extra mile", "se donner à fond / faire un effort supplémentaire", "She always goes the extra mile.", "Idiomes"],
  ["to cut corners", "bâcler / faire au plus vite", "Don't cut corners on safety.", "Idiomes"],
  ["to play it by ear", "improviser / voir au fur et à mesure", "Let's just play it by ear.", "Idiomes"],
  ["to be a rip-off", "être une arnaque", "Ten euros for a coffee is a rip-off.", "Idiomes"],
  ["to be worth a shot", "valoir le coup d'essayer", "It might not work, but it's worth a shot.", "Idiomes"],
  ["to have second thoughts", "avoir des doutes / hésiter", "I'm having second thoughts about it.", "Idiomes"],
  ["a blessing in disguise", "un mal pour un bien", "Losing that job was a blessing in disguise.", "Idiomes"],
  ["to keep an eye on", "surveiller / garder un œil sur", "Keep an eye on the kids.", "Idiomes"],
  ["to get on someone's nerves", "taper sur les nerfs de qqn", "That noise gets on my nerves.", "Idiomes"],
  ["to be fed up", "en avoir marre / ras-le-bol", "I'm fed up with waiting.", "Idiomes"],
  ["to make sense", "avoir du sens / être logique", "That doesn't make sense.", "Idiomes"],
  ["to be worth it", "en valoir la peine", "It's expensive, but worth it.", "Idiomes"],

  /* --- Faux-amis (plus) --- */
  ["to support", "soutenir / appuyer (≠ supporter = to bear/tolerate)", "I support your decision.", "Faux-amis"],
  ["to pretend", "faire semblant (≠ prétendre = to claim)", "He pretended to be asleep.", "Faux-amis"],
  ["to realize", "se rendre compte (≠ réaliser un projet = to carry out)", "I didn't realize it was so late.", "Faux-amis"],
  ["college", "l'université / la fac (≠ collège = middle school)", "She's away at college.", "Faux-amis"],
  ["to pass an exam", "réussir un examen (≠ passer = to sit/take)", "He passed the exam with ease.", "Faux-amis"],
  ["a course", "un cours (≠ course = race / errand)", "I'm taking a Spanish course.", "Faux-amis"],
  ["to advertise", "faire de la publicité (≠ avertir = to warn)", "They advertise on TV.", "Faux-amis"],
  ["an issue", "un problème / une question (≠ issue = exit)", "We need to fix this issue.", "Faux-amis"],
  ["inconvenient", "gênant / peu pratique (≠ inconvénient = drawback)", "It's an inconvenient time.", "Faux-amis"],
  ["to deceive", "tromper (≠ décevoir = to disappoint)", "He deceived his own family.", "Faux-amis"],
  ["eventually (rappel)", "finalement (≠ éventuellement = possibly)", "She eventually gave in.", "Faux-amis"],
  ["to injure", "blesser (≠ injurier = to insult)", "Three people were injured.", "Faux-amis"],

  /* --- Connecteurs & adverbes soutenus --- */
  ["therefore", "par conséquent / donc", "The data is flawed; therefore, we can't conclude.", "Connecteurs"],
  ["nonetheless", "néanmoins / cependant", "It's risky; nonetheless, we'll try.", "Connecteurs"],
  ["moreover", "de plus / en outre", "The plan is costly; moreover, it's slow.", "Connecteurs"],
  ["furthermore", "en outre / qui plus est", "Furthermore, the deadline is tight.", "Connecteurs"],
  ["hence", "d'où / par conséquent", "He's new here, hence the confusion.", "Connecteurs"],
  ["thus", "ainsi / de ce fait", "Sales rose, thus boosting profits.", "Connecteurs"],
  ["whereas", "tandis que / alors que", "He's calm, whereas she's anxious.", "Connecteurs"],
  ["albeit", "quoique / bien que (soutenu)", "A useful, albeit costly, solution.", "Connecteurs"],
  ["regardless", "quoi qu'il en soit / sans tenir compte", "We'll proceed regardless.", "Connecteurs"],
  ["likewise", "de même / pareillement", "She left early; likewise did he.", "Connecteurs"],
  ["indeed", "en effet / effectivement", "It was, indeed, a mistake.", "Connecteurs"],
  ["seldom", "rarement (soutenu)", "He seldom complains.", "Connecteurs"],
  ["barely", "à peine / tout juste", "I could barely hear her.", "Connecteurs"],
  ["throughout", "tout au long de / partout dans", "It rained throughout the trip.", "Connecteurs"],
  ["meanwhile", "pendant ce temps / entre-temps", "Meanwhile, the guests waited.", "Connecteurs"]

]);
