/* ============================================================
   990 — Vocabulaire supplémentaire (presse, littéraire, phrasal,
   expressions, C1-C2, connecteurs, nature/sciences).
   Format : [recto EN, verso FR, exemple EN, thème]
   Ajouté au vivier VOCAB. Charger après data.js.
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  /* --- Presse & actualité --- */
  ["outlet", "un média / un organe de presse", "The story broke across several major outlets.", "Presse & actualité"],
  ["op-ed", "une tribune (article d'opinion)", "She wrote an op-ed criticising the reform.", "Presse & actualité"],
  ["headline", "le titre / le gros titre", "The scandal made headlines for weeks.", "Presse & actualité"],
  ["coverage", "la couverture médiatique", "The election received wall-to-wall coverage.", "Presse & actualité"],
  ["watchdog", "un organisme de surveillance / une vigie", "The press acts as a watchdog on power.", "Presse & actualité"],
  ["leak", "une fuite (d'information)", "The leak exposed the secret negotiations.", "Presse & actualité"],
  ["whistleblower", "un lanceur d'alerte", "The whistleblower revealed the fraud.", "Presse & actualité"],
  ["biased", "partial / orienté", "Critics called the report biased.", "Presse & actualité"],
  ["fact-check", "vérifier les faits", "Journalists fact-check claims before publishing.", "Presse & actualité"],
  ["backlash", "un retour de bâton / une levée de boucliers", "The decision sparked a fierce backlash.", "Presse & actualité"],
  ["turnout", "le taux de participation", "Voter turnout was unusually high.", "Presse & actualité"],
  ["landmark", "historique / qui fait date", "The court issued a landmark ruling.", "Presse & actualité"],
  ["crackdown", "une répression / un tour de vis", "The government launched a crackdown on fraud.", "Presse & actualité"],
  ["unfold", "se dérouler (événements)", "The crisis unfolded over several days.", "Presse & actualité"],
  ["mounting", "croissant / qui s'accumule", "There is mounting pressure on the minister.", "Presse & actualité"],
  ["allegation", "une accusation (non prouvée)", "He denied the allegations of misconduct.", "Presse & actualité"],
  ["probe", "une enquête", "A federal probe is under way.", "Presse & actualité"],
  ["curb", "limiter / freiner", "New rules aim to curb emissions.", "Presse & actualité"],
  ["soar", "grimper en flèche", "Energy prices soared last winter.", "Presse & actualité"],
  ["plummet", "chuter brutalement", "Shares plummeted after the announcement.", "Presse & actualité"],
  ["loom", "se profiler (menace)", "A recession loomed on the horizon.", "Presse & actualité"],
  ["pledge", "une promesse / s'engager à", "Leaders pledged to cut emissions.", "Presse & actualité"],
  ["sweeping", "de grande ampleur / radical", "The bill brings sweeping reforms.", "Presse & actualité"],
  ["scrutiny", "un examen minutieux", "The deal came under close scrutiny.", "Presse & actualité"],

  /* --- Littéraire --- */
  ["dusk", "le crépuscule", "The town glowed softly at dusk.", "Littéraire"],
  ["dawn", "l'aube", "They set off at dawn.", "Littéraire"],
  ["shimmer", "chatoyer / miroiter", "The lake shimmered under the moon.", "Littéraire"],
  ["linger", "s'attarder / persister", "The scent of rain lingered in the air.", "Littéraire"],
  ["gaze", "le regard (fixe) / contempler", "She held his gaze without flinching.", "Littéraire"],
  ["whisper", "murmurer / un murmure", "The wind whispered through the pines.", "Littéraire"],
  ["solitude", "la solitude (choisie)", "He found a strange peace in solitude.", "Littéraire"],
  ["melancholy", "la mélancolie", "A quiet melancholy hung over the house.", "Littéraire"],
  ["yearn", "aspirer ardemment à", "She yearned for a life at sea.", "Littéraire"],
  ["frail", "frêle / fragile", "His frail hands trembled.", "Littéraire"],
  ["vast", "immense / vaste", "The vast plain stretched to the horizon.", "Littéraire"],
  ["weary", "las / épuisé", "The weary traveller sat by the fire.", "Littéraire"],
  ["dread", "l'effroi / redouter", "A sense of dread crept over her.", "Littéraire"],
  ["radiant", "radieux / rayonnant", "Her face was radiant with joy.", "Littéraire"],
  ["twilight", "le demi-jour / le crépuscule", "They walked home in the twilight.", "Littéraire"],
  ["quiver", "frémir / trembler", "His voice quivered with emotion.", "Littéraire"],
  ["wander", "errer / vagabonder", "They wandered the old streets for hours.", "Littéraire"],
  ["desolate", "désolé / abandonné", "The moor was cold and desolate.", "Littéraire"],
  ["serene", "serein", "The lake was perfectly serene.", "Littéraire"],
  ["haunt", "hanter", "The memory haunted him for years.", "Littéraire"],

  /* --- Verbes à particule (phrasal verbs) --- */
  ["carry out", "réaliser / mener (une tâche)", "They carried out a thorough survey.", "Phrasal verbs"],
  ["bring about", "provoquer / entraîner", "The crisis brought about deep reforms.", "Phrasal verbs"],
  ["put off", "reporter / rebuter", "They put off the meeting until Monday.", "Phrasal verbs"],
  ["turn down", "refuser / rejeter", "She turned down the offer.", "Phrasal verbs"],
  ["look into", "examiner / enquêter sur", "We'll look into the complaint.", "Phrasal verbs"],
  ["come up with", "trouver / imaginer (une idée)", "He came up with a clever solution.", "Phrasal verbs"],
  ["call off", "annuler", "They called off the strike.", "Phrasal verbs"],
  ["point out", "souligner / faire remarquer", "She pointed out a flaw in the plan.", "Phrasal verbs"],
  ["rule out", "exclure / écarter", "Police have not ruled out foul play.", "Phrasal verbs"],
  ["step down", "démissionner / se retirer", "The CEO stepped down abruptly.", "Phrasal verbs"],
  ["roll out", "déployer / lancer", "The company rolled out the update.", "Phrasal verbs"],
  ["cut back", "réduire", "Households cut back on spending.", "Phrasal verbs"],
  ["stand out", "se démarquer / ressortir", "Her essay really stood out.", "Phrasal verbs"],
  ["wear off", "s'estomper / se dissiper", "The excitement soon wore off.", "Phrasal verbs"],
  ["get across", "faire passer (un message)", "He struggled to get his point across.", "Phrasal verbs"],
  ["account for", "expliquer / représenter (une part)", "Exports account for half of sales.", "Phrasal verbs"],

  /* --- Expressions idiomatiques --- */
  ["a blessing in disguise", "un mal pour un bien", "Losing that job was a blessing in disguise.", "Expressions"],
  ["the tip of the iceberg", "la partie émergée de l'iceberg", "These complaints are just the tip of the iceberg.", "Expressions"],
  ["to bite the bullet", "prendre son courage à deux mains", "I bit the bullet and asked for a raise.", "Expressions"],
  ["to cut corners", "bâcler / faire au rabais", "Never cut corners on safety.", "Expressions"],
  ["once in a blue moon", "tous les trente-six du mois", "We see each other once in a blue moon.", "Expressions"],
  ["to be on the fence", "être indécis / hésiter", "I'm still on the fence about the offer.", "Expressions"],
  ["to break the ice", "briser la glace", "A joke helped break the ice.", "Expressions"],
  ["to jump the gun", "agir prématurément", "Don't jump the gun before the results.", "Expressions"],
  ["food for thought", "matière à réflexion", "Her talk gave us food for thought.", "Expressions"],
  ["to take with a grain of salt", "prendre avec des pincettes", "Take that rumour with a grain of salt.", "Expressions"],
  ["a game changer", "quelque chose qui change la donne", "The new law is a game changer.", "Expressions"],
  ["at odds with", "en désaccord avec / en contradiction avec", "His account is at odds with the facts.", "Expressions"],
  ["to get the hang of it", "prendre le coup de main", "It's tricky, but you'll get the hang of it.", "Expressions"],
  ["to beat around the bush", "tourner autour du pot", "Stop beating around the bush and answer.", "Expressions"],

  /* --- Mots C1-C2 --- */
  ["ubiquitous", "omniprésent", "Smartphones are now ubiquitous.", "Mots C1-C2"],
  ["meticulous", "méticuleux", "She is meticulous about detail.", "Mots C1-C2"],
  ["nuance", "une nuance", "The translation captured every nuance.", "Mots C1-C2"],
  ["compelling", "convaincant / captivant", "She made a compelling argument.", "Mots C1-C2"],
  ["intricate", "complexe / minutieux", "An intricate web of alliances.", "Mots C1-C2"],
  ["profound", "profond", "The book had a profound effect on me.", "Mots C1-C2"],
  ["resilient", "résilient / résistant", "The economy proved surprisingly resilient.", "Mots C1-C2"],
  ["inevitable", "inévitable", "Change was inevitable.", "Mots C1-C2"],
  ["ambiguous", "ambigu", "The wording is deliberately ambiguous.", "Mots C1-C2"],
  ["prevalent", "répandu", "The practice is prevalent in the industry.", "Mots C1-C2"],
  ["contentious", "controversé / litigieux", "It remains a contentious issue.", "Mots C1-C2"],
  ["candid", "franc / sincère", "He gave a candid interview.", "Mots C1-C2"],
  ["daunting", "intimidant / décourageant", "The task seemed daunting at first.", "Mots C1-C2"],
  ["tangible", "tangible / concret", "There were tangible results.", "Mots C1-C2"],
  ["mitigate", "atténuer", "Measures to mitigate the risk.", "Mots C1-C2"],
  ["underpin", "sous-tendre / étayer", "Trust underpins every partnership.", "Mots C1-C2"],
  ["overhaul", "une refonte / réviser en profondeur", "The system needs a complete overhaul.", "Mots C1-C2"],
  ["unprecedented", "sans précédent", "The demand was unprecedented.", "Mots C1-C2"],
  ["stark", "cru / frappant / net", "A stark contrast between rich and poor.", "Mots C1-C2"],
  ["viable", "viable", "It is the only viable option.", "Mots C1-C2"],
  ["cumbersome", "encombrant / lourd (à manier)", "The procedure is cumbersome.", "Mots C1-C2"],
  ["arduous", "ardu / pénible", "An arduous climb to the summit.", "Mots C1-C2"],
  ["succinct", "succinct / concis", "Keep the summary succinct.", "Mots C1-C2"],
  ["scrupulous", "scrupuleux", "He was scrupulous in his accounts.", "Mots C1-C2"],
  ["elusive", "insaisissable / difficile à cerner", "A lasting peace remains elusive.", "Mots C1-C2"],
  ["poignant", "poignant / émouvant", "A poignant farewell scene.", "Mots C1-C2"],

  /* --- Connecteurs & nuance --- */
  ["nonetheless", "néanmoins", "It's risky; nonetheless, we'll try.", "Connecteurs"],
  ["albeit", "quoique / bien que", "A small, albeit significant, gain.", "Connecteurs"],
  ["thereby", "ce faisant / par là même", "Costs fell, thereby boosting profit.", "Connecteurs"],
  ["insofar as", "dans la mesure où", "It helps insofar as it saves time.", "Connecteurs"],
  ["notwithstanding", "malgré / nonobstant", "Notwithstanding the delays, we finished.", "Connecteurs"],
  ["conversely", "à l'inverse", "Conversely, prices may fall.", "Connecteurs"],
  ["hence", "d'où / par conséquent", "He's new here, hence the confusion.", "Connecteurs"],
  ["whereby", "par lequel / selon lequel", "A system whereby users earn points.", "Connecteurs"],
  ["by and large", "dans l'ensemble", "By and large, the plan worked.", "Connecteurs"],
  ["for the most part", "pour l'essentiel", "The reviews were, for the most part, positive.", "Connecteurs"],
  ["all the more", "d'autant plus", "The win is all the more impressive given the odds.", "Connecteurs"],
  ["let alone", "encore moins / sans parler de", "He can't walk, let alone run.", "Connecteurs"],

  /* --- Nature & sciences --- */
  ["canopy", "la canopée", "Sunlight filtered through the canopy.", "Nature & sciences"],
  ["dormant", "en sommeil / dormant", "The volcano has been dormant for centuries.", "Nature & sciences"],
  ["thrive", "prospérer / s'épanouir", "Coral thrives in warm, clear water.", "Nature & sciences"],
  ["barren", "aride / stérile", "The barren landscape stretched for miles.", "Nature & sciences"],
  ["migrate", "migrer", "Millions of birds migrate south each autumn.", "Nature & sciences"],
  ["habitat", "l'habitat", "Deforestation destroys natural habitats.", "Nature & sciences"],
  ["breakthrough", "une percée / une avancée majeure", "The vaccine was a scientific breakthrough.", "Nature & sciences"],
  ["seep", "suinter / s'infiltrer", "Water seeped through the cracks.", "Nature & sciences"],
  ["glow", "briller / luire (doucement)", "The embers glowed in the dark.", "Nature & sciences"],
  ["vanish", "disparaître", "Below a certain depth, sunlight vanishes.", "Nature & sciences"]

]);
