/* ============================================================
   990 — Vocabulaire de REGISTRE SOUTENU (anglais élégant, académique)
   Verbes savants, adjectifs choisis, noms abstraits, tournures rhétoriques.
   Format : [recto EN, verso FR, exemple EN, thème]
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  /* --- Verbes soutenus --- */
  ["to ascertain", "établir / vérifier (avec certitude)", "We must ascertain the facts first.", "Soutenu"],
  ["to elucidate", "élucider / clarifier", "Let me elucidate the main point.", "Soutenu"],
  ["to delineate", "délimiter / exposer clairement", "The report delineates three options.", "Soutenu"],
  ["to expound", "exposer en détail / développer", "She expounded her theory at length.", "Soutenu"],
  ["to posit", "postuler / avancer (une idée)", "The author posits that growth is finite.", "Soutenu"],
  ["to underpin", "sous-tendre / étayer", "Trust underpins every partnership.", "Soutenu"],
  ["to encompass", "englober / recouvrir", "The role encompasses many duties.", "Soutenu"],
  ["to warrant", "justifier / mériter", "The issue warrants further study.", "Soutenu"],
  ["to preclude", "empêcher / exclure", "The clause precludes any refund.", "Soutenu"],
  ["to engender", "engendrer / susciter", "The policy engendered much debate.", "Soutenu"],
  ["to espouse", "épouser / adopter (une cause)", "He espouses free-market views.", "Soutenu"],
  ["to eschew", "éviter / renoncer à", "The firm eschews short-term gains.", "Soutenu"],
  ["to galvanize", "galvaniser / mobiliser", "The speech galvanized the team.", "Soutenu"],
  ["to consolidate", "consolider / affermir", "They consolidated their lead.", "Soutenu"],
  ["to deliberate", "délibérer / réfléchir mûrement", "The jury deliberated for hours.", "Soutenu"],
  ["to reaffirm", "réaffirmer", "The board reaffirmed its commitment.", "Soutenu"],
  ["to allude to", "faire allusion à", "She alluded to earlier failures.", "Soutenu"],
  ["to concur", "être d'accord / concorder", "I concur with your assessment.", "Soutenu"],
  ["to render", "rendre / faire devenir", "The error rendered the data useless.", "Soutenu"],
  ["to yield", "produire / céder", "The study yielded surprising results.", "Soutenu"],

  /* --- Adjectifs choisis --- */
  ["salient", "saillant / marquant", "Let me note the salient points.", "Soutenu"],
  ["cogent", "convaincant / pertinent", "She made a cogent argument.", "Soutenu"],
  ["succinct", "succinct / concis", "Please keep it succinct.", "Soutenu"],
  ["erudite", "érudit / savant", "An erudite and elegant essay.", "Soutenu"],
  ["eloquent", "éloquent", "He gave an eloquent defence.", "Soutenu"],
  ["judicious", "judicieux / avisé", "A judicious use of resources.", "Soutenu"],
  ["pertinent", "pertinent / approprié", "That's a pertinent observation.", "Soutenu"],
  ["tenable", "défendable / tenable", "The position is no longer tenable.", "Soutenu"],
  ["untenable", "indéfendable / intenable", "His argument proved untenable.", "Soutenu"],
  ["commendable", "louable / méritoire", "Their effort was commendable.", "Soutenu"],
  ["incisive", "incisif / tranchant", "An incisive piece of analysis.", "Soutenu"],
  ["exemplary", "exemplaire", "Her conduct was exemplary.", "Soutenu"],
  ["unequivocal", "sans équivoque / catégorique", "An unequivocal refusal.", "Soutenu"],
  ["tentative", "provisoire / hésitant", "We reached a tentative agreement.", "Soutenu"],
  ["pragmatic", "pragmatique", "A pragmatic approach to the crisis.", "Soutenu"],
  ["profound", "profond", "The change had profound effects.", "Soutenu"],
  ["nuanced", "nuancé", "A nuanced view of the issue.", "Soutenu"],
  ["formidable", "redoutable / impressionnant", "A formidable opponent.", "Soutenu"],

  /* --- Noms abstraits soutenus --- */
  ["the crux", "le nœud / le cœur (du problème)", "That's the crux of the matter.", "Soutenu"],
  ["premise", "la prémisse / le postulat", "The argument rests on a false premise.", "Soutenu"],
  ["tenet", "le principe / le dogme", "A central tenet of the theory.", "Soutenu"],
  ["paradigm", "le paradigme / le modèle", "This marks a new paradigm.", "Soutenu"],
  ["discourse", "le discours / le débat", "It shaped public discourse.", "Soutenu"],
  ["connotation", "la connotation", "The word carries a negative connotation.", "Soutenu"],
  ["ramifications", "les ramifications / conséquences", "The ruling has wide ramifications.", "Soutenu"],
  ["implications", "les implications / incidences", "Consider the ethical implications.", "Soutenu"],
  ["paradox", "le paradoxe", "It's a paradox worth pondering.", "Soutenu"],
  ["dichotomy", "la dichotomie / l'opposition", "A false dichotomy between the two.", "Soutenu"],
  ["aftermath", "les suites / les lendemains", "In the aftermath of the crisis.", "Soutenu"],
  ["impetus", "l'impulsion / l'élan", "The report gave impetus to reform.", "Soutenu"],
  ["propensity", "la propension / la tendance", "A propensity for risk-taking.", "Soutenu"],
  ["plethora", "la pléthore / l'abondance", "A plethora of options.", "Soutenu"],
  ["dearth", "la pénurie / le manque", "There's a dearth of evidence.", "Soutenu"],
  ["epitome", "l'incarnation / la quintessence", "She is the epitome of composure.", "Soutenu"],
  ["juxtaposition", "la juxtaposition / le contraste", "The juxtaposition is striking.", "Soutenu"],
  ["hindsight", "le recul / l'après-coup", "In hindsight, it was a mistake.", "Soutenu"],
  ["prowess", "la prouesse / le talent", "Her analytical prowess is remarkable.", "Soutenu"],
  ["scope", "l'étendue / la portée", "That's beyond the scope of this study.", "Soutenu"],

  /* --- Tournures & connecteurs rhétoriques --- */
  ["it is worth noting that", "il convient de noter que", "It is worth noting that costs vary.", "Connecteurs"],
  ["it stands to reason that", "il va de soi que / il est logique que", "It stands to reason that demand will rise.", "Connecteurs"],
  ["in light of", "à la lumière de / compte tenu de", "In light of recent events, we paused.", "Connecteurs"],
  ["with a view to", "en vue de / dans le but de", "With a view to cutting costs, we merged.", "Connecteurs"],
  ["for the sake of", "par souci de / pour", "For the sake of clarity, let me repeat.", "Connecteurs"],
  ["in the wake of", "dans le sillage de / à la suite de", "In the wake of the scandal, he resigned.", "Connecteurs"],
  ["on the grounds that", "au motif que / sous prétexte que", "It was rejected on the grounds that it was late.", "Connecteurs"],
  ["to that end", "à cette fin / dans ce but", "To that end, a task force was set up.", "Connecteurs"],
  ["by the same token", "de même / par la même logique", "By the same token, prices may fall.", "Connecteurs"],
  ["that being said", "ceci étant dit / cela dit", "That being said, risks remain.", "Connecteurs"],
  ["all things considered", "tout bien considéré", "All things considered, it went well.", "Connecteurs"],
  ["in essence", "essentiellement / au fond", "In essence, the plan is sound.", "Connecteurs"],
  ["more often than not", "le plus souvent / la plupart du temps", "More often than not, he is right.", "Connecteurs"],
  ["not least because", "notamment parce que / d'autant que", "It matters, not least because time is short.", "Connecteurs"],
  ["in no small part", "en grande partie / pour beaucoup", "Success was due, in no small part, to luck.", "Connecteurs"],
  ["to a large extent", "dans une large mesure", "To a large extent, this is true.", "Connecteurs"],
  ["as such", "à ce titre / en tant que tel", "He is the founder and, as such, decides.", "Connecteurs"],
  ["in stark contrast", "en net contraste", "In stark contrast, sales abroad fell.", "Connecteurs"],
  ["by virtue of", "en vertu de / grâce à", "By virtue of her role, she has access.", "Connecteurs"],
  ["notwithstanding", "nonobstant / malgré", "Notwithstanding the delay, we succeeded.", "Connecteurs"]

]);
