/* ============================================================
   990 — Vocabulaire bilingue, 3e vague (sport, arts, société, droit, science…)
   Format : [recto EN, verso FR, exemple EN, thème]
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  /* --- Sport & loisirs --- */
  ["referee", "l'arbitre", "The referee blew the whistle.", "Sport"],
  ["opponent", "l'adversaire", "She beat a tough opponent.", "Sport"],
  ["goalkeeper", "le gardien de but", "The goalkeeper made a great save.", "Sport"],
  ["pitch", "le terrain (foot/rugby)", "The players ran onto the pitch.", "Sport"],
  ["tennis court", "le court de tennis", "They booked a tennis court.", "Sport"],
  ["net", "le filet", "The ball hit the net.", "Sport"],
  ["racket", "la raquette", "He restrung his racket.", "Sport"],
  ["treadmill", "le tapis de course", "She ran on the treadmill.", "Sport"],
  ["to warm up", "s'échauffer", "Always warm up before running.", "Sport"],
  ["tournament", "le tournoi", "He reached the final of the tournament.", "Sport"],
  ["hiking", "la randonnée", "We went hiking in the Alps.", "Sport"],
  ["to cheer", "encourager / acclamer", "The crowd cheered wildly.", "Sport"],
  ["spectator", "le spectateur", "Thousands of spectators attended.", "Sport"],
  ["whistle", "le sifflet", "The referee's whistle stopped play.", "Sport"],
  ["draw", "le match nul", "The game ended in a draw.", "Sport"],

  /* --- Arts & culture --- */
  ["canvas", "la toile", "The painter stretched a fresh canvas.", "Arts"],
  ["sculpture", "la sculpture", "A marble sculpture stood in the hall.", "Arts"],
  ["stage", "la scène", "The actors took the stage.", "Arts"],
  ["audience", "le public / l'auditoire", "The audience applauded loudly.", "Arts"],
  ["rehearsal", "la répétition", "The final rehearsal went smoothly.", "Arts"],
  ["plot", "l'intrigue", "The plot has a surprising twist.", "Arts"],
  ["character", "le personnage", "The main character is a detective.", "Arts"],
  ["novel", "le roman", "She's writing her first novel.", "Arts"],
  ["poem", "le poème", "He recited a short poem.", "Arts"],
  ["tune", "l'air / la mélodie", "I can't get that tune out of my head.", "Arts"],
  ["choir", "la chorale / le chœur", "She sings in a choir.", "Arts"],
  ["conductor", "le chef d'orchestre", "The conductor raised his baton.", "Arts"],
  ["exhibit", "l'exposition / la pièce exposée", "The museum's new exhibit opens Friday.", "Arts"],
  ["masterpiece", "le chef-d'œuvre", "The novel is considered a masterpiece.", "Arts"],

  /* --- Politique & société --- */
  ["government", "le gouvernement", "The government announced new measures.", "Société"],
  ["election", "l'élection", "The election is held every five years.", "Société"],
  ["ballot", "le bulletin de vote / le scrutin", "Voters cast their ballots.", "Société"],
  ["poll", "le sondage", "The latest poll shows a tight race.", "Société"],
  ["candidate", "le candidat", "Three candidates are running.", "Société"],
  ["campaign", "la campagne", "She ran a strong campaign.", "Société"],
  ["bill", "le projet de loi ; l'addition", "Congress passed the bill.", "Société"],
  ["citizen", "le citoyen", "Every citizen has the right to vote.", "Société"],
  ["taxpayer", "le contribuable", "Taxpayers funded the project.", "Société"],
  ["welfare", "l'aide sociale / le bien-être", "The welfare system supports families.", "Société"],
  ["bias", "le parti pris / le biais", "The report showed a clear bias.", "Société"],
  ["turnout", "le taux de participation", "Voter turnout was low.", "Société"],
  ["pledge", "l'engagement / la promesse", "He made a pledge to cut taxes.", "Société"],
  ["to enforce", "faire respecter / appliquer", "Police enforce the law.", "Société"],
  ["to ban", "interdire", "The city banned plastic bags.", "Société"],
  ["mayor", "le maire", "The mayor gave a speech.", "Société"],
  ["spokesperson", "le porte-parole", "A spokesperson denied the claims.", "Société"],
  ["protest", "la manifestation / la protestation", "Thousands joined the protest.", "Société"],

  /* --- Droit & justice --- */
  ["trial", "le procès", "The trial lasted three weeks.", "Droit"],
  ["court", "le tribunal / la cour", "The case went to court.", "Droit"],
  ["jury", "le jury", "The jury reached a verdict.", "Droit"],
  ["witness", "le témoin", "A key witness testified.", "Droit"],
  ["evidence", "les preuves / la preuve", "There was no evidence of fraud.", "Droit"],
  ["guilty", "coupable", "The jury found him guilty.", "Droit"],
  ["to sue", "poursuivre en justice", "She threatened to sue the company.", "Droit"],
  ["lawsuit", "le procès / l'action en justice", "They filed a lawsuit.", "Droit"],
  ["sentence", "la peine / la condamnation", "He received a five-year sentence.", "Droit"],
  ["fine", "l'amende", "She paid a heavy fine.", "Droit"],
  ["to convict", "condamner (reconnaître coupable)", "He was convicted of theft.", "Droit"],
  ["defendant", "l'accusé / le prévenu", "The defendant pleaded not guilty.", "Droit"],
  ["oath", "le serment", "The witness took an oath.", "Droit"],
  ["bail", "la caution / la liberté sous caution", "She was released on bail.", "Droit"],

  /* --- Science & recherche --- */
  ["research", "la recherche", "The research took years.", "Science"],
  ["experiment", "l'expérience / l'expérimentation", "They ran a careful experiment.", "Science"],
  ["sample", "l'échantillon", "They tested a large sample.", "Science"],
  ["theory", "la théorie", "The theory was later confirmed.", "Science"],
  ["cell", "la cellule", "The human body has trillions of cells.", "Science"],
  ["gene", "le gène", "The gene controls eye colour.", "Science"],
  ["gravity", "la gravité / la pesanteur", "Gravity pulls objects downward.", "Science"],
  ["mixture", "le mélange", "Stir the mixture gently.", "Science"],
  ["to freeze", "geler / congeler", "Water freezes at zero degrees.", "Science"],
  ["to dissolve", "dissoudre / se dissoudre", "Sugar dissolves in water.", "Science"],
  ["breakthrough", "la percée / l'avancée majeure", "A medical breakthrough was announced.", "Science"],
  ["findings", "les résultats / les conclusions", "The findings were surprising.", "Science"],
  ["accurate", "exact / précis", "The measurements were accurate.", "Science"],

  /* --- Verbes de parole & attitude --- */
  ["to mumble", "marmonner", "He mumbled an apology.", "Verbes"],
  ["to yell", "hurler / crier", "She yelled at the referee.", "Verbes"],
  ["to grumble", "ronchonner / râler", "He grumbled about the price.", "Verbes"],
  ["to praise", "féliciter / faire l'éloge de", "The teacher praised her work.", "Verbes"],
  ["to scold", "gronder / réprimander", "She scolded the children.", "Verbes"],
  ["to warn", "avertir / prévenir", "I warned him about the risk.", "Verbes"],
  ["to threaten", "menacer", "They threatened to resign.", "Verbes"],
  ["to beg", "supplier / mendier", "He begged her to stay.", "Verbes"],
  ["to complain", "se plaindre", "Customers complained about the delay.", "Verbes"],
  ["to confess", "avouer / confesser", "He confessed to the crime.", "Verbes"],
  ["to deny", "nier / démentir", "She denied the accusation.", "Verbes"],
  ["to admit", "admettre / reconnaître", "He admitted his mistake.", "Verbes"],
  ["to swap", "échanger / troquer", "Let's swap seats.", "Verbes"],
  ["to quit", "arrêter / démissionner", "She quit her job last month.", "Verbes"],

  /* --- Adjectifs expressifs (C1-C2) --- */
  ["worthwhile", "qui en vaut la peine", "It was a worthwhile investment.", "Adjectifs"],
  ["far-fetched", "tiré par les cheveux", "His excuse sounded far-fetched.", "Adjectifs"],
  ["groundbreaking", "révolutionnaire / novateur", "A groundbreaking discovery.", "Adjectifs"],
  ["outstanding", "exceptionnel / remarquable", "She gave an outstanding performance.", "Adjectifs"],
  ["dreadful", "épouvantable / affreux", "The weather was dreadful.", "Adjectifs"],
  ["appalling", "effroyable / consternant", "The conditions were appalling.", "Adjectifs"],
  ["staggering", "stupéfiant / vertigineux", "The costs were staggering.", "Adjectifs"],
  ["negligible", "négligeable / infime", "The difference was negligible.", "Adjectifs"],
  ["tedious", "fastidieux / ennuyeux", "Data entry is tedious work.", "Adjectifs"],
  ["daunting", "intimidant / décourageant", "It was a daunting task.", "Adjectifs"],
  ["seamless", "sans accroc / fluide", "The transition was seamless.", "Adjectifs"],
  ["thriving", "florissant / prospère", "A thriving local economy.", "Adjectifs"],
  ["sluggish", "lent / atone / mou", "Sales have been sluggish.", "Adjectifs"],
  ["lucrative", "lucratif / rentable", "A lucrative business deal.", "Adjectifs"],
  ["redundant", "superflu ; licencié (job)", "The information is redundant.", "Adjectifs"],

  /* --- Locutions de temps & quantité --- */
  ["a handful of", "une poignée de", "Only a handful of people came.", "Connecteurs"],
  ["scarcely", "à peine / tout juste", "She had scarcely spoken.", "Connecteurs"],
  ["overall", "globalement / dans l'ensemble", "Overall, the year was positive.", "Connecteurs"],
  ["on the whole", "dans l'ensemble / tout compte fait", "On the whole, it went well.", "Connecteurs"],
  ["at once", "tout de suite ; à la fois", "Come here at once.", "Connecteurs"],
  ["for good", "pour de bon / définitivement", "He left the country for good.", "Connecteurs"],
  ["in the meantime", "en attendant / entre-temps", "In the meantime, stay calm.", "Connecteurs"],
  ["sooner or later", "tôt ou tard", "He'll find out sooner or later.", "Connecteurs"],
  ["all of a sudden", "tout à coup / soudain", "All of a sudden, the lights went out.", "Connecteurs"],
  ["from scratch", "à partir de zéro", "She built the company from scratch.", "Connecteurs"],
  ["off the top of my head", "de tête / comme ça", "Off the top of my head, I'd say fifty.", "Connecteurs"],
  ["by and large", "dans l'ensemble / de manière générale", "By and large, customers are happy.", "Connecteurs"]

]);
