/* ============================================================
   990 — Vocabulaire "vraiment bilingue" : quotidien + avancé (C1-C2)
   Format identique : [recto EN, verso FR, exemple EN, thème]
   Ajouté au vivier VOCAB existant (business).
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  /* --- Animaux --- */
  ["crane", "la grue (oiseau ET engin de chantier)", "A crane lifted the steel beams onto the roof.", "Animaux"],
  ["hedgehog", "le hérisson", "A hedgehog curled up under the hedge.", "Animaux"],
  ["squirrel", "l'écureuil", "A squirrel buried an acorn in the garden.", "Animaux"],
  ["owl", "le hibou / la chouette", "An owl hooted in the dark forest.", "Animaux"],
  ["bat", "la chauve-souris", "Bats hunt insects at dusk.", "Animaux"],
  ["deer", "le cerf / la biche", "A deer crossed the road at dawn.", "Animaux"],
  ["fox", "le renard", "The fox slipped through the fence.", "Animaux"],
  ["snail", "l'escargot", "A snail left a trail on the wall.", "Animaux"],
  ["ant", "la fourmi", "Ants marched across the kitchen counter.", "Animaux"],
  ["bee", "l'abeille", "A bee landed on the flower.", "Animaux"],
  ["wasp", "la guêpe", "A wasp is more aggressive than a bee.", "Animaux"],
  ["spider", "l'araignée", "A spider spun a web in the corner.", "Animaux"],
  ["frog", "la grenouille", "The frog leapt into the pond.", "Animaux"],
  ["snake", "le serpent", "The snake slid into the grass.", "Animaux"],
  ["turtle", "la tortue", "The turtle slowly crossed the sand.", "Animaux"],
  ["swan", "le cygne", "Two swans glided across the lake.", "Animaux"],
  ["ladybug", "la coccinelle", "A ladybug landed on my finger.", "Animaux"],
  ["otter", "la loutre", "An otter floated on its back.", "Animaux"],
  ["hare", "le lièvre", "A hare is faster than a rabbit.", "Animaux"],
  ["moth", "le papillon de nuit / la mite", "A moth fluttered around the lamp.", "Animaux"],

  /* --- Nature & météo --- */
  ["oak", "le chêne", "An old oak stood in the middle of the field.", "Nature"],
  ["willow", "le saule", "A willow leaned over the river.", "Nature"],
  ["pine", "le pin", "The air smelled of pine.", "Nature"],
  ["acorn", "le gland", "Squirrels collect acorns in autumn.", "Nature"],
  ["twig", "la brindille", "She snapped a twig off the branch.", "Nature"],
  ["root", "la racine", "The tree's roots cracked the pavement.", "Nature"],
  ["puddle", "la flaque", "The child jumped in every puddle.", "Nature"],
  ["dew", "la rosée", "Dew covered the grass this morning.", "Nature"],
  ["fog", "le brouillard", "Thick fog delayed the flights.", "Nature"],
  ["frost", "le givre / le gel", "Frost covered the windshield overnight.", "Nature"],
  ["hail", "la grêle", "Hail damaged the car's roof.", "Nature"],
  ["thunder", "le tonnerre", "Thunder rumbled in the distance.", "Nature"],
  ["lightning", "l'éclair / la foudre", "Lightning struck the old barn.", "Nature"],
  ["breeze", "la brise", "A cool breeze came off the sea.", "Nature"],
  ["pebble", "le caillou / le galet", "She skipped a pebble across the water.", "Nature"],
  ["mud", "la boue", "Our boots were covered in mud.", "Nature"],
  ["cliff", "la falaise", "The path ran along the edge of the cliff.", "Nature"],
  ["stream", "le ruisseau", "A stream ran through the valley.", "Nature"],
  ["shore", "le rivage", "We walked along the shore at sunset.", "Nature"],

  /* --- Outils & bricolage --- */
  ["hammer", "le marteau", "He hit the nail with a hammer.", "Bricolage"],
  ["nail", "le clou", "The nail bent when I hammered it.", "Bricolage"],
  ["screw", "la vis", "Tighten the screw with a screwdriver.", "Bricolage"],
  ["screwdriver", "le tournevis", "I need a smaller screwdriver.", "Bricolage"],
  ["drill", "la perceuse", "Use the drill to make a hole.", "Bricolage"],
  ["saw", "la scie", "He cut the plank with a saw.", "Bricolage"],
  ["ladder", "l'échelle", "She climbed the ladder to fix the gutter.", "Bricolage"],
  ["wrench", "la clé (à molette)", "Use a wrench to loosen the bolt.", "Bricolage"],
  ["pliers", "la pince", "Grip the wire with the pliers.", "Bricolage"],
  ["shovel", "la pelle", "He dug the hole with a shovel.", "Bricolage"],
  ["rake", "le râteau", "She raked the leaves into a pile.", "Bricolage"],
  ["wheelbarrow", "la brouette", "He pushed a wheelbarrow full of soil.", "Bricolage"],
  ["bucket", "le seau", "Fill the bucket with water.", "Bricolage"],
  ["broom", "le balai", "Sweep the floor with a broom.", "Bricolage"],
  ["hose", "le tuyau (d'arrosage)", "Water the plants with the hose.", "Bricolage"],
  ["glue", "la colle", "A drop of glue will hold it.", "Bricolage"],

  /* --- Cuisine & nourriture --- */
  ["sink", "l'évier", "The dishes are piled in the sink.", "Cuisine"],
  ["tap", "le robinet", "Turn off the tap while brushing.", "Cuisine"],
  ["kettle", "la bouilloire", "The kettle is boiling.", "Cuisine"],
  ["frying pan", "la poêle", "Heat some oil in the frying pan.", "Cuisine"],
  ["saucepan", "la casserole", "Simmer the sauce in a saucepan.", "Cuisine"],
  ["lid", "le couvercle", "Put the lid on the pot.", "Cuisine"],
  ["ladle", "la louche", "Serve the soup with a ladle.", "Cuisine"],
  ["whisk", "le fouet", "Whisk the eggs until fluffy.", "Cuisine"],
  ["grater", "la râpe", "Grate the cheese with a grater.", "Cuisine"],
  ["chopping board", "la planche à découper", "Slice the onion on the chopping board.", "Cuisine"],
  ["dough", "la pâte (à pain)", "Let the dough rise for an hour.", "Cuisine"],
  ["leftovers", "les restes", "We ate the leftovers for lunch.", "Cuisine"],
  ["to simmer", "mijoter", "Let it simmer for twenty minutes.", "Cuisine"],
  ["to knead", "pétrir", "Knead the dough for ten minutes.", "Cuisine"],
  ["ripe", "mûr (fruit)", "The bananas aren't ripe yet.", "Cuisine"],
  ["stale", "rassis / pas frais", "The bread has gone stale.", "Cuisine"],
  ["to melt", "fondre", "Let the butter melt slowly.", "Cuisine"],
  ["sour", "aigre / acide", "The milk tastes sour.", "Cuisine"],
  ["to boil", "bouillir / faire bouillir", "Boil the water first.", "Cuisine"],

  /* --- Maison & mobilier --- */
  ["drawer", "le tiroir", "The forks are in the top drawer.", "Maison"],
  ["shelf", "l'étagère", "Put the book back on the shelf.", "Maison"],
  ["ceiling", "le plafond", "There's a crack in the ceiling.", "Maison"],
  ["attic", "le grenier", "We store old boxes in the attic.", "Maison"],
  ["basement", "la cave / le sous-sol", "The washing machine is in the basement.", "Maison"],
  ["hallway", "le couloir / l'entrée", "Leave your shoes in the hallway.", "Maison"],
  ["curtain", "le rideau", "Draw the curtains at night.", "Maison"],
  ["pillow", "l'oreiller", "This pillow is too soft.", "Maison"],
  ["blanket", "la couverture", "Pull the blanket over you.", "Maison"],
  ["carpet", "le tapis / la moquette", "They vacuumed the carpet.", "Maison"],
  ["lightbulb", "l'ampoule", "The lightbulb burned out.", "Maison"],
  ["socket", "la prise (électrique)", "Plug it into the socket by the door.", "Maison"],
  ["doorknob", "la poignée de porte", "The doorknob is loose.", "Maison"],
  ["sink (bathroom)", "le lavabo", "He washed his hands at the sink.", "Maison"],

  /* --- Corps & santé --- */
  ["eyebrow", "le sourcil", "She raised an eyebrow in surprise.", "Corps"],
  ["eyelash", "le cil", "An eyelash fell into my eye.", "Corps"],
  ["cheek", "la joue", "The cold wind stung his cheeks.", "Corps"],
  ["chin", "le menton", "He rested his chin on his hand.", "Corps"],
  ["forehead", "le front", "She wiped the sweat off her forehead.", "Corps"],
  ["jaw", "la mâchoire", "His jaw dropped in shock.", "Corps"],
  ["wrist", "le poignet", "He sprained his wrist playing tennis.", "Corps"],
  ["ankle", "la cheville", "She twisted her ankle on the stairs.", "Corps"],
  ["heel", "le talon", "My new shoes gave me a blister on the heel.", "Corps"],
  ["thumb", "le pouce", "He hit his thumb with the hammer.", "Corps"],
  ["spine", "la colonne vertébrale", "Sit up straight to protect your spine.", "Corps"],
  ["lung", "le poumon", "Smoking damages the lungs.", "Corps"],
  ["to sneeze", "éternuer", "The dust made her sneeze.", "Corps"],
  ["to yawn", "bâiller", "He yawned through the meeting.", "Corps"],
  ["bruise", "le bleu / l'ecchymose", "She got a bruise on her knee.", "Corps"],
  ["sprain", "l'entorse / la foulure", "The doctor said it was just a sprain.", "Corps"],

  /* --- Ville & transport --- */
  ["sidewalk", "le trottoir", "Cyclists shouldn't ride on the sidewalk.", "Ville"],
  ["crosswalk", "le passage piéton", "Cross at the crosswalk.", "Ville"],
  ["roundabout", "le rond-point", "Take the second exit at the roundabout.", "Ville"],
  ["traffic jam", "l'embouteillage", "We were stuck in a traffic jam for an hour.", "Ville"],
  ["toll", "le péage", "There's a toll on the motorway.", "Ville"],
  ["fence", "la clôture / la barrière", "The dog jumped over the fence.", "Ville"],
  ["gate", "le portail", "Please close the gate behind you.", "Ville"],
  ["alley", "la ruelle", "The cat darted down the alley.", "Ville"],
  ["lamppost", "le lampadaire", "He leaned against the lamppost.", "Ville"],
  ["gutter", "le caniveau / la gouttière", "Leaves clogged the gutter.", "Ville"],

  /* --- Vêtements --- */
  ["sleeve", "la manche", "He rolled up his sleeves.", "Vêtements"],
  ["collar", "le col", "Straighten your collar.", "Vêtements"],
  ["zipper", "la fermeture éclair", "The zipper got stuck.", "Vêtements"],
  ["pocket", "la poche", "Keep your phone in your pocket.", "Vêtements"],
  ["shoelace", "le lacet", "Tie your shoelaces.", "Vêtements"],
  ["belt", "la ceinture", "He tightened his belt.", "Vêtements"],
  ["glove", "le gant", "I lost one glove.", "Vêtements"],
  ["scarf", "l'écharpe / le foulard", "Wrap a scarf around your neck.", "Vêtements"],
  ["raincoat", "l'imperméable", "Take a raincoat, it might pour.", "Vêtements"],

  /* --- Verbes du quotidien --- */
  ["to trip", "trébucher", "I tripped over the cable.", "Verbes"],
  ["to squeeze", "presser / serrer", "Squeeze the lemon over the fish.", "Verbes"],
  ["to grab", "attraper / saisir", "Grab your coat, we're leaving.", "Verbes"],
  ["to spill", "renverser (un liquide)", "I spilled coffee on my shirt.", "Verbes"],
  ["to leak", "fuir (avoir une fuite)", "The roof leaks when it rains.", "Verbes"],
  ["to soak", "tremper / faire tremper", "Soak the beans overnight.", "Verbes"],
  ["to rinse", "rincer", "Rinse the glass under cold water.", "Verbes"],
  ["to wipe", "essuyer", "Wipe the table after dinner.", "Verbes"],
  ["to sweep", "balayer", "Sweep the crumbs off the floor.", "Verbes"],
  ["to fold", "plier", "Fold the towels and put them away.", "Verbes"],
  ["to tear", "déchirer", "Be careful not to tear the page.", "Verbes"],
  ["to shrink", "rétrécir", "Wool sweaters shrink in hot water.", "Verbes"],
  ["to bend", "plier / se courber", "Bend your knees when you lift.", "Verbes"],
  ["to lean", "se pencher / s'appuyer", "Don't lean against the wet paint.", "Verbes"],
  ["to crawl", "ramper / marcher à quatre pattes", "The baby crawled across the floor.", "Verbes"],
  ["to sigh", "soupirer", "She sighed and closed the book.", "Verbes"],
  ["to blink", "cligner des yeux", "He blinked in the bright light.", "Verbes"],
  ["to nod", "hocher la tête (oui)", "She nodded in agreement.", "Verbes"],
  ["to shrug", "hausser les épaules", "He just shrugged and walked away.", "Verbes"],
  ["to stare", "fixer (du regard)", "Stop staring at me.", "Verbes"],
  ["to whisper", "chuchoter", "She whispered the answer.", "Verbes"],

  /* --- Adjectifs nuancés (C1) --- */
  ["clumsy", "maladroit", "It was a clumsy attempt to apologize.", "Adjectifs"],
  ["stubborn", "têtu / obstiné", "He's too stubborn to admit he's wrong.", "Adjectifs"],
  ["shrewd", "perspicace / astucieux", "A shrewd investor spots trends early.", "Adjectifs"],
  ["blunt", "direct / brusque ; émoussé", "To be blunt, the plan won't work.", "Adjectifs"],
  ["dull", "terne / ennuyeux", "The lecture was rather dull.", "Adjectifs"],
  ["gloomy", "morose / sombre", "The weather was cold and gloomy.", "Adjectifs"],
  ["cheerful", "joyeux / enjoué", "She gave a cheerful wave.", "Adjectifs"],
  ["reckless", "imprudent / téméraire", "Reckless driving causes accidents.", "Adjectifs"],
  ["cautious", "prudent", "Be cautious when signing contracts.", "Adjectifs"],
  ["thorough", "minutieux / approfondi", "They did a thorough investigation.", "Adjectifs"],
  ["shallow", "superficiel ; peu profond", "The river is shallow here.", "Adjectifs"],
  ["awkward", "gênant / maladroit", "There was an awkward silence.", "Adjectifs"],
  ["cosy", "douillet / confortable", "The cabin was small but cosy.", "Adjectifs"],
  ["scarce", "rare / peu abondant", "Water became scarce during the drought.", "Adjectifs"],
  ["brittle", "cassant / fragile", "Old paper becomes brittle.", "Adjectifs"],
  ["cumbersome", "encombrant / lourd (à gérer)", "The old software is cumbersome to use.", "Adjectifs"],
  ["sleek", "élégant / épuré", "The car has a sleek design.", "Adjectifs"],
  ["eerie", "inquiétant / étrange", "The empty house had an eerie feel.", "Adjectifs"],

  /* --- Verbes soutenus (C1-C2) --- */
  ["to grasp", "saisir (comprendre)", "He quickly grasped the concept.", "Soutenu"],
  ["to convey", "transmettre / exprimer", "Words can't convey how grateful I am.", "Soutenu"],
  ["to hinder", "entraver / gêner", "The storm hindered the rescue effort.", "Soutenu"],
  ["to foster", "favoriser / encourager", "The program fosters innovation.", "Soutenu"],
  ["to alleviate", "soulager / atténuer", "The medicine alleviates the pain.", "Soutenu"],
  ["to undermine", "saper / miner", "The rumors undermined his authority.", "Soutenu"],
  ["to thrive", "prospérer / s'épanouir", "The business thrived after the reform.", "Soutenu"],
  ["to dwindle", "s'amenuiser / diminuer", "Their savings slowly dwindled.", "Soutenu"],
  ["to soar", "monter en flèche", "Prices soared after the shortage.", "Soutenu"],
  ["to plummet", "chuter / s'effondrer", "Sales plummeted last quarter.", "Soutenu"],
  ["to linger", "s'attarder / persister", "A faint smell lingered in the room.", "Soutenu"],
  ["to overlook", "négliger ; donner sur", "We overlooked one important detail.", "Soutenu"],
  ["to acknowledge", "reconnaître / admettre", "She acknowledged her mistake.", "Soutenu"],
  ["to resent", "en vouloir à / mal supporter", "He resented being left out.", "Soutenu"],
  ["to yearn", "aspirer à / languir de", "She yearned for a quieter life.", "Soutenu"],
  ["to loathe", "détester / exécrer", "I loathe getting up early.", "Soutenu"],
  ["to tackle", "s'attaquer à (un problème)", "We must tackle climate change now.", "Soutenu"],
  ["painstaking", "méticuleux / minutieux", "It was painstaking, detailed work.", "Soutenu"],
  ["resilient", "résilient / résistant", "Children are remarkably resilient.", "Soutenu"],
  ["ubiquitous", "omniprésent", "Smartphones are now ubiquitous.", "Soutenu"],

  /* --- Faux-amis (pièges FR/EN) --- */
  ["actually", "en fait (≠ actuellement = currently)", "Actually, that's not what I meant.", "Faux-amis"],
  ["eventually", "finalement / au bout du compte (≠ éventuellement)", "He eventually agreed.", "Faux-amis"],
  ["to attend", "assister à (≠ attendre = to wait)", "She attended the conference.", "Faux-amis"],
  ["sensible", "raisonnable / sensé (≠ sensible = sensitive)", "That's a sensible decision.", "Faux-amis"],
  ["library", "la bibliothèque (≠ librairie = bookshop)", "I borrowed it from the library.", "Faux-amis"],
  ["to demand", "exiger (≠ demander = to ask)", "The workers demanded a raise.", "Faux-amis"],
  ["deception", "la tromperie (≠ déception = disappointment)", "The scheme involved deception.", "Faux-amis"],
  ["to resume", "reprendre (≠ résumer = to summarize)", "They resumed talks after lunch.", "Faux-amis"],
  ["comprehensive", "complet / exhaustif (≠ compréhensif = understanding)", "A comprehensive report.", "Faux-amis"],
  ["location", "l'emplacement (≠ location = rental)", "It's a great location for a shop.", "Faux-amis"],
  ["to achieve", "accomplir / réaliser (≠ achever = to finish off)", "She achieved her goal.", "Faux-amis"],
  ["fabric", "le tissu (≠ fabrique = factory)", "The dress is made of soft fabric.", "Faux-amis"],
  ["to rest", "se reposer (≠ rester = to stay)", "You should rest for a while.", "Faux-amis"],
  ["chance", "l'occasion / le hasard (≠ chance = luck)", "It was my chance to speak.", "Faux-amis"],
  ["to assist", "aider / assister (qqn) (≠ assister à = to attend)", "A nurse assisted the surgeon.", "Faux-amis"],

  /* --- Expressions idiomatiques --- */
  ["to get the hang of it", "prendre le coup de main", "Don't worry, you'll get the hang of it.", "Idiomes"],
  ["to be over the moon", "être aux anges", "She was over the moon about the offer.", "Idiomes"],
  ["to bite the bullet", "serrer les dents / se lancer", "I bit the bullet and called the dentist.", "Idiomes"],
  ["to cost an arm and a leg", "coûter les yeux de la tête", "That car cost an arm and a leg.", "Idiomes"],
  ["to be under the weather", "ne pas être dans son assiette", "I'm a bit under the weather today.", "Idiomes"],
  ["to hit the nail on the head", "mettre le doigt dessus / taper juste", "You hit the nail on the head.", "Idiomes"],
  ["to beat around the bush", "tourner autour du pot", "Stop beating around the bush.", "Idiomes"],
  ["to call it a day", "s'arrêter là (pour aujourd'hui)", "Let's call it a day.", "Idiomes"],
  ["once in a blue moon", "tous les 36 du mois / très rarement", "We meet once in a blue moon.", "Idiomes"],
  ["to spill the beans", "vendre la mèche", "Don't spill the beans about the party.", "Idiomes"],
  ["to break the ice", "briser la glace", "A joke helped break the ice.", "Idiomes"],
  ["the last straw", "la goutte d'eau qui fait déborder le vase", "That was the last straw.", "Idiomes"],
  ["to pull someone's leg", "faire marcher quelqu'un", "Relax, I'm just pulling your leg.", "Idiomes"],
  ["to ring a bell", "dire quelque chose (à qqn)", "The name rings a bell.", "Idiomes"],
  ["to be broke", "être fauché", "I can't go out, I'm broke.", "Idiomes"],
  ["speak of the devil", "quand on parle du loup", "Speak of the devil — here she is!", "Idiomes"],
  ["to make ends meet", "joindre les deux bouts", "It's hard to make ends meet.", "Idiomes"],
  ["to be a piece of cake", "être du gâteau / très facile", "The exam was a piece of cake.", "Idiomes"]

]);
