/* ============================================================
   990 — Vocabulaire « Le monde de demain » (IA, climat, futur du travail,
   numérique, science) — C1-C2, en prévision du futur.
   [EN, FR, exemple EN, thème]
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  // --- IA & Tech ---
  ["artificial intelligence", "l'intelligence artificielle", "Artificial intelligence is reshaping entire industries.", "IA & Tech"],
  ["machine learning", "l'apprentissage automatique", "Machine learning powers the recommendation engine.", "IA & Tech"],
  ["algorithm", "l'algorithme", "The algorithm ranks the search results.", "IA & Tech"],
  ["automation", "l'automatisation", "Automation is transforming factory work.", "IA & Tech"],
  ["to automate", "automatiser", "They automated the entire approval process.", "IA & Tech"],
  ["self-driving", "autonome (véhicule)", "Self-driving cars are being tested on public roads.", "IA & Tech"],
  ["chatbot", "l'agent conversationnel, le chatbot", "A chatbot now handles most customer queries.", "IA & Tech"],
  ["cutting-edge", "de pointe", "It's a piece of cutting-edge technology.", "IA & Tech"],
  ["disruptive", "disruptif, qui bouscule", "They built a disruptive business model.", "IA & Tech"],
  ["to disrupt", "bouleverser (un marché)", "Streaming disrupted the music industry.", "IA & Tech"],
  ["scalable", "évolutif, extensible", "We need a scalable solution.", "IA & Tech"],
  ["to roll out", "déployer", "The feature will roll out globally next week.", "IA & Tech"],
  ["cloud computing", "l'informatique en nuage", "The firm migrated to cloud computing.", "IA & Tech"],
  ["virtual reality", "la réalité virtuelle", "Virtual reality is used for surgical training.", "IA & Tech"],
  ["augmented reality", "la réalité augmentée", "The app overlays data using augmented reality.", "IA & Tech"],
  ["wearable", "l'appareil connecté (porté sur soi)", "Wearables track your heart rate all day.", "IA & Tech"],
  ["data-driven", "fondé sur les données", "We make data-driven decisions.", "IA & Tech"],
  ["to train a model", "entraîner un modèle", "They trained the model on huge datasets.", "IA & Tech"],
  ["seamless", "fluide, sans accroc", "The integration was seamless.", "IA & Tech"],
  ["state-of-the-art", "à la pointe, dernier cri", "A state-of-the-art data centre.", "IA & Tech"],

  // --- Climat & durabilité ---
  ["renewable energy", "l'énergie renouvelable", "Renewable energy is getting cheaper every year.", "Climat"],
  ["solar power", "l'énergie solaire", "Solar power now competes with gas.", "Climat"],
  ["wind power", "l'énergie éolienne", "Wind power supplies much of the region.", "Climat"],
  ["carbon footprint", "l'empreinte carbone", "We aim to cut our carbon footprint in half.", "Climat"],
  ["net zero", "la neutralité carbone", "The company pledged net zero by 2040.", "Climat"],
  ["emissions", "les émissions", "Emissions must fall sharply this decade.", "Climat"],
  ["greenhouse gas", "le gaz à effet de serre", "Methane is a potent greenhouse gas.", "Climat"],
  ["fossil fuels", "les énergies fossiles", "We must phase out fossil fuels.", "Climat"],
  ["to phase out", "supprimer progressivement", "They plan to phase out diesel cars.", "Climat"],
  ["to offset", "compenser (des émissions)", "Companies offset their emissions with tree planting.", "Climat"],
  ["sustainability", "la durabilité", "Sustainability is now a core priority.", "Climat"],
  ["biodiversity", "la biodiversité", "Biodiversity is under serious threat.", "Climat"],
  ["climate crisis", "la crise climatique", "The climate crisis demands urgent action.", "Climat"],
  ["ecosystem", "l'écosystème", "The reef is a fragile ecosystem.", "Climat"],
  ["carbon neutral", "neutre en carbone", "The event was entirely carbon neutral.", "Climat"],
  ["flooding", "les inondations", "Flooding is becoming more frequent.", "Climat"],
  ["to reverse", "inverser (une tendance)", "It may be too late to reverse the damage.", "Climat"],

  // --- Futur du travail ---
  ["remote work", "le télétravail", "Remote work is here to stay.", "Futur du travail"],
  ["hybrid work", "le travail hybride", "Most firms adopted a hybrid work model.", "Futur du travail"],
  ["gig economy", "l'économie des petits boulots", "The gig economy keeps expanding.", "Futur du travail"],
  ["to upskill", "monter en compétences", "Staff are encouraged to upskill regularly.", "Futur du travail"],
  ["to reskill", "se reconvertir", "Thousands of workers had to reskill.", "Futur du travail"],
  ["burnout", "l'épuisement professionnel", "Burnout is a growing workplace concern.", "Futur du travail"],
  ["work-life balance", "l'équilibre vie pro / vie perso", "She left for a better work-life balance.", "Futur du travail"],
  ["four-day week", "la semaine de quatre jours", "Some firms are trialling a four-day week.", "Futur du travail"],
  ["side hustle", "l'activité secondaire", "His side hustle turned into a real business.", "Futur du travail"],
  ["to outsource", "externaliser", "They outsource their customer support.", "Futur du travail"],
  ["layoffs", "les licenciements", "Tech layoffs made headlines this year.", "Futur du travail"],
  ["freelance", "en indépendant, freelance", "She now works freelance.", "Futur du travail"],

  // --- Science & espace ---
  ["spacecraft", "le vaisseau spatial", "The spacecraft entered orbit as planned.", "Science & espace"],
  ["orbit", "l'orbite", "The satellite is in low orbit.", "Science & espace"],
  ["satellite", "le satellite", "They launched a new weather satellite.", "Science & espace"],
  ["gene editing", "la modification génétique", "Gene editing could one day cure inherited diseases.", "Science & espace"],
  ["clinical trial", "l'essai clinique", "The drug passed its final clinical trial.", "Science & espace"],
  ["quantum computing", "l'informatique quantique", "Quantum computing is still in its infancy.", "Science & espace"],
  ["telescope", "le télescope", "The telescope captured distant galaxies.", "Science & espace"],
  ["stem cell", "la cellule souche", "Stem cell therapy shows real promise.", "Science & espace"],
  ["particle", "la particule", "Physicists study subatomic particles.", "Science & espace"],
  ["to hover", "planer, être en vol stationnaire", "The drone hovered above the field.", "Science & espace"],

  // --- Société numérique ---
  ["privacy", "la vie privée", "Users increasingly worry about their privacy.", "Numérique"],
  ["surveillance", "la surveillance", "Mass surveillance raises ethical concerns.", "Numérique"],
  ["data breach", "la fuite de données", "The data breach exposed millions of accounts.", "Numérique"],
  ["cybersecurity", "la cybersécurité", "Cybersecurity is now a boardroom issue.", "Numérique"],
  ["deepfake", "l'hypertrucage, le deepfake", "Deepfakes are used to spread misinformation.", "Numérique"],
  ["misinformation", "la désinformation", "Misinformation spreads faster than facts.", "Numérique"],
  ["to go viral", "devenir viral", "The clip went viral overnight.", "Numérique"],
  ["influencer", "l'influenceur", "Brands increasingly work with influencers.", "Numérique"],
  ["screen time", "le temps d'écran", "She limits her children's screen time.", "Numérique"],
  ["digital divide", "la fracture numérique", "The pandemic widened the digital divide.", "Numérique"],
  ["encryption", "le chiffrement", "The app uses end-to-end encryption.", "Numérique"],
  ["to hack", "pirater", "Hackers hacked into the network.", "Numérique"],
  ["biometric", "biométrique", "Phones now rely on biometric security.", "Numérique"],
  ["subscription", "l'abonnement", "Almost everything is a subscription these days.", "Numérique"],
  ["addictive", "addictif", "These apps are deliberately addictive.", "Numérique"],

  // --- Innovation & économie ---
  ["venture capital", "le capital-risque", "The startup raised venture capital.", "Innovation"],
  ["unicorn", "la licorne (start-up)", "The firm became a unicorn within two years.", "Innovation"],
  ["valuation", "la valorisation", "Its valuation topped a billion dollars.", "Innovation"],
  ["to scale up", "passer à l'échelle", "They struggled to scale up fast enough.", "Innovation"],
  ["forecast", "la prévision", "The forecast points to modest growth.", "Innovation"],
  ["to forecast", "prévoir", "Analysts forecast a slowdown.", "Innovation"],
  ["emerging market", "le marché émergent", "They expanded into emerging markets.", "Innovation"],
  ["supply chain", "la chaîne d'approvisionnement", "Supply chain disruptions persist.", "Innovation"],
  ["to pivot", "pivoter (changer de modèle)", "The startup had to pivot to survive.", "Innovation"],
  ["game changer", "un tournant décisif", "This tool is a real game changer.", "Innovation"],
  ["trailblazer", "le pionnier", "She's a trailblazer in green tech.", "Innovation"],
  ["to future-proof", "pérenniser, préparer à l'avenir", "We must future-proof the business.", "Innovation"],

  // --- Adjectifs & tournures du futur ---
  ["imminent", "imminent", "A major shift is imminent.", "Adjectifs (futur)"],
  ["obsolete", "obsolète", "The technology is already obsolete.", "Adjectifs (futur)"],
  ["foreseeable", "prévisible", "No change is likely in the foreseeable future.", "Adjectifs (futur)"],
  ["far-reaching", "aux effets étendus", "The reform has far-reaching consequences.", "Adjectifs (futur)"],
  ["long-term", "à long terme", "We take a long-term view.", "Adjectifs (futur)"],
  ["short-lived", "éphémère", "The trend proved short-lived.", "Adjectifs (futur)"],
  ["promising", "prometteur", "The early results are promising.", "Adjectifs (futur)"],
  ["to loom", "se profiler (menace)", "A recession looms on the horizon.", "Adjectifs (futur)"],
  ["on the horizon", "à l'horizon", "Sweeping changes are on the horizon.", "Adjectifs (futur)"],
  ["to usher in", "inaugurer, ouvrir la voie à", "The invention ushered in a new era.", "Adjectifs (futur)"],
  ["to reshape", "redessiner, remodeler", "AI is reshaping the labour market.", "Adjectifs (futur)"],
  ["paradigm shift", "le changement de paradigme", "We are witnessing a paradigm shift.", "Adjectifs (futur)"]

]);
