/* ============================================================
   990 — Vocabulaire avancé (C1-C2) : collocations, registre soutenu,
   verbes & connecteurs de haut niveau. Vise la note parfaite.
   Format : [recto EN, verso FR, exemple EN, thème]
   ============================================================ */
window.VOCAB = window.VOCAB.concat([

  /* --- Collocations (associations attendues à l'examen) --- */
  ["to meet a deadline", "respecter une échéance", "They struggled to meet the deadline.", "Collocations"],
  ["to run a business", "gérer une entreprise", "She runs a small business.", "Collocations"],
  ["to take responsibility", "assumer la responsabilité", "He took responsibility for the error.", "Collocations"],
  ["to draw a conclusion", "tirer une conclusion", "It's too early to draw conclusions.", "Collocations"],
  ["to pose a threat", "représenter une menace", "The virus poses a serious threat.", "Collocations"],
  ["to raise awareness", "sensibiliser", "The campaign raised awareness of the issue.", "Collocations"],
  ["to reach a compromise", "parvenir à un compromis", "Both sides reached a compromise.", "Collocations"],
  ["to break a promise", "rompre une promesse", "He never breaks a promise.", "Collocations"],
  ["to make a distinction", "faire une distinction", "We must make a clear distinction here.", "Collocations"],
  ["to bear in mind", "garder à l'esprit", "Bear in mind that prices may change.", "Collocations"],
  ["to take into account", "prendre en compte", "We took the delay into account.", "Collocations"],
  ["to set a precedent", "créer un précédent", "This ruling sets a precedent.", "Collocations"],
  ["to meet a requirement", "satisfaire une exigence", "The design meets every requirement.", "Collocations"],
  ["to strike a balance", "trouver un équilibre", "We must strike a balance between cost and quality.", "Collocations"],
  ["to voice concern", "exprimer une inquiétude", "Residents voiced concern over the plan.", "Collocations"],
  ["to shed light on", "faire la lumière sur / éclairer", "The report sheds light on the causes.", "Collocations"],
  ["to pave the way", "ouvrir la voie", "The deal paved the way for expansion.", "Collocations"],
  ["to take its toll", "faire des ravages / peser lourd", "The long hours took their toll on her health.", "Collocations"],
  ["to jump to conclusions", "tirer des conclusions hâtives", "Let's not jump to conclusions.", "Collocations"],
  ["to take the lead", "prendre les devants / la tête", "Our team took the lead in the project.", "Collocations"],
  ["to gain insight", "acquérir une compréhension", "The survey gave us valuable insight.", "Collocations"],
  ["to weigh the pros and cons", "peser le pour et le contre", "Weigh the pros and cons before deciding.", "Collocations"],
  ["to make headway", "faire des progrès / avancer", "We finally made headway on the talks.", "Collocations"],
  ["to raise the bar", "placer la barre plus haut", "Their product raised the bar for the industry.", "Collocations"],

  /* --- Verbes soutenus (C2) --- */
  ["to allege", "alléguer / prétendre", "The report alleges widespread fraud.", "Soutenu"],
  ["to assert", "affirmer / faire valoir", "She asserted her right to appeal.", "Soutenu"],
  ["to concede", "concéder / admettre", "He conceded that he had been wrong.", "Soutenu"],
  ["to refute", "réfuter", "The study refutes that theory.", "Soutenu"],
  ["to underscore", "souligner / mettre en évidence", "The crisis underscores the need for reform.", "Soutenu"],
  ["to mitigate", "atténuer / limiter", "Measures to mitigate the damage were taken.", "Soutenu"],
  ["to exacerbate", "aggraver / exacerber", "The delay only exacerbated the problem.", "Soutenu"],
  ["to substantiate", "étayer / corroborer", "There's no evidence to substantiate the claim.", "Soutenu"],
  ["to circumvent", "contourner", "They tried to circumvent the rules.", "Soutenu"],
  ["to relinquish", "renoncer à / céder", "He refused to relinquish control.", "Soutenu"],
  ["to reiterate", "réitérer / répéter", "Let me reiterate our position.", "Soutenu"],
  ["to culminate", "culminer / aboutir à", "Years of work culminated in a patent.", "Soutenu"],
  ["to spearhead", "mener / être le fer de lance", "She spearheaded the reform.", "Soutenu"],
  ["to overhaul", "réviser en profondeur / remanier", "They overhauled the entire system.", "Soutenu"],
  ["to streamline", "rationaliser / simplifier", "We streamlined the approval process.", "Soutenu"],
  ["to curtail", "réduire / restreindre", "Spending was sharply curtailed.", "Soutenu"],
  ["to epitomize", "incarner / illustrer parfaitement", "She epitomizes professionalism.", "Soutenu"],
  ["to permeate", "imprégner / se répandre dans", "A sense of doubt permeated the room.", "Soutenu"],
  ["to instigate", "provoquer / être à l'origine de", "He was accused of instigating the strike.", "Soutenu"],
  ["to reconcile with", "concilier / accorder", "It's hard to reconcile the two accounts.", "Soutenu"],

  /* --- Adjectifs soutenus (C2) --- */
  ["meticulous", "méticuleux / minutieux", "Her meticulous notes saved us hours.", "Soutenu"],
  ["scrupulous", "scrupuleux / rigoureux", "He was scrupulous about the accounts.", "Soutenu"],
  ["candid", "franc / sincère", "She gave a candid assessment.", "Soutenu"],
  ["astute", "astucieux / perspicace", "An astute observer of markets.", "Soutenu"],
  ["versatile", "polyvalent", "A versatile and reliable employee.", "Soutenu"],
  ["ambivalent", "ambivalent / partagé", "I feel ambivalent about the move.", "Soutenu"],
  ["unprecedented", "sans précédent", "Sales reached unprecedented levels.", "Soutenu"],
  ["detrimental", "préjudiciable / nuisible", "Stress is detrimental to health.", "Soutenu"],
  ["conducive", "propice / favorable", "A quiet room is conducive to study.", "Soutenu"],
  ["viable", "viable / réalisable", "It's the only viable option.", "Soutenu"],
  ["coherent", "cohérent", "We need a coherent strategy.", "Soutenu"],
  ["ambiguous", "ambigu", "The wording is deliberately ambiguous.", "Soutenu"],
  ["superfluous", "superflu", "Cut any superfluous detail.", "Soutenu"],
  ["paramount", "primordial / capital", "Safety is of paramount importance.", "Soutenu"],
  ["inevitable", "inévitable", "A downturn seemed inevitable.", "Soutenu"],
  ["prudent", "prudent / avisé", "It would be prudent to wait.", "Soutenu"],

  /* --- Noms soutenus (C2) --- */
  ["nuance", "la nuance", "He grasped every nuance of the argument.", "Soutenu"],
  ["discrepancy", "l'écart / la divergence", "There's a discrepancy in the figures.", "Soutenu"],
  ["setback", "le revers / le contretemps", "The launch suffered a major setback.", "Soutenu"],
  ["leverage", "l'effet de levier / l'influence", "They used their size as leverage.", "Soutenu"],
  ["turmoil", "la tourmente / l'agitation", "The market was in turmoil.", "Soutenu"],
  ["scrutiny", "l'examen minutieux", "The deal came under close scrutiny.", "Soutenu"],
  ["endeavour", "l'entreprise / l'effort", "We wish you well in your endeavour.", "Soutenu"],
  ["hindrance", "l'obstacle / l'entrave", "Red tape is a real hindrance.", "Soutenu"],
  ["consensus", "le consensus", "There's no consensus on the issue.", "Soutenu"],
  ["backlash", "la levée de boucliers / la réaction hostile", "The policy sparked a backlash.", "Soutenu"],
  ["caveat", "la mise en garde / la réserve", "One caveat: results may vary.", "Soutenu"],
  ["rationale", "la logique / la justification", "Explain the rationale behind the choice.", "Soutenu"],
  ["threshold", "le seuil", "Income above this threshold is taxed.", "Soutenu"],
  ["outlook", "les perspectives", "The economic outlook is uncertain.", "Soutenu"],

  /* --- Connecteurs & adverbes de haut niveau --- */
  ["arguably", "sans doute / on peut soutenir que", "It's arguably their best product.", "Connecteurs"],
  ["ostensibly", "en apparence / soi-disant", "He left, ostensibly to make a call.", "Connecteurs"],
  ["conversely", "à l'inverse / inversement", "Prices fell; conversely, demand rose.", "Connecteurs"],
  ["notably", "notamment / en particulier", "Several firms, notably ours, opposed it.", "Connecteurs"],
  ["invariably", "invariablement / toujours", "He is invariably late.", "Connecteurs"],
  ["accordingly", "en conséquence / par conséquent", "The rules changed; act accordingly.", "Connecteurs"],
  ["hitherto", "jusqu'ici / jusqu'à présent", "A hitherto unknown risk emerged.", "Connecteurs"],
  ["insofar as", "dans la mesure où", "It helps insofar as it saves time.", "Connecteurs"],
  ["to a certain extent", "dans une certaine mesure", "I agree, to a certain extent.", "Connecteurs"],
  ["by no means", "en aucun cas / nullement", "The matter is by no means settled.", "Connecteurs"],
  ["all the more", "d'autant plus", "That makes it all the more important.", "Connecteurs"],
  ["for the time being", "pour l'instant / pour le moment", "For the time being, nothing changes.", "Connecteurs"],
  ["with regard to", "en ce qui concerne", "With regard to your request, see below.", "Connecteurs"],
  ["by and large", "dans l'ensemble", "By and large, the plan worked.", "Connecteurs"],
  ["needless to say", "inutile de dire / bien entendu", "Needless to say, we were thrilled.", "Connecteurs"],

  /* --- Registre soutenu (formel, utile pour l'écrit/Reading) --- */
  ["to purchase", "acheter (soutenu)", "Tickets can be purchased online.", "Registre"],
  ["to obtain", "obtenir", "You must obtain prior approval.", "Registre"],
  ["to seek", "chercher / rechercher (soutenu)", "The firm is seeking new partners.", "Registre"],
  ["to reside", "résider / habiter (soutenu)", "Applicants must reside in the region.", "Registre"],
  ["to commence", "commencer (soutenu)", "Boarding will commence shortly.", "Registre"],
  ["to utilize", "utiliser (soutenu)", "Please utilize the resources provided.", "Registre"],
  ["subsequently", "par la suite / ensuite", "He was fired and subsequently sued.", "Registre"],
  ["prior to", "avant (soutenu)", "Arrive prior to the start time.", "Registre"],
  ["regarding", "concernant / au sujet de", "I'm writing regarding your invoice.", "Registre"],
  ["pending", "en attendant / en instance", "The decision is pending review.", "Registre"],
  ["henceforth", "désormais / dorénavant", "Henceforth, all reports must be digital.", "Registre"],
  ["thereby", "de ce fait / ainsi", "He resigned, thereby ending the dispute.", "Registre"]

]);
